#!/usr/bin/env bash
# Generated by scripts/build-deploy.sh — do not edit directly.
# setup-user-cursor.sh — Sets up Cursor CLI + dependencies on macOS/Linux
# Self-contained. No repo or Drive needed.
# Safe to re-run — checks each step and skips what's already done.
#
# Does three things:
#   1. Installs ripgrep (rg) if not already present (required by Cursor CLI)
#   2. Installs Cursor CLI (agent command) if not already present
#   3. Merges preferences into ~/.cursor/cli-config.json (preserves CLI-managed fields)

set -euo pipefail

# --- Logging ---
LOG_DIR="$HOME/Library/Logs/aitools"
[ "$(uname -s)" != "Darwin" ] && LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/aitools"
LOG_FILE="$LOG_DIR/deploy.log"
SCRIPT_NAME="setup-user-cursor"
ERRORS=0

mkdir -p "$LOG_DIR"

log()       { printf '[%s] [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$SCRIPT_NAME" "$1" | tee -a "$LOG_FILE"; }
log_ok()    { log "OK: $1"; }
log_error() { log "ERROR: $1"; ERRORS=$((ERRORS + 1)); }
log_warn()  { log "WARN: $1"; }

# --- OS guard ---
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        log_error "This script is for macOS/Linux. On Windows, use the .ps1 version."
        exit 1 ;;
esac

CURSOR_DIR="$HOME/.cursor"
CLI_CONFIG="$CURSOR_DIR/cli-config.json"

# --- 1. ripgrep (rg) ---
log "Step 1: ripgrep (rg)"

if command -v rg &>/dev/null; then
    RG_VERSION=$(rg --version | head -1)
    log_ok "Already installed: $RG_VERSION"
else
    if command -v brew &>/dev/null; then
        log "Installing ripgrep via brew..."
        brew install ripgrep
        if command -v rg &>/dev/null; then
            log_ok "Installed: $(rg --version | head -1)"
        else
            log_error "brew install completed but 'rg' not found in PATH"
        fi
    else
        log_error "Homebrew not found. Install ripgrep manually: brew install ripgrep"
    fi
fi

# --- 2. Cursor CLI (agent) ---
log "Step 2: Cursor CLI (agent)"

if command -v agent &>/dev/null; then
    AGENT_VERSION=$(agent --version)
    log_ok "Already installed: $AGENT_VERSION"
else
    log "Installing Cursor CLI..."
    curl https://cursor.com/install -fsS | bash
    if command -v agent &>/dev/null; then
        log_ok "Installed: $(agent --version)"
    else
        log_error "Cursor CLI install completed but 'agent' not found in PATH (restart terminal)"
    fi
fi

# --- 3. cli-config.json (merge, not overwrite) ---
log "Step 3: cli-config.json"

mkdir -p "$CURSOR_DIR"

if ! command -v node &>/dev/null; then
    log_warn "node not found -- skipping cli-config.json merge"
else
    MERGE_RESULT=$(node -e "
const fs = require('fs');
const f = process.argv[1];

// --- Embedded preferences (from profile.json at build time) ---
const vimMode = true;
const modelId = 'auto';

// --- Read existing cli-config.json ---
let config = {};
try { config = JSON.parse(fs.readFileSync(f, 'utf8')); } catch {}
const before = JSON.stringify(config);

// --- Merge managed fields ---
config.version = 1;
if (!config.editor) config.editor = {};
config.editor.vimMode = vimMode;
if (!config.permissions) config.permissions = {};
if (!Array.isArray(config.permissions.allow)) config.permissions.allow = [];
if (!Array.isArray(config.permissions.deny)) config.permissions.deny = [];

if (modelId === 'auto') {
    config.model = {
        modelId: 'default',
        displayModelId: 'auto',
        displayName: 'Auto',
        displayNameShort: 'Auto',
        aliases: ['auto'],
        maxMode: false
    };
    config.hasChangedDefaultModel = true;
}

// All other fields (authInfo, privacyCache, network, statsigBootstrap, maxMode, etc.)
// are preserved -- we never delete keys we don't manage.

const after = JSON.stringify(config);
if (before === after) {
    console.log('unchanged');
} else {
    fs.writeFileSync(f, JSON.stringify(config, null, 2) + '\\n');
    console.log(before === '{}' ? 'created' : 'merged');
}
" "$CLI_CONFIG")

    case "$MERGE_RESULT" in
        unchanged) log_ok "Already up to date: $CLI_CONFIG" ;;
        created)   log_ok "Created: $CLI_CONFIG" ;;
        merged)    log_ok "Merged preferences into: $CLI_CONFIG" ;;
        *)         log_error "Unexpected merge result: $MERGE_RESULT" ;;
    esac
fi

# --- Exit ---
if [ "$ERRORS" -gt 0 ]; then
    log "FAILED with $ERRORS error(s). See log: $LOG_FILE"
    exit 1
else
    log "COMPLETED successfully"
    exit 0
fi
