#!/usr/bin/env bash
# Generated by scripts/build-deploy.sh — do not edit directly.
# setup-gh-cli.sh — Installs/updates GitHub CLI (gh)
# Safe to re-run — detects existing install and upgrades as needed.
#
# macOS: Uses Homebrew (brew install gh).
# Linux: Uses apt + GitHub CLI keyring (added on first install only).
#        Falls back with warning on non-apt systems.
#
# Auth (gh auth login) is interactive — handled by aitools-install Step 2, not here.
#
# See reference/tool-registry.md for install source details.

set -euo pipefail

# --- Shared library ---
# aitools-lib.sh -- shared helpers for all aitools bash scripts
# Sourced, not executed directly. No shebang, no set -euo pipefail (caller sets it).
#
# Provides: platform detection, display_path, read_config_key, logging_init,
# log/log_ok/log_error/log_warn, write_summary, show_summary,
# SORT_KEYS_JS, normalize_json.
#
# Usage:
#   source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/aitools-lib.sh"
#   logging_init "script-name"
#
# Entry points (aitools, aitools-install) override log functions after sourcing
# for specialized logging (file-only, JSONL, etc.).

# ---------------------------------------------------------------------------
# Platform detection
# ---------------------------------------------------------------------------
IS_MACOS=false
IS_WINDOWS=false
case "$(uname -s)" in
    Darwin*)              IS_MACOS=true ;;
    MINGW*|MSYS*|CYGWIN*) IS_WINDOWS=true ;;
esac

# ---------------------------------------------------------------------------
# Log directory (platform-aware)
# ---------------------------------------------------------------------------
AITOOLS_LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/aitools"
$IS_MACOS && AITOOLS_LOG_DIR="$HOME/Library/Logs/aitools"

# ---------------------------------------------------------------------------
# Module-level counters (safe for sourcing without logging_init under set -u)
# ---------------------------------------------------------------------------
ERRORS=0
WARNINGS=0

# ---------------------------------------------------------------------------
# Display-friendly path (native Windows on MSYS, no-op elsewhere)
# ---------------------------------------------------------------------------
display_path() {
    if command -v cygpath &>/dev/null; then
        cygpath -w "$1"
    else
        printf '%s' "$1"
    fi
}

# ---------------------------------------------------------------------------
# Config reader (pure bash, handles UTF-8 BOM)
# ---------------------------------------------------------------------------
# Read a top-level string value from a JSON config file.
# Handles UTF-8 BOM (PowerShell 5.x writes one) and JSON-escaped backslashes.
read_config_key() {
    local file="$1" key="$2"
    [ -f "$file" ] || return 1
    local val
    val=$(tr -d '\357\273\277' < "$file" \
        | grep -o "\"$key\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
        | head -1 \
        | cut -d'"' -f4)
    [ -n "$val" ] || return 1
    # Unescape JSON backslashes: \\ -> \
    printf '%b' "$val"
}

# ---------------------------------------------------------------------------
# Logging init
# ---------------------------------------------------------------------------
# Sets SCRIPT_NAME, LOG_DIR, LOG_FILE; resets ERRORS, WARNINGS; creates log dir.
# Usage: logging_init "setup-foo"
logging_init() {
    SCRIPT_NAME="${1:?logging_init requires a script name}"
    LOG_DIR="$AITOOLS_LOG_DIR"
    LOG_FILE="$LOG_DIR/deploy.log"
    mkdir -p "$LOG_DIR"
    ERRORS=0
    WARNINGS=0
}

# ---------------------------------------------------------------------------
# Standard logging (Pattern A: console + log file, with [level] tag)
# ---------------------------------------------------------------------------
log() {
    local level="${2:-info}"
    local ts; ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    local line="[$ts] [$SCRIPT_NAME] [$level] $1"
    printf '%s\n' "$line" >> "$LOG_FILE"
    case "$level" in
        error) printf '\033[31m%s\033[0m\n' "$line" ;;
        warn)  printf '\033[33m%s\033[0m\n' "$line" ;;
        *)     printf '%s\n' "$line" ;;
    esac
}
log_ok()    { log "$1" "ok"; }
log_error() { log "$1" "error"; ERRORS=$((ERRORS + 1)); }
log_warn()  { log "$1" "warn"; WARNINGS=$((WARNINGS + 1)); }

# ---------------------------------------------------------------------------
# Summary writer (3-arg: category, tool, detail)
# ---------------------------------------------------------------------------
write_summary() {
    if [ -n "${AITOOLS_SUMMARY_FILE:-}" ]; then
        printf '%s|%s|%s\n' "$1" "$2" "$3" >> "$AITOOLS_SUMMARY_FILE"
    fi
}

# ---------------------------------------------------------------------------
# Backup a file before overwriting. Keeps at most $max_backups copies.
# ---------------------------------------------------------------------------
backup_file() {
    local file="$1" max_backups=20
    [ -f "$file" ] || return 0
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    cp "$file" "${file}.bak.${ts}"
    # Prune oldest beyond limit
    ls -1t "${file}.bak."* 2>/dev/null | tail -n +$((max_backups + 1)) | xargs rm -f 2>/dev/null
    log "Backed up $(display_path "$file")"
}

# ---------------------------------------------------------------------------
# Backup a directory before modifying managed files. Keeps at most $max_backups copies.
# ---------------------------------------------------------------------------
backup_dir() {
    local dir="$1" max_backups=5
    [ -d "$dir" ] || return 0
    local file_count
    file_count=$(find "$dir" -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')
    if [ "$file_count" -eq 0 ]; then
        return 0
    fi
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    if ! cp -R "$dir" "${dir}.bak.${ts}"; then
        log_warn "Could not back up $(display_path "$dir") -- proceeding without backup"
        return 0
    fi
    local old_backups
    old_backups=$(find "$(dirname "$dir")" -maxdepth 1 -name "$(basename "$dir").bak.*" -type d \
        | sort -r | tail -n +$((max_backups + 1)))
    if [ -n "$old_backups" ]; then
        printf '%s\n' "$old_backups" | while IFS= read -r old_dir; do
            rm -rf "$old_dir"
            log "Pruned old backup: $(display_path "$old_dir")"
        done
    fi
    log "Backed up $(display_path "$dir") ($file_count managed files)"
}

# ---------------------------------------------------------------------------
# Parse CHANGED: lines from a node merge result and emit DETAIL summary entries.
# Usage: emit_merge_details "$MERGE_RESULT" "tool_name"
# Only processes lines prefixed with "CHANGED: " -- ignores status and other output.
# ---------------------------------------------------------------------------
emit_merge_details() {
    local merge_result="$1" tool_name="$2"
    local changed_keys
    changed_keys=$(echo "$merge_result" | perl -ne 'print if s/^CHANGED: //')
    if [ -n "$changed_keys" ]; then
        while IFS= read -r key_change; do
            log "  $key_change"
            write_summary DETAIL "$tool_name" "$key_change"
        done <<< "$changed_keys"
    fi
}

# ---------------------------------------------------------------------------
# JSON normalization for comparison (sorted keys, deterministic output)
# ---------------------------------------------------------------------------
# JavaScript JSON.stringify preserves insertion order, which may differ
# between runs or between PS1/bash variants writing the same file. Sorting
# keys before comparison ensures identical content produces identical JSON.
#
# SORT_KEYS_JS: minified sortKeys function for embedding in node -e blocks.
#   Usage: node -e "$SORT_KEYS_JS; ..."
#
# normalize_json: pipe-based wrapper for standalone use.
#   Usage: NORMALIZED=$(echo "$json_string" | normalize_json)
SORT_KEYS_JS='function sortKeys(o){if(o===null||typeof o!=="object")return o;if(Array.isArray(o))return o.map(sortKeys);var s={};Object.keys(o).sort().forEach(function(k){s[k]=sortKeys(o[k])});return s}'

normalize_json() {
    node -e "
        var input = require('fs').readFileSync('/dev/stdin', 'utf8');
        $SORT_KEYS_JS
        try {
            console.log(JSON.stringify(sortKeys(JSON.parse(input)), null, 2));
        } catch(e) {
            process.stderr.write('normalize_json: ' + e.message + '\n');
            process.exit(1);
        }
    "
}

# ---------------------------------------------------------------------------
# Summary panel renderer
# ---------------------------------------------------------------------------
# Reads AITOOLS_SUMMARY_FILE, displays colored panel, cleans up.
# Silent no-op if file unset, missing, or empty.
show_summary() {
    local sfile="${AITOOLS_SUMMARY_FILE:-}"
    [ -n "$sfile" ] || return 0
    [ -f "$sfile" ] || return 0
    [ -s "$sfile" ] || { rm -f "$sfile"; return 0; }

    # Dedup by tool name: highest severity wins (ERROR > WARN > OK).
    # ACTIONs (empty tool name) are never deduped. DETAIL lines collected separately.
    # Output is pre-sorted: OK+details, WARN+details, ERROR+details, ACTIONs.
    local deduped
    deduped=$(perl -F'\|' -lane '
        BEGIN { %rank = (OK => 1, WARN => 2, ERROR => 3); }
        $cat = $F[0]; $tool = $F[1]; $det = join("|", @F[2..$#F]);
        if ($cat eq "DETAIL") {
            push @{$details{$tool}}, $det; next;
        }
        if ($cat eq "ACTION" || $tool eq "") {
            push @actions, $_; next;
        }
        $r = $rank{$cat} // 0;
        if (!exists $best{$tool}) {
            push @order, $tool;
            $best{$tool} = $cat; $detail{$tool} = $det;
        } elsif ($r > ($rank{$best{$tool}} // 0)) {
            $best{$tool} = $cat; $detail{$tool} = $det;
        }
        END {
            my (@ok, @warn, @err);
            for my $t (@order) {
                my @g = ("$best{$t}|$t|$detail{$t}",
                         map { "DETAIL|$t|$_" } @{$details{$t} // []});
                if    ($best{$t} eq "OK")    { push @ok,   @g }
                elsif ($best{$t} eq "WARN")  { push @warn, @g }
                elsif ($best{$t} eq "ERROR") { push @err,  @g }
            }
            print for @ok, @warn, @err, @actions;
        }
    ' "$sfile")

    # Single-pass display: Perl output is pre-sorted by severity.
    # DETAIL lines inherit the color of their preceding parent entry.
    echo ""
    echo "────────────────────────────────────────────────────────"
    local last_color="" first_action=true
    while IFS='|' read -r cat tool detail; do
        case "$cat" in
            OK)
                last_color='\033[32m'
                printf '\033[32m  [ok]  %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            WARN)
                last_color='\033[33m'
                printf '\033[33m  [!]   %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            ERROR)
                last_color='\033[31m'
                printf '\033[31m  [ERR] %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            DETAIL)
                printf '%b                          %s\033[0m\n' "$last_color" "$detail"
                ;;
            ACTION)
                if [ "$first_action" = true ]; then
                    echo ""
                    printf '\033[1;35m  ACTION REQUIRED -- run before tools are ready:\033[0m\n'
                    first_action=false
                fi
                printf '\033[1;35m  >>  %s\033[0m\n' "$detail"
                ;;
        esac
    done <<< "$deduped"
    echo "────────────────────────────────────────────────────────"

    # Preserve summary for log compliance checks
    if [ "${AITOOLS_PRESERVE_SUMMARY:-}" = "1" ]; then
        # cp may fail if log dir was cleaned up; non-blocking (summary already displayed)
        if ! cp "$sfile" "$LOG_DIR/last-summary.txt" 2>/dev/null; then
            printf 'warning: could not preserve summary file\n' >&2
        fi
    fi
    # Cleanup summary file (already displayed; rm -f ignores nonexistent files)
    rm -f "$sfile"
}
logging_init "setup-gh-cli"

# --- OS guard ---
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        log_error "This script is for macOS/Linux. On Windows, use ${SCRIPT_NAME}.ps1 instead."
        exit 1 ;;
esac

OS_NAME="$(uname -s)"

# --- Install/update ---
case "$OS_NAME" in
    Darwin)
        # macOS: Homebrew is the preferred method
        if ! command -v brew &>/dev/null; then
            log_error "Homebrew not found. Install gh manually:"
            log_error "  1. Install Homebrew: https://brew.sh"
            log_error "  2. brew install gh"
            exit 1
        fi

        if command -v gh &>/dev/null; then
            log "gh CLI already installed ($(gh --version | head -1))"
            log "Checking for updates via Homebrew..."
            UPGRADE_OUTPUT=$(brew upgrade gh 2>&1) || true
            if printf '%s\n' "$UPGRADE_OUTPUT" | grep -qi 'already installed\|up.to.date\|No available upgrade'; then
                log_ok "gh CLI already up to date"
                write_summary OK "gh cli" "$(gh --version | head -1)"
            else
                printf '%s\n' "$UPGRADE_OUTPUT" | while IFS= read -r line; do log "$line"; done
                if printf '%s\n' "$UPGRADE_OUTPUT" | grep -qi 'error\|fatal'; then
                    log_error "brew upgrade gh failed (see log above)"
                    write_summary ERROR "gh cli" "brew upgrade failed"
                else
                    log_ok "gh CLI $(gh --version | head -1)"
                    write_summary OK "gh cli" "$(gh --version | head -1)"
                fi
            fi
        else
            log "Installing gh CLI via Homebrew..."
            if ! brew install gh 2>&1 | while IFS= read -r line; do log "$line"; done; then
                log_error "brew install gh failed"
                write_summary ERROR "gh cli" "brew install failed"
            fi

            if command -v gh &>/dev/null; then
                log_ok "gh CLI installed ($(gh --version | head -1))"
                log_ok "Install path: $(command -v gh)"
                write_summary OK "gh cli" "$(gh --version | head -1)"
            else
                log_error "brew install completed but 'gh' not found in PATH"
                write_summary ERROR "gh cli" "installed but not on PATH"
            fi
        fi
        ;;

    *)
        # Linux: apt is the preferred method
        if command -v apt-get &>/dev/null; then
            if command -v gh &>/dev/null; then
                log "gh CLI already installed ($(gh --version | head -1))"
                log "Updating via apt..."
                # apt handles idempotency; keyring was added on first install
                if ! { sudo apt-get update -qq && sudo apt-get install -y gh; } 2>&1 | while IFS= read -r line; do log "$line"; done; then
                    log_error "apt-get install gh failed"
                    write_summary ERROR "gh cli" "apt-get install failed"
                fi
                if command -v gh &>/dev/null; then
                    log_ok "gh CLI updated/confirmed ($(gh --version | head -1))"
                    write_summary OK "gh cli" "$(gh --version | head -1)"
                else
                    log_error "apt-get completed but 'gh' not found in PATH"
                    write_summary ERROR "gh cli" "installed but not on PATH"
                fi
            else
                log "Installing gh CLI via apt + GitHub keyring..."
                if ! { (type -p wget >/dev/null || sudo apt-get install -y wget) \
                    && sudo mkdir -p -m 755 /etc/apt/keyrings \
                    && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
                    && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
                    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
                    && sudo apt-get update -qq && sudo apt-get install -y gh; } 2>&1 | while IFS= read -r line; do log "$line"; done; then
                    log_error "apt keyring + install failed for gh CLI"
                    write_summary ERROR "gh cli" "apt install failed"
                fi

                if command -v gh &>/dev/null; then
                    log_ok "gh CLI installed ($(gh --version | head -1))"
                    write_summary OK "gh cli" "$(gh --version | head -1)"
                else
                    log_error "Failed to install gh CLI via apt"
                    write_summary ERROR "gh cli" "install failed"
                fi
            fi
        else
            log_error "No supported package manager found (apt). Install gh manually: https://cli.github.com"
            write_summary ERROR "gh cli" "no supported package manager"
        fi
        ;;
esac

# --- Exit ---
if [ "$ERRORS" -gt 0 ]; then
    log "FAILED with $ERRORS error(s)" "error"
    exit 1
elif [ "$WARNINGS" -gt 0 ]; then
    log "COMPLETED with $WARNINGS warning(s)" "warn"
    exit 0
else
    log "COMPLETED successfully" "ok"
    exit 0
fi
