# Generated by scripts/build-deploy.sh — do not edit directly.
param(
    [switch]$DryRun,
    [switch]$Force
)

# Env passthrough from parent (aitools CLI)
if ($env:AITOOLS_DRY_RUN -eq "1") { $DryRun = [switch]::Present }

# --- Shared library ---
# aitools-lib.ps1 -- shared helpers for all aitools PowerShell scripts
# Dot-sourced, not executed directly.
#
# Provides: ReadConfigKey, Initialize-Logging, Log/LogOk/LogError/LogWarn,
# Write-Summary, Show-Summary, Refresh-Path, Log-WingetOutput,
# Repair-UvToolEnv, Remove-OrphanedPythonDirs, Normalize-JsonForComparison.
#
# Usage:
#   . (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "aitools-lib.ps1")
#   Initialize-Logging "script-name"
#
# Entry points (aitools.ps1, aitools-install.ps1) override log functions after
# sourcing for specialized logging (file-only, JSONL, etc.).
#
# Platform detection uses PS 7+ built-in $IsMacOS/$IsWindows -- no custom variables.

# ---------------------------------------------------------------------------
# Config reader (PS 5.1 compatible)
# ---------------------------------------------------------------------------
function ReadConfigKey {
    param([string]$File, [string]$Key)
    if (-not (Test-Path $File)) { return $null }
    try {
        $json = Get-Content $File -Raw -ErrorAction Stop | ConvertFrom-Json
        $val = $json.$Key
        if ($val) { return $val }
    } catch {
        # File exists but is invalid JSON -- warn so callers know the null
        # return means "corrupt", not "missing key"
        Write-Host "      WARN: could not parse $File" -ForegroundColor Yellow
    }
    return $null
}

# ---------------------------------------------------------------------------
# Logging init
# ---------------------------------------------------------------------------
# Sets $script:scriptName, $script:logDir, $script:logFile; resets
# $script:errors, $script:warnings. Creates log directory.
# Usage: Initialize-Logging "setup-foo"
function Initialize-Logging {
    param([Parameter(Mandatory)][string]$Name)
    $script:scriptName = $Name
    if ($IsWindows -or (-not (Test-Path variable:IsMacOS))) {
        # Windows (PS 7+) or PS 5.1 (always Windows)
        $script:logDir = Join-Path $env:LOCALAPPDATA "aitools"
    } else {
        # macOS/Linux
        $script:logDir = Join-Path $HOME "Library/Logs/aitools"
    }
    $script:logFile = Join-Path $script:logDir "deploy.log"
    if (-not (Test-Path $script:logDir)) {
        New-Item -ItemType Directory -Path $script:logDir -Force | Out-Null
    }
    $script:errors = 0
    $script:warnings = 0
}

# ---------------------------------------------------------------------------
# Standard logging (console + log file, with [level] tag)
# ---------------------------------------------------------------------------
function Log($msg, $level = "info") {
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $line = "[$ts] [$scriptName] [$level] $msg"
    Add-Content -Path $logFile -Value $line
    switch ($level) {
        "error" { Write-Host $line -ForegroundColor Red }
        "warn"  { Write-Host $line -ForegroundColor Yellow }
        default { Write-Host $line }
    }
}
function LogOk($msg)    { Log $msg "ok" }
function LogError($msg) { Log $msg "error"; $script:errors++ }
function LogWarn($msg)  { Log $msg "warn"; $script:warnings++ }

# ---------------------------------------------------------------------------
# Summary writer (3-arg: category, tool, detail)
# ---------------------------------------------------------------------------
function Write-Summary($cat, $tool, $detail) {
    if ($env:AITOOLS_SUMMARY_FILE) {
        # Auto-promote OK to WARN when warnings have been logged
        if ($cat -eq "OK" -and $script:warnings -gt 0) {
            $cat = "WARN"
        }
        Add-Content -Path $env:AITOOLS_SUMMARY_FILE -Value "${cat}|${tool}|${detail}"
    }
}

# ---------------------------------------------------------------------------
# Backup a file before overwriting. Keeps at most $MaxBackups copies.
# ---------------------------------------------------------------------------
function Backup-File {
    param([string]$FilePath, [int]$MaxBackups = 20)
    if (-not (Test-Path $FilePath)) { return }
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHHmmssZ")
    $backupPath = "${FilePath}.bak.${ts}"
    Copy-Item -Path $FilePath -Destination $backupPath
    # Prune oldest beyond limit
    $backups = Get-ChildItem -Path "${FilePath}.bak.*" | Sort-Object LastWriteTime -Descending
    if ($backups.Count -gt $MaxBackups) {
        $backups | Select-Object -Skip $MaxBackups | Remove-Item -Force
    }
    Log "Backed up $FilePath"
}

# ---------------------------------------------------------------------------
# Backup a directory before modifying managed files. Keeps at most $MaxBackups copies.
# ---------------------------------------------------------------------------
function Backup-Dir {
    param([string]$DirPath, [int]$MaxBackups = 5)
    if (-not (Test-Path $DirPath)) { return }
    $mdFiles = Get-ChildItem -Path $DirPath -Filter "*.md" -File -ErrorAction SilentlyContinue
    if (-not $mdFiles -or $mdFiles.Count -eq 0) { return }
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHHmmssZ")
    $backupPath = "${DirPath}.bak.${ts}"
    try {
        Copy-Item -Path $DirPath -Destination $backupPath -Recurse -ErrorAction Stop
    } catch {
        LogWarn "Could not back up $DirPath -- proceeding without backup: $_"
        return
    }
    $parentDir = Split-Path $DirPath -Parent
    $dirName = Split-Path $DirPath -Leaf
    $backups = Get-ChildItem -Path $parentDir -Directory -Filter "${dirName}.bak.*" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending
    if ($backups -and $backups.Count -gt $MaxBackups) {
        $backups | Select-Object -Skip $MaxBackups | ForEach-Object {
            Remove-Item $_.FullName -Recurse -Force
            Log "Pruned old backup: $($_.FullName)"
        }
    }
    Log "Backed up $DirPath ($($mdFiles.Count) managed files)"
}

# ---------------------------------------------------------------------------
# Deploy state tracking: manifest + shadow copies for auto-deploy detection.
# Tracks what was last deployed to each managed file. When the local file
# matches the last-deployed hash, content changes are auto-deployed without
# prompting (user didn't edit). Shadows provide the common ancestor for diff3.
# ---------------------------------------------------------------------------
$script:DeployManifest = $null
$script:DeployStateDir = if ($IsWindows) { "$env:USERPROFILE\.aitools\deploy-state" } else { "$HOME/.aitools/deploy-state" }

function Get-ContentHash {
    param([string]$Content)
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Content)
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $hash = $sha.ComputeHash($bytes)
        return [BitConverter]::ToString($hash) -replace '-'
    } finally {
        $sha.Dispose()
    }
}

function Initialize-DeployState {
    $manifestPath = Join-Path $script:DeployStateDir "manifest.json"
    if (Test-Path $manifestPath) {
        try {
            $raw = Get-Content $manifestPath -Raw -ErrorAction Stop
            $script:DeployManifest = ($raw | ConvertFrom-Json)
            if (-not $script:DeployManifest.files) {
                $script:DeployManifest | Add-Member -NotePropertyName files -NotePropertyValue @{} -Force
            }
        } catch {
            LogWarn "Corrupt deploy manifest, resetting: $_"
            $script:DeployManifest = [PSCustomObject]@{ version = 1; files = @{} }
        }
    } else {
        $script:DeployManifest = [PSCustomObject]@{ version = 1; files = @{} }
    }
}

function Get-DeployStateKey {
    param([string]$FilePath)
    $resolved = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($FilePath)
    $homeDir = if ($IsWindows) { $env:USERPROFILE } else { $env:HOME }
    if ($resolved.StartsWith($homeDir, [System.StringComparison]::OrdinalIgnoreCase)) {
        return $resolved.Substring($homeDir.Length).Replace('\', '/').TrimStart('/')
    }
    return $resolved.Replace('\', '/')
}

function Get-DeployState {
    param([string]$FilePath)
    if (-not $script:DeployManifest) { Initialize-DeployState }
    $key = Get-DeployStateKey $FilePath
    $files = $script:DeployManifest.files
    if ($files -is [hashtable]) {
        if ($files.ContainsKey($key)) { return $files[$key] }
    } else {
        $val = $files.$key
        if ($val) { return $val }
    }
    return $null
}

function Update-DeployState {
    param([string]$FilePath, [string]$Content)
    if (-not $script:DeployManifest) { Initialize-DeployState }
    $key = Get-DeployStateKey $FilePath
    $hash = Get-ContentHash $Content
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

    $entry = [PSCustomObject]@{ hash = $hash; deployedAt = $ts }
    $files = $script:DeployManifest.files
    if ($files -is [hashtable]) {
        $files[$key] = $entry
    } else {
        $ht = @{}
        $files.PSObject.Properties | ForEach-Object { $ht[$_.Name] = $_.Value }
        $ht[$key] = $entry
        $script:DeployManifest | Add-Member -NotePropertyName files -NotePropertyValue $ht -Force
    }

    $manifestDir = $script:DeployStateDir
    if (-not (Test-Path $manifestDir)) {
        New-Item -ItemType Directory -Path $manifestDir -Force | Out-Null
    }
    $manifestPath = Join-Path $manifestDir "manifest.json"
    $resolved = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($manifestPath)
    $json = $script:DeployManifest | ConvertTo-Json -Depth 5
    [System.IO.File]::WriteAllText($resolved, $json, [System.Text.UTF8Encoding]::new($false))

    $shadowPath = Join-Path $manifestDir "shadows" $key
    $shadowDir = Split-Path $shadowPath -Parent
    if (-not (Test-Path $shadowDir)) {
        New-Item -ItemType Directory -Path $shadowDir -Force | Out-Null
    }
    $resolvedShadow = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($shadowPath)
    [System.IO.File]::WriteAllText($resolvedShadow, $Content, [System.Text.UTF8Encoding]::new($false))
}

function Get-DeployShadow {
    param([string]$FilePath)
    $key = Get-DeployStateKey $FilePath
    $shadowPath = Join-Path $script:DeployStateDir "shadows" $key
    if (Test-Path $shadowPath) {
        try {
            return Get-Content $shadowPath -Raw -ErrorAction Stop
        } catch {
            return $null
        }
    }
    return $null
}

# ---------------------------------------------------------------------------
# Non-agentic merge via diff3 (3-way merge using shadow as common ancestor).
# Returns merged content string on clean merge, $null on conflicts/error.
# ---------------------------------------------------------------------------
function Find-Diff3 {
    # Get-Command exempt: command-existence check with explicit fallback
    $gitCmd = Get-Command git -ErrorAction SilentlyContinue
    if ($gitCmd) {
        $gitDir = Split-Path (Split-Path $gitCmd.Source)
        $diff3Path = Join-Path $gitDir "usr\bin\diff3.exe"
        if (Test-Path $diff3Path) { return $diff3Path }
    }
    return $null
}

function Try-Diff3Merge {
    param(
        [string]$LocalContent,
        [string]$AncestorContent,
        [string]$SourceContent
    )
    $diff3 = Find-Diff3
    if (-not $diff3) { return $null }

    $tmpLocal = [System.IO.Path]::GetTempFileName()
    $tmpAncestor = [System.IO.Path]::GetTempFileName()
    $tmpSource = [System.IO.Path]::GetTempFileName()
    try {
        [IO.File]::WriteAllText($tmpLocal, $LocalContent)
        [IO.File]::WriteAllText($tmpAncestor, $AncestorContent)
        [IO.File]::WriteAllText($tmpSource, $SourceContent)

        $merged = & $diff3 -m $tmpLocal $tmpAncestor $tmpSource 2>&1
        if ($LASTEXITCODE -eq 0) {
            return ($merged -join "`n")
        }
        return $null
    } catch {
        return $null
    } finally {
        Remove-Item $tmpLocal, $tmpAncestor, $tmpSource -ErrorAction SilentlyContinue
    }
}

# ---------------------------------------------------------------------------
# Agentic merge via claude CLI. Returns "merge" (sets $script:MergedContent)
# or falls back to "overwrite"/"skip".
# ---------------------------------------------------------------------------
function Invoke-AiMerge {
    param(
        [string]$FilePath,
        [string]$SourceContent,
        [string]$LocalContent
    )

    # Get-Command exempt: command-existence check with explicit fallback
    if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
        [Console]::WriteLine("  >> claude CLI not found -- merge unavailable, falling back to overwrite")
        LogWarn "AI merge unavailable (claude CLI not found)"
        return "overwrite"
    }

    [Console]::WriteLine("  >> merging via AI...")

    $tmpSource = [System.IO.Path]::GetTempFileName()
    $tmpLocal = [System.IO.Path]::GetTempFileName()
    $tmpPrompt = [System.IO.Path]::GetTempFileName()
    try {
        [IO.File]::WriteAllText($tmpSource, $SourceContent)
        [IO.File]::WriteAllText($tmpLocal, $LocalContent)

        $promptText = @"
Merge these two versions of a configuration file.

SOURCE ($tmpSource) is the new template being deployed.
LOCAL ($tmpLocal) is the user's current file with their customizations.

Rules:
- Preserve all user customizations from LOCAL that are intentional
- Include all new content from SOURCE (new sections, updated tables, structural changes)
- When both sides modify the same line, prefer LOCAL unless SOURCE adds new information
- Output ONLY the merged file content, no commentary, no markdown fences
"@
        [IO.File]::WriteAllText($tmpPrompt, $promptText)

        $merged = Get-Content $tmpPrompt -Raw | claude -p 2>&1
        if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($merged)) {
            [Console]::WriteLine("  >> AI merge failed -- choose another option")
            LogWarn "AI merge failed (exit $LASTEXITCODE)"
            [Console]::Write("  fallback [o]verwrite / [s]kip: ")
            $fb = [Console]::ReadLine()
            if ($fb.ToLower() -eq "s") { return "skip" }
            return "overwrite"
        }
    } catch {
        [Console]::WriteLine("  >> AI merge error: $_ -- choose another option")
        LogWarn "AI merge error: $_"
        [Console]::Write("  fallback [o]verwrite / [s]kip: ")
        $fb = [Console]::ReadLine()
        if ($fb.ToLower() -eq "s") { return "skip" }
        return "overwrite"
    } finally {
        Remove-Item $tmpSource, $tmpLocal, $tmpPrompt -ErrorAction SilentlyContinue
    }

    # Show merge preview
    [Console]::WriteLine("")
    [Console]::WriteLine("  --- merged result preview (first 30 lines) ---")
    $mergedLines = $merged -split "`n"
    $previewCount = [Math]::Min(30, $mergedLines.Count)
    for ($i = 0; $i -lt $previewCount; $i++) {
        [Console]::WriteLine("  | $($mergedLines[$i])")
    }
    if ($mergedLines.Count -gt 30) {
        [Console]::WriteLine("  | ... ($($mergedLines.Count - 30) more lines)")
    }
    [Console]::WriteLine("")
    [Console]::Write("  accept merge? [y]es / [n]o (falls back to overwrite): ")
    $accept = [Console]::ReadLine()
    if ($accept.ToLower() -eq "y") {
        $script:MergedContent = $merged
        [Console]::WriteLine("  >> merged: AI-merged content deployed")
        return "merge"
    }
    [Console]::WriteLine("  >> merge rejected, falling back to overwrite")
    return "overwrite"
}

# ---------------------------------------------------------------------------
# Prompt user before overwriting a managed file with different content.
# Shows diff, attempts diff3 auto-merge, offers interactive options.
#
# Returns: "overwrite", "adopt", "merge", or "skip"
# Exits with code 2 on abort.
# Non-interactive / -Force: returns "overwrite".
# When returning "merge", sets $script:MergedContent with the merged result.
# ---------------------------------------------------------------------------
$script:MergedContent = $null
function Prompt-DiffReview {
    param(
        [string]$FilePath,
        [string]$NewContent,
        [string]$CurrentContent = "",
        [string]$AncestorContent = "",
        [string]$AdoptLabel = ""
    )

    $script:MergedContent = $null

    # -Force or AITOOLS_FORCE: auto-overwrite
    if ($env:AITOOLS_FORCE -eq "1" -or $Force) {
        LogWarn "Diff in $FilePath -- overwriting (-Force)"
        return "overwrite"
    }

    # Non-interactive: auto-overwrite
    if (-not [Environment]::UserInteractive) {
        LogWarn "Diff in $FilePath -- overwriting (non-interactive)"
        return "overwrite"
    }

    # Read current file if not provided
    if (-not $CurrentContent) {
        try {
            $CurrentContent = Get-Content $FilePath -Raw -ErrorAction Stop
        } catch {
            LogWarn "Cannot read $FilePath for diff: $_"
            return "overwrite"
        }
    }

    # Context header
    [Console]::WriteLine("")
    [Console]::WriteLine("[REVIEW] $FilePath differs from source.")
    [Console]::WriteLine("  source = template (would deploy)")
    [Console]::WriteLine("  local  = current file on disk")
    [Console]::WriteLine("")

    # Generate line-level diff
    $srcLines = @($NewContent -split "`n")
    $curLines = @($CurrentContent -split "`n")
    $diffs = Compare-Object $srcLines $curLines
    $diffCount = 0
    if ($diffs) { $diffCount = @($diffs).Count }

    if ($diffCount -eq 0) {
        [Console]::WriteLine("  (whitespace-only differences)")
    } elseif ($diffCount -le 40) {
        foreach ($d in $diffs) {
            $indicator = if ($d.SideIndicator -eq "=>") { "+ local  " } else { "- source " }
            [Console]::WriteLine("  $indicator$($d.InputObject)")
        }
    } else {
        $shown = 0
        foreach ($d in $diffs) {
            if ($shown -ge 30) { break }
            $indicator = if ($d.SideIndicator -eq "=>") { "+ local  " } else { "- source " }
            [Console]::WriteLine("  $indicator$($d.InputObject)")
            $shown++
        }
        [Console]::WriteLine("  ... ($($diffCount - 30) more lines -- see deploy log)")
    }

    # Attempt diff3 auto-merge if ancestor available
    if ($AncestorContent) {
        [Console]::WriteLine("")
        [Console]::WriteLine("  Attempting automatic merge...")
        $autoMerged = Try-Diff3Merge -LocalContent $CurrentContent `
            -AncestorContent $AncestorContent -SourceContent $NewContent
        if ($autoMerged) {
            [Console]::WriteLine("  Clean merge -- no conflicts.")
            [Console]::WriteLine("")
            $mergedLines = $autoMerged -split "`n"
            $previewCount = [Math]::Min(30, $mergedLines.Count)
            [Console]::WriteLine("  --- merged result preview (first $previewCount lines) ---")
            for ($i = 0; $i -lt $previewCount; $i++) {
                [Console]::WriteLine("  | $($mergedLines[$i])")
            }
            if ($mergedLines.Count -gt 30) {
                [Console]::WriteLine("  | ... ($($mergedLines.Count - 30) more lines)")
            }
            [Console]::WriteLine("")
            if ($AdoptLabel) {
                [Console]::WriteLine("  [y]es       : accept merge result")
                [Console]::WriteLine("  [o]verwrite : source wins -> deploy to local (backup kept)")
                [Console]::WriteLine("  [a]dopt     : local wins -> copy back to $AdoptLabel")
                [Console]::WriteLine("  [s]kip      : keep local as-is (no changes)")
                [Console]::WriteLine("  [x]abort    : stop deployment")
                [Console]::Write("  choice [y/o/a/s/x]: ")
            } else {
                [Console]::WriteLine("  [y]es       : accept merge result")
                [Console]::WriteLine("  [o]verwrite : source wins -> deploy to local (backup kept)")
                [Console]::WriteLine("  [s]kip      : keep local as-is (no changes)")
                [Console]::WriteLine("  [x]abort    : stop deployment")
                [Console]::Write("  choice [y/o/s/x]: ")
            }
            $choice = [Console]::ReadLine()
            switch ($choice.ToLower()) {
                "y" {
                    $script:MergedContent = $autoMerged
                    [Console]::WriteLine("  >> merged: diff3 merge deployed")
                    return "merge"
                }
                "a" {
                    if ($AdoptLabel) {
                        [Console]::WriteLine("  >> adopted: local version copied back to $AdoptLabel")
                        return "adopt"
                    }
                    [Console]::WriteLine("  >> overwritten: source deployed to local (backup kept)")
                    return "overwrite"
                }
                "s" {
                    [Console]::WriteLine("  >> skipped: local file unchanged")
                    return "skip"
                }
                "x" {
                    LogError "Aborted by user"
                    exit 2
                }
                default {
                    [Console]::WriteLine("  >> overwritten: source deployed to local (backup kept)")
                    return "overwrite"
                }
            }
        } else {
            [Console]::WriteLine("  Merge has conflicts -- manual choice required.")
        }
    }

    # Options (no auto-merge available or merge had conflicts)
    [Console]::WriteLine("")
    if ($AdoptLabel) {
        [Console]::WriteLine("  [o]verwrite : source wins -> deploy to local (backup kept)")
        [Console]::WriteLine("  [a]dopt     : local wins -> copy back to $AdoptLabel")
        [Console]::WriteLine("  [m]erge     : AI-assisted merge of source + local")
        [Console]::WriteLine("  [s]kip      : keep local as-is (no changes)")
        [Console]::WriteLine("  [x]abort    : stop deployment")
        [Console]::Write("  choice [o/a/m/s/x]: ")
    } else {
        [Console]::WriteLine("  [o]verwrite : source wins -> deploy to local (backup kept)")
        [Console]::WriteLine("  [m]erge     : AI-assisted merge of source + local")
        [Console]::WriteLine("  [s]kip      : keep local as-is (no changes)")
        [Console]::WriteLine("  [x]abort    : stop deployment")
        [Console]::Write("  choice [o/m/s/x]: ")
    }

    $choice = [Console]::ReadLine()
    switch ($choice.ToLower()) {
        "a" {
            if ($AdoptLabel) {
                [Console]::WriteLine("  >> adopted: local version copied back to $AdoptLabel")
                return "adopt"
            }
            [Console]::WriteLine("  >> overwritten: source deployed to local (backup kept)")
            return "overwrite"
        }
        "m" {
            return (Invoke-AiMerge -FilePath $FilePath -SourceContent $NewContent -LocalContent $CurrentContent)
        }
        "s" {
            [Console]::WriteLine("  >> skipped: local file unchanged")
            return "skip"
        }
        "x" {
            LogError "Aborted by user"
            exit 2
        }
        default {
            [Console]::WriteLine("  >> overwritten: source deployed to local (backup kept)")
            return "overwrite"
        }
    }
}

# ---------------------------------------------------------------------------
# Deploy a managed file with diff review and deploy state tracking.
# Uses manifest to auto-deploy when user hasn't edited the local file.
# Falls back to interactive review with merge options when both sides differ.
#
# Returns: "created", "updated", "unchanged", "adopted", or "skipped"
# Exits with code 2 on abort.
# On "adopted"/"skipped": does NOT write the file.
# On "created"/"updated": writes content to dest + updates deploy state.
# ---------------------------------------------------------------------------
function Deploy-ManagedFile {
    param(
        [string]$Content,
        [string]$DestPath,
        [string]$ToolName,
        [string]$ItemName,
        [string]$AdoptLabel = ""
    )

    # Dry run: report what would happen without writing
    if ($DryRun) {
        if (Test-Path $DestPath) {
            try {
                $existing = Get-Content $DestPath -Raw -ErrorAction Stop
            } catch {
                $existing = ""
            }
            if ($existing -eq $Content) {
                Log "[DRY RUN] Unchanged: $ItemName"
            } else {
                Log "[DRY RUN] Would update: $ItemName -> $DestPath"
            }
        } else {
            Log "[DRY RUN] Would create: $ItemName -> $DestPath"
        }
        return "unchanged"
    }

    $destDir = Split-Path -Parent $DestPath
    if (-not (Test-Path $destDir)) {
        New-Item -ItemType Directory -Path $destDir -Force | Out-Null
    }

    if (Test-Path $DestPath) {
        try {
            $existing = Get-Content $DestPath -Raw -ErrorAction Stop
        } catch {
            LogWarn "Cannot read $DestPath for comparison: $_"
            $existing = ""
        }
        if ($existing -eq $Content) {
            # Content identical — update deploy state (bootstraps manifest)
            Update-DeployState -FilePath $DestPath -Content $Content
            return "unchanged"
        }

        # Content differs — check deploy state for auto-deploy eligibility
        $state = Get-DeployState -FilePath $DestPath
        if ($state -and $state.hash) {
            $existingHash = Get-ContentHash $existing
            if ($existingHash -eq $state.hash) {
                # User didn't edit since last deploy → auto-deploy silently
                Backup-File -FilePath $DestPath
                $resolved = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($DestPath)
                [System.IO.File]::WriteAllText($resolved, $Content, [System.Text.UTF8Encoding]::new($false))
                Update-DeployState -FilePath $DestPath -Content $Content
                Log "Auto-deployed: $ItemName (no local edits detected)"
                return "updated"
            }
        }

        # User edited AND source changed — backup + interactive review
        Backup-File -FilePath $DestPath
        $ancestorContent = Get-DeployShadow -FilePath $DestPath
        $result = Prompt-DiffReview -FilePath $DestPath -NewContent $Content `
            -CurrentContent $existing -AncestorContent $ancestorContent `
            -AdoptLabel $AdoptLabel
        switch ($result) {
            "adopt" { return "adopted" }
            "skip" {
                LogWarn "Skipped: $ItemName"
                return "skipped"
            }
            "merge" {
                $Content = $script:MergedContent
            }
        }
        # overwrite or merge: write content to dest
        $resolved = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($DestPath)
        [System.IO.File]::WriteAllText($resolved, $Content, [System.Text.UTF8Encoding]::new($false))
        Update-DeployState -FilePath $DestPath -Content $Content
        LogOk "Updated: $ItemName -> $DestPath"
        return "updated"
    } else {
        # New file — create
        $resolved = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($DestPath)
        [System.IO.File]::WriteAllText($resolved, $Content, [System.Text.UTF8Encoding]::new($false))
        Update-DeployState -FilePath $DestPath -Content $Content
        LogOk "Created: $ItemName -> $DestPath"
        return "created"
    }
}

# ---------------------------------------------------------------------------
# Deploy tracker: centralizes outcome counting and summary writing for
# loops that deploy multiple managed files (rules, skills, hooks).
# ---------------------------------------------------------------------------

$script:dtAdded = 0; $script:dtUpdated = 0; $script:dtUnchanged = 0
$script:dtAdopted = 0; $script:dtSkipped = 0; $script:dtPreserved = 0
$script:deployTrackerText = ""

function Initialize-DeployTracker {
    $script:dtAdded = 0; $script:dtUpdated = 0; $script:dtUnchanged = 0
    $script:dtAdopted = 0; $script:dtSkipped = 0; $script:dtPreserved = 0
    $script:deployTrackerText = ""
}

# Record a single file outcome. Increments counter and writes DETAIL summary.
function Record-DeployOutcome {
    param([string]$Outcome, [string]$ToolName, [string]$ItemName)
    switch ($Outcome) {
        { $_ -eq "added" -or $_ -eq "created" } { $script:dtAdded++;     Write-Summary "DETAIL" $ToolName "added: $ItemName" }
        "updated"   { $script:dtUpdated++;   Write-Summary "DETAIL" $ToolName "updated: $ItemName" }
        "adopted"   { $script:dtAdopted++;   Write-Summary "DETAIL" $ToolName "adopted: $ItemName" }
        "skipped"   { $script:dtSkipped++;   Write-Summary "DETAIL" $ToolName "skipped: $ItemName" }
        "unchanged" { $script:dtUnchanged++ }
        "preserved" { $script:dtPreserved++ }
    }
}

# Write aggregate summary for a deploy loop. Uses non-zero counts.
function Write-DeployTrackerSummary {
    param([string]$ToolName)
    $parts = @()
    if ($script:dtAdded -gt 0)     { $parts += "$($script:dtAdded) added" }
    if ($script:dtUpdated -gt 0)   { $parts += "$($script:dtUpdated) updated" }
    if ($script:dtAdopted -gt 0)   { $parts += "$($script:dtAdopted) adopted" }
    if ($script:dtUnchanged -gt 0) { $parts += "$($script:dtUnchanged) unchanged" }
    $text = if ($parts.Count -gt 0) { $parts -join ", " } else { "unchanged" }
    $script:deployTrackerText = $text

    if ($script:dtSkipped -gt 0) {
        Write-Summary "WARN" $ToolName "$($script:dtSkipped) skipped (user review)"
    } else {
        Write-Summary "OK" $ToolName $text
    }
}

# ---------------------------------------------------------------------------
# PATH helpers
# ---------------------------------------------------------------------------

# Refresh-Path: Reload $env:Path from Machine + User registry values.
# Call after winget install/upgrade to pick up PATH changes in same session.
function Refresh-Path {
    $machinePath = [Environment]::GetEnvironmentVariable("Path", "Machine")
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    $env:Path = "$machinePath;$userPath"
}

# Log-WingetOutput: Filter and log captured winget command output.
# Strips spinner characters (- \ | /), download progress bars (KB/MB/GB),
# and empty lines. Remaining lines are logged at info level.
function Log-WingetOutput([string]$Output) {
    $Output.Trim().Split("`n") | ForEach-Object {
        $l = $_.TrimEnd()
        if ($l.Trim() -and $l.Trim() -notmatch '^[-\\|/]+$' -and $l -notmatch '\d+(\.\d+)?\s*(KB|MB|GB)\s*/\s*\d+') {
            Log $l
        }
    }
}

# ---------------------------------------------------------------------------
# Repair broken uv tool environment (cross-platform)
# ---------------------------------------------------------------------------
# When `uv tool upgrade <tool>` fails with "missing a valid environment",
# find a working Python via `uv python find` (fallback: system python/python3)
# and reinstall with --force --python <path>.
# Returns $true if repaired, $false if not applicable or failed.
function Repair-UvToolEnv {
    param(
        [Parameter(Mandatory)][string]$ToolName,
        [string]$UpgradeOutput = ""
    )

    if ($UpgradeOutput -notmatch 'missing a valid environment') { return $false }

    LogWarn "$ToolName uv environment is broken (Python removed?) -- repairing..."

    # Find a working Python -- uv's own Pythons first, then system
    # Get-Command exempt: command-existence check with fallback chain
    $workingPython = $null
    $uvPython = & uv python find 2>$null
    if ($LASTEXITCODE -eq 0 -and $uvPython -and (Test-Path $uvPython)) {
        $workingPython = $uvPython
    } elseif (Get-Command python -ErrorAction SilentlyContinue) {
        $workingPython = (Get-Command python).Source
    } elseif (Get-Command python3 -ErrorAction SilentlyContinue) {
        $workingPython = (Get-Command python3).Source
    }

    if (-not $workingPython) {
        LogError "Cannot repair $ToolName -- no working Python found"
        return $false
    }

    Log "Repairing with: uv tool install --force --python $workingPython $ToolName"
    $repairOutput = & uv tool install --force --python $workingPython $ToolName 2>&1 | Out-String
    $repairOutput.Trim().Split("`n") | ForEach-Object {
        $l = $_.TrimEnd(); if ($l.Trim()) { Log $l }
    }

    if ($LASTEXITCODE -ne 0) {
        LogError "$ToolName environment repair failed (exit $LASTEXITCODE)"
        return $false
    }

    LogOk "Repaired $ToolName uv environment"
    return $true
}

# ---------------------------------------------------------------------------
# Remove orphaned Python directories (Windows only)
# ---------------------------------------------------------------------------
# Scans %LOCALAPPDATA%\Programs\Python\ for PythonXYZ\ directories where
# python.exe is gone (uninstalled). Removes the orphaned directory tree and
# cleans stale entries from User PATH.
# Returns count of directories removed (0 = nothing to clean).
function Remove-OrphanedPythonDirs {
    if (-not $IsWindows) { return 0 }

    $pythonBase = Join-Path $env:LOCALAPPDATA "Programs\Python"
    if (-not (Test-Path $pythonBase)) { return 0 }

    $removedCount = 0
    $candidates = Get-ChildItem -Path $pythonBase -Directory -ErrorAction SilentlyContinue
    if (-not $candidates) { return 0 }

    foreach ($dir in $candidates) {
        # Skip the Launcher directory (belongs to pymanager)
        if ($dir.Name -eq "Launcher") { continue }

        # Orphaned = python.exe is gone
        $pythonExe = Join-Path $dir.FullName "python.exe"
        if (Test-Path $pythonExe) { continue }

        # Log stale executables for visibility
        $scriptsDir = Join-Path $dir.FullName "Scripts"
        if (Test-Path $scriptsDir) {
            $staleExes = Get-ChildItem $scriptsDir -Filter "*.exe" -File -ErrorAction SilentlyContinue
            if ($staleExes) {
                $names = ($staleExes | Select-Object -First 5 | ForEach-Object { $_.Name }) -join ", "
                LogWarn "Orphaned Python dir with stale executables: $($dir.Name) ($names)"
            }
        }

        try {
            Remove-Item -Path $dir.FullName -Recurse -Force -ErrorAction Stop
            LogOk "Removed orphaned directory: $($dir.FullName)"
            $removedCount++
        } catch {
            LogError "Failed to remove $($dir.FullName): $_"
        }
    }

    # Clean stale User PATH entries pointing to removed Python dirs
    if ($removedCount -gt 0) {
        $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
        if ($userPath) {
            $entries = $userPath -split ";"
            $cleanEntries = @()
            $removedEntries = @()

            foreach ($entry in $entries) {
                $trimmed = $entry.TrimEnd("\", "/")
                if ($trimmed -match '\\Programs\\Python\\Python\d+' -and -not (Test-Path $trimmed)) {
                    $removedEntries += $trimmed
                } else {
                    $cleanEntries += $entry
                }
            }

            if ($removedEntries.Count -gt 0) {
                $newPath = $cleanEntries -join ";"
                [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
                foreach ($re in $removedEntries) {
                    LogOk "Removed stale User PATH entry: $re"
                }
            }
        }

        Refresh-Path
    }

    return $removedCount
}

# ---------------------------------------------------------------------------
# PS 5.1 compatibility: ConvertFrom-Json -> Hashtable (recursive, array-aware)
# ---------------------------------------------------------------------------
function ConvertPSObjectToHashtable($obj) {
    if ($null -eq $obj) { return @{} }
    if ($obj -is [array]) {
        return ,@($obj | ForEach-Object { ConvertPSObjectToHashtable $_ })
    }
    if ($obj -isnot [System.Management.Automation.PSCustomObject]) { return $obj }
    $ht = @{}
    foreach ($prop in $obj.PSObject.Properties) {
        $ht[$prop.Name] = ConvertPSObjectToHashtable $prop.Value
    }
    return $ht
}

# ---------------------------------------------------------------------------
# Emit DETAIL summary entries from a list of change descriptions.
# Usage: Emit-MergeDetails -Changes @("key: old -> new") -ToolName "tool_name"
# ---------------------------------------------------------------------------
function Emit-MergeDetails {
    param(
        [string[]]$Changes,
        [string]$ToolName
    )
    foreach ($change in $Changes) {
        Log "  $change"
        Write-Summary "DETAIL" $ToolName "$change"
    }
}

# ---------------------------------------------------------------------------
# JSON normalization for comparison (sorted keys, deterministic output)
# ---------------------------------------------------------------------------
# PowerShell hashtable key ordering is non-deterministic. ConvertTo-Json
# produces different strings for semantically identical objects, causing
# false-positive change detection. These functions recursively sort keys
# before serializing, ensuring identical content produces identical JSON.
#
# Usage:
#   $norm = Normalize-JsonForComparison $hashtable
#   $norm = Normalize-JsonForComparison $hashtable -Depth 5 -Compress
function ConvertTo-CanonicalObject($obj) {
    if ($null -eq $obj) { return $null }
    if ($obj -is [array]) {
        return ,@($obj | ForEach-Object { ConvertTo-CanonicalObject $_ })
    }
    if ($obj -is [hashtable]) {
        $ordered = [ordered]@{}
        foreach ($key in ($obj.Keys | Sort-Object)) {
            $ordered[$key] = ConvertTo-CanonicalObject $obj[$key]
        }
        return [PSCustomObject]$ordered
    }
    if ($obj -is [System.Management.Automation.PSCustomObject]) {
        $ordered = [ordered]@{}
        foreach ($prop in ($obj.PSObject.Properties | Sort-Object Name)) {
            $ordered[$prop.Name] = ConvertTo-CanonicalObject $prop.Value
        }
        return [PSCustomObject]$ordered
    }
    return $obj
}

function Normalize-JsonForComparison {
    param($Value, [int]$Depth = 10, [switch]$Compress)
    if ($null -eq $Value) { return "null" }
    $canonical = ConvertTo-CanonicalObject $Value
    $canonical | ConvertTo-Json -Depth $Depth -Compress:$Compress
}

# ---------------------------------------------------------------------------
# Go install provenance detection (Windows)
# Returns: "winget", "chocolatey", "scoop", "msi", "none", or "unknown"
# ---------------------------------------------------------------------------
function Get-GoProvenance {
    # Get-Command exempt: command-existence check with explicit fallback
    $goCmd = Get-Command go -ErrorAction SilentlyContinue
    if (-not $goCmd) { return "none" }
    $goSource = $goCmd.Source
    if ($goSource -like '*\Program Files\Go\*') {
        $wingetCheck = winget list --id GoLang.Go --accept-source-agreements 2>&1 | Out-String
        if ($wingetCheck -match 'GoLang\.Go') { return "winget" }
        return "msi"
    }
    if ($goSource -like '*\chocolatey\*') { return "chocolatey" }
    if ($goSource -like '*\scoop\*') { return "scoop" }
    return "unknown"
}

# ---------------------------------------------------------------------------
# Ensure GOPATH\bin is on persistent User PATH (Windows)
# Returns $true if already present, $false if added
# ---------------------------------------------------------------------------
function Ensure-GopathBinOnPath {
    $gopath = $env:GOPATH
    if (-not $gopath) { $gopath = Join-Path $env:USERPROFILE "go" }
    $gopathBin = Join-Path $gopath "bin"
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($userPath -like "*$gopathBin*") { return $true }
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$gopathBin", "User")
    Refresh-Path
    return $false
}

# ---------------------------------------------------------------------------
# Summary panel renderer
# ---------------------------------------------------------------------------
# Reads AITOOLS_SUMMARY_FILE, displays colored panel, cleans up.
# Silent no-op if file unset, missing, or empty.
function Show-Summary {
    $sfile = $env:AITOOLS_SUMMARY_FILE
    if (-not $sfile -or -not (Test-Path $sfile)) { return }
    # Read summary file; -ErrorAction SilentlyContinue checked on next line
    $lines = Get-Content $sfile -ErrorAction SilentlyContinue
    if (-not $lines) {
        # Summary file empty or unreadable; clean up and return
        try { Remove-Item $sfile -Force -ErrorAction Stop }
        catch { Write-Host "  note: could not remove empty summary file" -ForegroundColor Gray }
        return
    }

    # Dedup by tool name: highest severity wins (ERROR > WARN > OK).
    # ACTIONs (empty tool name) are never deduped. DETAIL lines collected separately.
    $rank = @{ 'OK' = 1; 'WARN' = 2; 'ERROR' = 3 }
    $order = [System.Collections.Generic.List[string]]::new()
    $best = @{}
    $bestDetail = @{}
    $detailMap = @{}
    $actions = [System.Collections.Generic.List[string]]::new()

    foreach ($line in $lines) {
        $parts = $line -split '\|', 3
        $cat = $parts[0]
        $tool = $parts[1]
        $det = $parts[2]
        if ($cat -eq 'DETAIL') {
            if (-not $detailMap.ContainsKey($tool)) { $detailMap[$tool] = [System.Collections.Generic.List[string]]::new() }
            $detailMap[$tool].Add($det)
            continue
        }
        if ($cat -eq 'ACTION' -or $tool -eq '') {
            $actions.Add($line)
            continue
        }
        $r = if ($rank.ContainsKey($cat)) { $rank[$cat] } else { 0 }
        if (-not $best.ContainsKey($tool)) {
            $order.Add($tool)
            $best[$tool] = $cat
            $bestDetail[$tool] = $det
        } elseif ($r -gt $rank[$best[$tool]]) {
            $best[$tool] = $cat
            $bestDetail[$tool] = $det
        }
    }

    # Build deduped lines, pre-sorted: OK+details, WARN+details, ERROR+details, ACTIONs
    $deduped = [System.Collections.Generic.List[string]]::new()
    foreach ($sev in @('OK', 'WARN', 'ERROR')) {
        foreach ($t in $order) {
            if ($best[$t] -ne $sev) { continue }
            $deduped.Add("$sev|$t|$($bestDetail[$t])")
            if ($detailMap.ContainsKey($t)) {
                foreach ($d in $detailMap[$t]) { $deduped.Add("DETAIL|$t|$d") }
            }
        }
    }
    foreach ($a in $actions) { $deduped.Add($a) }

    # Color and tag maps for severity categories
    $colorMap = @{ 'OK' = 'Green'; 'WARN' = 'Yellow'; 'ERROR' = 'Red' }
    $tagMap = @{ 'OK' = '  [ok]  '; 'WARN' = '  [!]   '; 'ERROR' = '  [ERR] ' }

    # Single-pass display: deduped list is pre-sorted by severity.
    # DETAIL lines inherit the color of their preceding parent entry.
    Write-Host ""
    Write-Host "------------------------------------------------------------"
    $lastColor = 'Green'
    $firstAction = $true
    foreach ($line in $deduped) {
        $parts = $line -split '\|', 3
        $cat = $parts[0]
        if ($cat -eq 'DETAIL') {
            Write-Host ("                          {0}" -f $parts[2]) -ForegroundColor $lastColor
            continue
        }
        if ($colorMap.ContainsKey($cat)) {
            $lastColor = $colorMap[$cat]
            Write-Host ("{0}{1,-16} {2}" -f $tagMap[$cat], $parts[1], $parts[2]) -ForegroundColor $lastColor
            continue
        }
        if ($cat -eq 'ACTION') {
            if ($firstAction) {
                Write-Host ""
                Write-Host "  ACTION REQUIRED -- run before tools are ready:" -ForegroundColor Magenta
                $firstAction = $false
            }
            Write-Host "  >>  $($parts[2])" -ForegroundColor Magenta
        }
    }
    Write-Host "------------------------------------------------------------"

    # Preserve summary for log compliance checks
    if ($env:AITOOLS_PRESERVE_SUMMARY -eq "1") {
        $preserveDest = Join-Path $script:logDir "last-summary.txt"
        try { Copy-Item $sfile $preserveDest -Force -ErrorAction Stop }
        catch {
            # Non-blocking: summary already displayed; preservation is for compliance checks
            Write-Host "  warning: could not preserve summary: $_" -ForegroundColor Yellow
        }
    }
    # Summary file cleanup (already displayed; next run creates a fresh one)
    try { Remove-Item $sfile -Force -ErrorAction Stop }
    catch { Write-Host "  note: could not remove summary file" -ForegroundColor Gray }
}

# ---------------------------------------------------------------------------
# Build prerequisite checking
# ---------------------------------------------------------------------------

# Known build prerequisites by ecosystem.
# To add a new prerequisite: add an entry to the appropriate ecosystem array.
# Fields: Name (display), Check (scriptblock), Install (remediation), Platform (win/mac/all)
$script:BuildPrereqs = @{
    "cargo" = @(
        @{
            Name    = "MSVC Build Tools"
            Check   = {
                $vsWhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
                if (Test-Path $vsWhere) {
                    $installs = & $vsWhere -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath 2>$null
                    return [bool]$installs
                }
                return $false
            }
            Install = "winget install Microsoft.VisualStudio.2022.BuildTools (add 'Desktop Development with C++' workload)"
            Platform = "win"
        },
        @{
            Name       = "NASM"
            ToolName   = "nasm"
            # Get-Command exempt: command-existence check with explicit fallback
            Check      = { [bool](Get-Command nasm -ErrorAction SilentlyContinue) }
            # Verified: 2026-03-11 (winget NASM.NASM v3.01, per-user Nullsoft installer)
            KnownPaths = @("$env:LOCALAPPDATA\bin\NASM\nasm.exe", "$env:ProgramFiles\NASM\nasm.exe", "${env:ProgramFiles(x86)}\NASM\nasm.exe")
            Install    = "winget install NASM.NASM"
            Platform   = "win"
        },
        @{
            Name       = "CMake"
            ToolName   = "cmake"
            # Get-Command exempt: command-existence check with explicit fallback
            Check      = { [bool](Get-Command cmake -ErrorAction SilentlyContinue) }
            # UNVERIFIED: assumed MSI behavior -- verify after install (#22)
            KnownPaths = @("$env:ProgramFiles\CMake\bin\cmake.exe")
            Install    = "winget install Kitware.CMake"
            Platform   = "win"
        }
    )
}

# Ensure-ToolOnPath: Verify a tool is findable after installation.
# Tries: 1) Get-Command (current PATH), 2) Refresh-Path (registry reload),
# 3) KnownPaths fallback (filesystem check + session PATH update).
# Returns $true if tool is now on PATH, $false otherwise.
# Callers: setup scripts after winget install, Check-BuildPrereqs fallback.
function Ensure-ToolOnPath {
    param(
        [Parameter(Mandatory)][string]$ToolName,
        [Parameter(Mandatory)][string[]]$KnownPaths
    )
    # Get-Command exempt: command-existence check with explicit fallback
    if (Get-Command $ToolName -ErrorAction SilentlyContinue) { return $true }

    # Reload PATH from registry (picks up changes from winget installers)
    Refresh-Path
    if (Get-Command $ToolName -ErrorAction SilentlyContinue) { return $true }

    # Fallback: check known install locations on disk
    foreach ($kp in $KnownPaths) {
        if (Test-Path $kp) {
            $parentDir = Split-Path $kp -Parent
            $env:Path = "$parentDir;$env:Path"
            Log "$ToolName found at $kp (added to session PATH)"
            return $true
        }
    }
    return $false
}

function Check-BuildPrereqs {
    <#
    .SYNOPSIS
    Checks known build prerequisites for an ecosystem (cargo, pip, go).
    Returns array of missing prerequisites. Empty array = all present.
    Callers decide whether to abort or warn.

    Detection order per prerequisite:
    1. Run the Check scriptblock (typically Get-Command / PATH-based)
    2. If Check fails AND entry has KnownPaths + ToolName, call Ensure-ToolOnPath
       which tries Refresh-Path then filesystem fallback
    3. If still not found, add to missing array
    #>
    param(
        [Parameter(Mandatory)][string]$Ecosystem
    )

    $prereqs = $script:BuildPrereqs[$Ecosystem]
    if (-not $prereqs) { return @() }

    $missing = @()
    foreach ($p in $prereqs) {
        # Filter by platform
        if ($p.Platform -eq "win" -and -not $IsWindows) { continue }
        if ($p.Platform -eq "mac" -and $IsWindows) { continue }

        $present = & $p.Check
        if (-not $present -and $p.KnownPaths -and $p.ToolName) {
            $present = Ensure-ToolOnPath -ToolName $p.ToolName -KnownPaths $p.KnownPaths
        }
        if (-not $present) {
            $missing += $p
        }
    }
    return $missing
}

# ---------------------------------------------------------------------------
# Build failure diagnosis
# ---------------------------------------------------------------------------

# Known build failure signatures.
# To add a new signature: add an entry to this array.
# When a user reports a new build failure, add the error pattern + remedy here.
$script:BuildFailureSignatures = @(
    @{ Pattern = "NASM command not found";                Remedy = "winget install NASM.NASM";                     Name = "NASM (assembler)" }
    @{ Pattern = "linker.*not found|link\.exe.*not found"; Remedy = "Install MSVC Build Tools with C++ workload";  Name = "MSVC linker" }
    @{ Pattern = "cmake.*not found|Could not find cmake"; Remedy = "winget install Kitware.CMake";                 Name = "CMake" }
    @{ Pattern = "pkg-config.*not found";                 Remedy = "Install pkg-config";                           Name = "pkg-config" }
    @{ Pattern = "Python\.h.*not found|python.*dev";      Remedy = "Install Python development headers";           Name = "Python headers" }
    @{ Pattern = "C compiler.*not found|cc.*not found";   Remedy = "Install a C compiler (MSVC/gcc/clang)";        Name = "C compiler" }
    @{ Pattern = "openssl.*not found|OPENSSL_DIR";        Remedy = "Install OpenSSL or set OPENSSL_DIR";           Name = "OpenSSL" }
)

function Diagnose-BuildFailure {
    <#
    .SYNOPSIS
    Scans build output for known failure signatures and returns actionable remediation.
    Call this after a build command fails to surface the real cause.
    Returns $null if no known signature matches (generic failure).
    #>
    param(
        [Parameter(Mandatory)][string]$Output
    )

    foreach ($sig in $script:BuildFailureSignatures) {
        if ($Output -match $sig.Pattern) {
            return $sig
        }
    }
    return $null
}
Initialize-Logging "setup-user-mcp"

# --- OS guard ---
if ($PSVersionTable.PSVersion.Major -ge 6 -and -not $IsWindows) {
    LogError "This script is for Windows. On macOS/Linux, use the .sh version."
    exit 1
}

if ($DryRun) { Log "[DRY RUN] Preview mode -- no files will be written" }

# Check that claude CLI is available
if (-not (Get-Command claude -ErrorAction SilentlyContinue)) {
    LogError "'claude' CLI not found in PATH. Install Claude Code first: https://claude.ai/download"
    exit 1
}

# Check that Node.js is available (required for Chrome DevTools MCP and settings merge)
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    LogError "Node.js not found. Install via 'aitools install' or manually: https://nodejs.org"
    exit 1
} else {
    $nodeVersion = (node --version)
    LogOk "Node.js $nodeVersion found"
}

# --- Check existing MCP server configs via claude mcp list ---
$mcpCurrent = @{}

$savedClaudeCode = $env:CLAUDECODE
Remove-Item Env:\CLAUDECODE -ErrorAction SilentlyContinue

try {
    $mcpListOutput = claude mcp list 2>$null
    $mcpListRc = $LASTEXITCODE
} catch {
    $mcpListOutput = $null
    $mcpListRc = 1
}

if ($savedClaudeCode) {
    $env:CLAUDECODE = $savedClaudeCode
}

if ($mcpListRc -eq 0 -and $mcpListOutput) {
    foreach ($line in $mcpListOutput) {
        $clean = $line -replace '\e\[[0-9;]*m', ''
        if ($clean -match '^(.+?):\s+(.+)\s+-\s+.+$') {
            $name = $Matches[1]
            $details = $Matches[2] -replace '\s+\(HTTP\)$', ''
            $details = $details.TrimEnd()
            $mcpCurrent[$name] = $details
        }
    }
    LogOk "Checked existing MCP config ($($mcpCurrent.Count) servers found)"
} else {
    LogWarn "Could not check existing MCP config; will re-add all servers"
}

function Test-ServerConfigMatches {
    param([string]$Name, [string]$Expected)
    $current = $mcpCurrent[$Name]
    return ($null -ne $current -and $current -eq $Expected)
}

# --- Add all three MCP servers at user scope ---

function Add-McpServer {
    param(
        [string]$Name,
        [string[]]$AddArgs
    )

    # Unset CLAUDECODE to allow running inside a Claude Code session
    $savedClaudeCode = $env:CLAUDECODE
    Remove-Item Env:\CLAUDECODE -ErrorAction SilentlyContinue

    # Remove existing (ignore errors if not found)
    $removeResult = claude mcp remove $Name --scope user 2>&1
    if ($LASTEXITCODE -eq 0) {
        Log "Removed existing $Name config"
    }

    Log "Adding $Name..."
    $addResult = & claude mcp add @AddArgs 2>&1
    if ($LASTEXITCODE -eq 0) {
        LogOk "$Name configured"
        $script:mcpChanged = $true
    } else {
        LogError "Failed to add $Name`: $addResult"
        Write-Summary "ERROR" "claude mcp" "failed to add $Name"
    }

    # Restore CLAUDECODE
    if ($savedClaudeCode) {
        $env:CLAUDECODE = $savedClaudeCode
    }
}

$mcpChanged = $false
Log "Setting up MCP servers for Claude Code (user scope)..."

# Chrome DevTools -- local stdio server via npx (Windows needs cmd /c wrapper)
if ($Force) {
    if ($DryRun) {
        Log "[DRY RUN] Would re-add MCP server: chrome-devtools (-Force)"
    } else {
        Add-McpServer -Name "chrome-devtools" -AddArgs @("chrome-devtools", "--scope", "user", "cmd", "/c", "npx", "chrome-devtools-mcp@latest", "--", "--isolated")
    }
} elseif (Test-ServerConfigMatches "chrome-devtools" "cmd /c npx chrome-devtools-mcp@latest --isolated") {
    LogOk "chrome-devtools already configured, skipping (use -Force to re-add)"
} else {
    if ($DryRun) {
        Log "[DRY RUN] Would add MCP server: chrome-devtools (stdio, --isolated)"
    } else {
        Add-McpServer -Name "chrome-devtools" -AddArgs @("chrome-devtools", "--scope", "user", "cmd", "/c", "npx", "chrome-devtools-mcp@latest", "--", "--isolated")
    }
}

# Vercel -- remote HTTP server (disabled by default via deny rules below)
if ($Force) {
    if ($DryRun) {
        Log "[DRY RUN] Would re-add MCP server: vercel (-Force)"
    } else {
        Add-McpServer -Name "vercel" -AddArgs @("--transport", "http", "--scope", "user", "vercel", "https://mcp.vercel.com")
    }
} elseif (Test-ServerConfigMatches "vercel" "https://mcp.vercel.com") {
    LogOk "vercel already configured, skipping (use -Force to re-add)"
} else {
    if ($DryRun) {
        Log "[DRY RUN] Would add MCP server: vercel (http)"
    } else {
        Add-McpServer -Name "vercel" -AddArgs @("--transport", "http", "--scope", "user", "vercel", "https://mcp.vercel.com")
    }
}

# Webflow -- remote HTTP server (disabled by default via deny rules below)
if ($Force) {
    if ($DryRun) {
        Log "[DRY RUN] Would re-add MCP server: webflow (-Force)"
    } else {
        Add-McpServer -Name "webflow" -AddArgs @("--transport", "http", "--scope", "user", "webflow", "https://mcp.webflow.com/mcp")
    }
} elseif (Test-ServerConfigMatches "webflow" "https://mcp.webflow.com/mcp") {
    LogOk "webflow already configured, skipping (use -Force to re-add)"
} else {
    if ($DryRun) {
        Log "[DRY RUN] Would add MCP server: webflow (http)"
    } else {
        Add-McpServer -Name "webflow" -AddArgs @("--transport", "http", "--scope", "user", "webflow", "https://mcp.webflow.com/mcp")
    }
}

# --- Merge deny rules into ~/.claude/settings.json ---
# Vercel and Webflow are disabled by default at user level.
# Projects enable them via .claude/settings.local.json (aitools --addmcp).

$settingsFile = Join-Path (Join-Path $env:USERPROFILE ".claude") "settings.json"
$settingsDir = Split-Path $settingsFile -Parent
Log "Merging deny rules into $settingsFile..."

if (-not (Test-Path $settingsDir)) {
    if (-not $DryRun) {
        New-Item -ItemType Directory -Path $settingsDir -Force | Out-Null
    }
}

# Back up before merge
if (-not $DryRun) {
    Backup-File -FilePath $settingsFile
}

# Read existing settings or start fresh
$settings = @{}
$corrupt = $false
if (Test-Path $settingsFile) {
    try {
        $raw = Get-Content $settingsFile -Raw
        $settings = ConvertPSObjectToHashtable ($raw | ConvertFrom-Json)
    } catch {
        $corrupt = $true
        LogWarn "$settingsFile could not be parsed ($_)"
    }
}
$beforeKeys = @($settings.Keys)

# Ensure permissions.deny exists
if (-not $settings.ContainsKey("permissions")) { $settings["permissions"] = @{} }
if (-not $settings["permissions"].ContainsKey("deny")) { $settings["permissions"]["deny"] = @() }

# Add deny rules if not already present
$denyRules = @("MCP(vercel)", "MCP(webflow)")
foreach ($rule in $denyRules) {
    if ($rule -notin $settings["permissions"]["deny"]) {
        $settings["permissions"]["deny"] += $rule
    }
}

# Clobber detection
$managedKeys = @("permissions")
$lostKeys = @($beforeKeys | Where-Object { $_ -notin $settings.Keys })

if ($DryRun) {
    Log "[DRY RUN] $settingsFile`: merge deny rules"
    Log "  Managed fields: permissions.deny"
    if ($lostKeys.Count -gt 0) {
        LogWarn "[DRY RUN] CLOBBER: would lose non-managed fields: $($lostKeys -join ', ')"
    }
    if ($corrupt) {
        LogWarn "[DRY RUN] File is corrupt -- -Force required to overwrite"
    }
} elseif ($corrupt -and -not $Force) {
    LogError "$settingsFile is corrupt. Use -Force to overwrite, or fix manually."
    Write-Summary "ERROR" "claude mcp" "settings corrupt"
} elseif ($lostKeys.Count -gt 0 -and -not $Force) {
    LogError "$settingsFile merge would lose fields: $($lostKeys -join ', '). Use -Force to proceed."
    Write-Summary "ERROR" "claude mcp" "merge would lose fields"
} else {
    if ($corrupt) { LogWarn "Proceeding with -Force on corrupt file" }
    if ($lostKeys.Count -gt 0) { LogWarn "Proceeding with -Force, losing fields: $($lostKeys -join ', ')" }

    $mergedNorm = Normalize-JsonForComparison $settings -Depth 10
    $existingNorm = if ($raw -and -not $corrupt) {
        Normalize-JsonForComparison (ConvertPSObjectToHashtable ($raw | ConvertFrom-Json)) -Depth 10
    } else { $null }

    if (-not $corrupt -and $lostKeys.Count -eq 0 -and $mergedNorm -eq $existingNorm) {
        LogOk "Deny rules unchanged in $settingsFile"
    } else {
        $json = $settings | ConvertTo-Json -Depth 10
        $resolvedPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($settingsFile)
        [System.IO.File]::WriteAllText($resolvedPath, $json, [System.Text.UTF8Encoding]::new($false))

        # Post-write validation
        try {
            $vContent = [System.IO.File]::ReadAllText($resolvedPath)
            $vParsed = $vContent | ConvertFrom-Json
            if (-not ($vParsed.PSObject.Properties.Name -contains "permissions")) {
                LogError "Validation failed: $settingsFile missing required field 'permissions'"
            }
        } catch {
            LogError "Validation failed: $settingsFile is not valid JSON -- $_"
        }

        LogOk "Deny rules set for vercel, webflow in $settingsFile"
        $mcpChanged = $true
    }
}

if ($DryRun) {
    Log "[DRY RUN] Would configure user-level MCP (all servers; vercel/webflow disabled by default)"
} else {
    LogOk "User-level MCP configured (all servers; vercel/webflow disabled by default)"
    if ($errors -eq 0) {
        Write-Summary "OK" "claude mcp" $(if ($mcpChanged) { "configured" } else { "unchanged" })
    }
}
Log "To enable per project: aitools --addmcp vercel"
Log "To check status: aitools mcp"

# Display cloud MCP servers configured at claude.ai.
# Silent no-op if claude CLI unavailable or no cloud servers found.
function Show-CloudMcpStatus {
    if (-not (Get-Command claude -ErrorAction SilentlyContinue)) { return }
    $savedClaudeCode = $env:CLAUDECODE
    Remove-Item Env:\CLAUDECODE -ErrorAction SilentlyContinue
    try {
        $savedEncoding = [Console]::OutputEncoding
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $raw = claude mcp list 2>$null
        [Console]::OutputEncoding = $savedEncoding
    } catch { $raw = $null }
    if ($savedClaudeCode) { $env:CLAUDECODE = $savedClaudeCode }
    if (-not $raw) { return }
    $entries = @()
    foreach ($line in $raw) {
        $clean = $line -replace '\e\[[0-9;]*m', ''
        if ($clean -match '^claude\.ai\s+(.+?):\s+.+\s+-\s+(.+)$') {
            $name = $Matches[1].Trim()
            $status = $Matches[2].Trim()
            $entries += [PSCustomObject]@{ Name = $name; Status = $status }
        }
    }
    if ($entries.Count -eq 0) { return }
    Log "Cloud MCP servers (configured at claude.ai):"
    foreach ($entry in $entries) {
        $pad = if ($entry.Name.Length -lt 24) { " " * (24 - $entry.Name.Length) } else { " " }
        Log "  $($entry.Name)$pad$($entry.Status)"
    }
}

# --- Deploy Chrome DevTools skills (embedded) ---
# Vendored from https://github.com/ChromeDevTools/chrome-devtools-mcp/tree/main/skills
# Content embedded at build time by build-deploy.sh for self-contained deployment.

$skillsDest = Join-Path (Join-Path $env:USERPROFILE ".claude") "skills"
$skillsDestCursor = Join-Path (Join-Path $env:USERPROFILE ".cursor") "skills"
$allSkillDests = @($skillsDest, $skillsDestCursor)

function Deploy-EmbeddedSkill {
    param([string]$SkillName, [string]$DestBase, [string]$ToolName, [string]$Content)

    $destDir = Join-Path $DestBase $SkillName
    $dest = Join-Path $destDir "SKILL.md"
    $adoptLabel = ""
    $cfgFile = Join-Path $env:USERPROFILE ".aitools\config.json"
    $repoPath = ReadConfigKey -File $cfgFile -Key "repoPath"
    if ($repoPath) { $adoptLabel = "shared/" }

    $skillResult = Deploy-ManagedFile -Content $Content -DestPath $dest -ToolName $ToolName -ItemName $SkillName -AdoptLabel $adoptLabel

    if ($skillResult -eq "adopted") {
        if ($repoPath) {
            $adoptDir = Join-Path (Join-Path $repoPath "shared\skills") $SkillName
            if (-not (Test-Path $adoptDir)) {
                New-Item -ItemType Directory -Path $adoptDir -Force | Out-Null
            }
            $adoptDest = Join-Path $adoptDir "SKILL.md"
            Copy-Item -Path $dest -Destination $adoptDest -Force -ErrorAction Stop
            LogOk "Adopted skill to shared/: $SkillName"
        }
        # Sync to all other deploy targets (prevents clobber)
        foreach ($otherBase in $allSkillDests) {
            if ($otherBase -eq $DestBase) { continue }
            $otherDir = Join-Path $otherBase $SkillName
            if (-not (Test-Path $otherDir)) {
                New-Item -ItemType Directory -Path $otherDir -Force | Out-Null
            }
            Copy-Item -Path $dest -Destination (Join-Path $otherDir "SKILL.md") -Force
        }
    }
    Record-DeployOutcome -Outcome $skillResult -ToolName $ToolName -ItemName $SkillName
}

$chromeDevtoolsSkill = @'
---
name: chrome-devtools
description: Uses Chrome DevTools via MCP for efficient debugging, troubleshooting and browser automation. Use when debugging web pages, automating browser interactions, analyzing performance, or inspecting network requests.
---

## Core Concepts

**Browser lifecycle**: Browser starts automatically on first tool call using a persistent Chrome profile. Configure via CLI args in the MCP server configuration: `npx chrome-devtools-mcp@latest --help`.

**Page selection**: Tools operate on the currently selected page. Use `list_pages` to see available pages, then `select_page` to switch context.

**Element interaction**: Use `take_snapshot` to get page structure with element `uid`s. Each element has a unique `uid` for interaction. If an element isn't found, take a fresh snapshot - the element may have been removed or the page changed.

## Workflow Patterns

### Before interacting with a page

1. Navigate: `navigate_page` or `new_page`
2. Wait: `wait_for` to ensure content is loaded if you know what you look for.
3. Snapshot: `take_snapshot` to understand page structure
4. Interact: Use element `uid`s from snapshot for `click`, `fill`, etc.

### Efficient data retrieval

- Use `filePath` parameter for large outputs (screenshots, snapshots, traces)
- Use pagination (`pageIdx`, `pageSize`) and filtering (`types`) to minimize data
- Set `includeSnapshot: false` on input actions unless you need updated page state

### Tool selection

- **Automation/interaction**: `take_snapshot` (text-based, faster, better for automation)
- **Visual inspection**: `take_screenshot` (when user needs to see visual state)
- **Additional details**: `evaluate_script` for data not in accessibility tree

### Expanding accordions, tabs, and FAQs

Many pages use JS-rendered accordions/tabs (e.g., FAQ sections) whose content is hidden until clicked. The a11y tree shows them as `tab` or `button` elements with `expandable` state but no inner content until expanded.

**Pattern:**
1. `take_snapshot` — identify the collapsed elements (look for `tab`/`button` with `expandable` but NOT `expanded`)
2. `click` on the element `uid` to expand it
3. `take_snapshot` again — the expanded content now appears inline in the tab/button's accessible name or as child nodes
4. Repeat for each accordion item

**Tips:**
- Only one accordion panel may be open at a time (clicking the next may collapse the previous) — snapshot after each click
- The expanded content often appears directly in the element's accessible name text, not as separate child nodes
- Save each snapshot to `filePath` to avoid flooding context when extracting large amounts of content
- If clicking doesn't expand (some require user interaction), ask the user to expand manually, then snapshot

### Parallel execution

You can send multiple tool calls in parallel, but maintain correct order: navigate → wait → snapshot → interact.

## Troubleshooting

If `chrome-devtools-mcp` is insufficient, guide users to use Chrome DevTools UI:

- https://developer.chrome.com/docs/devtools
- https://developer.chrome.com/docs/devtools/ai-assistance

If there are errors launching `chrome-devtools-mcp` or Chrome, refer to https://github.com/ChromeDevTools/chrome-devtools-mcp/blob/main/docs/troubleshooting.md.
'@

$a11ySkill = @'
---
name: a11y-debugging
description: Uses Chrome DevTools MCP for accessibility (a11y) debugging and auditing based on web.dev guidelines. Use when testing semantic HTML, ARIA labels, focus states, keyboard navigation, tap targets, and color contrast.
---

## Core Concepts

**Accessibility Tree vs DOM**: Visually hiding an element (e.g., `CSS opacity: 0`) behaves differently for screen readers than `display: none` or `aria-hidden="true"`. The `take_snapshot` tool returns the accessibility tree of the page, which represents what assistive technologies "see", making it the most reliable source of truth for semantic structure.

**Reading web.dev documentation**: If you need to research specific accessibility guidelines (like `https://web.dev/articles/accessible-tap-targets`), you can append `.md.txt` to the URL (e.g., `https://web.dev/articles/accessible-tap-targets.md.txt`) to fetch the clean, raw markdown version. This is much easier to read!

## Workflow Patterns

### 1. Browser Issues & Audits

Chrome automatically checks for common accessibility problems. Use `list_console_messages` to check for these native audits first:

- `types`: `["issue"]`
- `includePreservedMessages`: `true` (to catch issues that occurred during page load)

This often reveals missing labels, invalid ARIA attributes, and other critical errors without manual investigation.

### 2. Semantics & Structure

The accessibility tree exposes the heading hierarchy and semantic landmarks.

1.  Navigate to the page.
2.  Use `take_snapshot` to capture the accessibility tree.
3.  **Check Heading Levels**: Ensure heading levels (`h1`, `h2`, `h3`, etc.) are logical and do not skip levels. The snapshot will include heading roles.
4.  **Content Reordering**: Verify that the DOM order (which drives the accessibility tree) matches the visual reading order. Use `take_screenshot` to inspect the visual layout and compare it against the snapshot structure to catch CSS floats or absolute positioning that jumbles the logical flow.

### 3. Labels, Forms & Text Alternatives

1.  Locate buttons, inputs, and images in the `take_snapshot` output.
2.  Ensure interactive elements have an accessible name (e.g., a button should not just say `""` if it only contains an icon).
3.  **Orphaned Inputs**: Verify that all form inputs have associated labels. Use `evaluate_script` to check for inputs missing `id` (for `label[for]`) or `aria-label`:
    ```js
    () =>
      Array.from(document.querySelectorAll('input, select, textarea'))
        .filter(i => {
          const hasId = i.id && document.querySelector(`label[for="${i.id}"]`);
          const hasAria =
            i.getAttribute('aria-label') || i.getAttribute('aria-labelledby');
          return !hasId && !hasAria && !i.closest('label');
        })
        .map(i => ({
          tag: i.tagName,
          id: i.id,
          name: i.name,
          placeholder: i.placeholder,
        }));
    ```

4.  Check images for `alt` text.

### 4. Focus & Keyboard Navigation

Testing "keyboard traps" and proper focus management without visual feedback relies on tracking the focused element.

1.  Use the `press_key` tool with `"Tab"` or `"Shift+Tab"` to move focus.
2.  Use `take_snapshot` to capture the updated accessibility tree.
3.  Locate the element marked as focused in the snapshot to verify focus moved to the expected interactive element.
4.  If a modal opens, focus must move into the modal and "trap" within it until closed.

### 5. Tap Targets and Visuals

According to web.dev, tap targets should be at least 48x48 pixels with sufficient spacing. Since the accessibility tree doesn't show sizes, use `evaluate_script`:

```js
// Usage in console: copy, paste, and call with element: fn(element)
el => {
 const rect = el.getBoundingClientRect();
 return {width: rect.width, height: rect.height};
};
```

_Pass the element's `uid` from the snapshot as an argument to `evaluate_script`._

### 6. Color Contrast

To verify color contrast ratios, start by checking for native accessibility issues:

1.  Call `list_console_messages` with `types: ["issue"]`.
2.  Look for "Low Contrast" issues in the output.

If native audits do not report issues (which may happen in some headless environments) or if you need to check a specific element manually, you can use the following script as a fallback approximation.

**Note**: This script uses a simplified algorithm and may not account for transparency, gradients, or background images. For production-grade auditing, consider injecting `axe-core`.

```js
el => {
  function getRGB(colorStr) {
    const match = colorStr.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
    return match
      ? [parseInt(match[1]), parseInt(match[2]), parseInt(match[3])]
      : [255, 255, 255];
  }
  function luminance(r, g, b) {
    const a = [r, g, b].map(function (v) {
      v /= 255;
      return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    });
    return a[0] * 0.2126 + a[1] * 0.7152 + a[2] * 0.0722;
  }

  const style = window.getComputedStyle(el);
  const fg = getRGB(style.color);
  let bg = getRGB(style.backgroundColor);

  // Basic contrast calculation (Note: Doesn't account for transparency over background images)
  const l1 = luminance(fg[0], fg[1], fg[2]);
  const l2 = luminance(bg[0], bg[1], bg[2]);
  const ratio = (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);

  return {
    color: style.color,
    bg: style.backgroundColor,
    contrastRatio: ratio.toFixed(2),
  };
};
```

_Pass the element's `uid` to test the contrast against WCAG AA (4.5:1 for normal text, 3:1 for large text)._

### 7. Global Page Checks

Verify document-level accessibility settings often missed in component testing:

```js
() => ({
  lang:
    document.documentElement.lang ||
    'MISSING - Screen readers need this for pronunciation',
  title: document.title || 'MISSING - Required for context',
  viewport:
    document.querySelector('meta[name="viewport"]')?.content ||
    'MISSING - Check for user-scalable=no (bad practice)',
  reducedMotion: window.matchMedia('(prefers-reduced-motion: reduce)').matches
    ? 'Enabled'
    : 'Disabled',
});
```

### 8. ARIA Live Regions

Live regions announce dynamic content updates to screen readers. Verify they work correctly:

1. Use `take_snapshot` to identify elements with `aria-live`, `role="alert"`, `role="status"`, or `role="log"`
2. Trigger the dynamic update (e.g., form submission, async load)
3. `take_snapshot` again — check that the live region content changed
4. Verify `aria-live` politeness: `"polite"` for non-urgent updates, `"assertive"` for critical alerts

**Common mistakes:**
- Adding `aria-live` to an element that already has content (screen readers only announce *changes*)
- Using `aria-live="assertive"` for non-critical notifications (interrupts the user)
- Nesting live regions (unpredictable behavior across screen readers)

## Troubleshooting

If standard a11y queries fail or the `evaluate_script` snippets return unexpected results:

- **Visual Inspection**: If automated scripts cannot determine contrast (e.g., text over gradient images or complex backgrounds), use `take_screenshot` to capture the element. While models cannot measure exact contrast ratios from images, they can visually assess legibility and identifying obvious issues.
'@

Log "Deploying skills to $skillsDest..."
$errorsBeforeClaudeSkills = $errors
Initialize-DeployTracker
Deploy-EmbeddedSkill "chrome-devtools" $skillsDest "claude skills" $chromeDevtoolsSkill
Deploy-EmbeddedSkill "a11y-debugging" $skillsDest "claude skills" $a11ySkill
if ($errors -eq $errorsBeforeClaudeSkills) {
    Write-DeployTrackerSummary -ToolName "claude skills"
} else {
    Write-Summary "ERROR" "claude skills" "deploy failed"
}

Log "Deploying skills to $skillsDestCursor..."
$errorsBeforeCursorSkills = $errors
Initialize-DeployTracker
Deploy-EmbeddedSkill "chrome-devtools" $skillsDestCursor "cursor skills" $chromeDevtoolsSkill
Deploy-EmbeddedSkill "a11y-debugging" $skillsDestCursor "cursor skills" $a11ySkill
if ($errors -eq $errorsBeforeCursorSkills) {
    Write-DeployTrackerSummary -ToolName "cursor skills"
} else {
    Write-Summary "ERROR" "cursor skills" "deploy failed"
}

if ($errors -gt 0) {
    Log "FAILED with $errors error(s). See log: $logFile" "error"
    exit 1
} elseif ($warnings -gt 0) {
    Show-CloudMcpStatus
    Log "COMPLETED with $warnings warning(s)" "warn"
    exit 0
} else {
    Show-CloudMcpStatus
    Log "COMPLETED successfully" "ok"
    exit 0
}
