#!/usr/bin/env bash
# Generated by scripts/build-deploy.sh — do not edit directly.
# setup-cursor-mcp.sh — Installs/updates MCP servers for Cursor on macOS/Linux
# Safe to re-run — merges managed servers into ~/.cursor/mcp.json.
#
# Managed fields: mcpServers.chrome-devtools, mcpServers.vercel, mcpServers.webflow
# Preserved: all other mcpServers entries, all other top-level keys
#
# All three servers at user level. Chrome DevTools enabled globally;
# Vercel and Webflow are present but disabled via `agent mcp disable`.
# Use `aitools --addmcp` to enable per project.
#
# Cursor uses its own MCP config at ~/.cursor/mcp.json (separate from Claude Code's ~/.claude.json).
# Remote servers use the "url" key directly. Local stdio servers use "command" + "args".

set -euo pipefail

# --- Flag parsing ---
DRY_RUN=false
FORCE=false
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --force)   FORCE=true ;;
    esac
done
[ "${AITOOLS_DRY_RUN:-}" = "1" ] && DRY_RUN=true

# --- Logging ---
LOG_DIR="$HOME/Library/Logs/aitools"
[ "$(uname -s)" != "Darwin" ] && LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/aitools"
LOG_FILE="$LOG_DIR/deploy.log"
SCRIPT_NAME="setup-cursor-mcp"
mkdir -p "$LOG_DIR"

display_path() {
    if command -v cygpath &>/dev/null; then cygpath -w "$1"; else printf '%s' "$1"; fi
}
ERRORS=0
log()       { printf '[%s] [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$SCRIPT_NAME" "$1" | tee -a "$LOG_FILE"; }
log_ok()    { log "OK: $1"; }
log_error() { log "ERROR: $1"; ERRORS=$((ERRORS + 1)); }
log_warn()  { log "WARN: $1"; }
write_summary() {
    local cat="$1" msg="$2"
    [ -n "${AITOOLS_SUMMARY_FILE:-}" ] && printf '%s|%s\n' "$cat" "$msg" >> "$AITOOLS_SUMMARY_FILE"
}

# Backup a file before overwriting. Keeps at most $max_backups copies.
backup_file() {
    local file="$1" max_backups=20
    [ -f "$file" ] || return 0
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    cp "$file" "${file}.bak.${ts}"
    # Prune oldest beyond limit
    ls -1t "${file}.bak."* 2>/dev/null | tail -n +$((max_backups + 1)) | xargs rm -f 2>/dev/null
    log "Backed up $(display_path "$file")"
}

# --- OS guard ---
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        log_error "This script is for macOS/Linux. On Windows, use ${SCRIPT_NAME}.ps1 instead."
        exit 1 ;;
esac

[ "$DRY_RUN" = "true" ] && log "[DRY RUN] Preview mode -- no files will be written"

# Check that Node.js is available (required for Chrome DevTools MCP)
if ! command -v node &> /dev/null; then
    log_error "Node.js not found. Install via 'aitools install' or manually: https://nodejs.org"
    exit 1
else
    log_ok "Node.js $(node --version) found"
fi

# Ensure ~/.cursor directory exists
cursor_dir="$HOME/.cursor"
mkdir -p "$cursor_dir"

mcp_json="$cursor_dir/mcp.json"

if [ "$DRY_RUN" != "true" ]; then
    backup_file "$mcp_json"
fi
if [ -f "$mcp_json" ]; then
    log "Merging managed servers into $(display_path "$mcp_json")"
else
    log "Creating $(display_path "$mcp_json")"
fi

# Merge managed servers — preserves user-added servers and other keys
MERGE_RESULT=$(node -e "
const fs = require('fs');
const f = process.argv[1];
const dryRun = process.argv[2] === 'true';
const force = process.argv[3] === 'true';

// Read existing config (ENOENT = start fresh, parse error = warn)
let config = {};
let corrupt = false;
try {
    config = JSON.parse(fs.readFileSync(f, 'utf8'));
} catch (e) {
    if (e.code !== 'ENOENT') {
        corrupt = true;
        console.error('Warning: ' + f + ' is invalid JSON');
    }
}
const beforeKeys = Object.keys(config);

// Ensure mcpServers exists
if (!config.mcpServers || typeof config.mcpServers !== 'object') {
    config.mcpServers = {};
}

// Set managed servers (macOS uses npx directly, no cmd /c wrapper)
config.mcpServers['chrome-devtools'] = {
    command: 'npx',
    args: ['-y', 'chrome-devtools-mcp@latest', '--isolated']
};
config.mcpServers['vercel'] = { url: 'https://mcp.vercel.com' };
config.mcpServers['webflow'] = { url: 'https://mcp.webflow.com/mcp' };

// Clobber detection
const managedKeys = ['mcpServers'];
const afterKeys = Object.keys(config);
const lostKeys = beforeKeys.filter(k => !afterKeys.includes(k));

if (dryRun) {
    console.error('[DRY RUN] ' + f + ': merge MCP servers');
    console.error('  Managed fields: mcpServers.chrome-devtools, mcpServers.vercel, mcpServers.webflow');
    if (lostKeys.length > 0) console.error('  CLOBBER WARNING: would lose: ' + lostKeys.join(', '));
    if (corrupt) console.error('  File is corrupt -- --force required');
    console.log('dry-run');
} else if (corrupt && !force) {
    console.error('ERROR: ' + f + ' is corrupt. Use --force to overwrite, or fix manually.');
    console.log('error-corrupt');
} else if (lostKeys.length > 0 && !force) {
    console.error('ERROR: merge would lose fields: ' + lostKeys.join(', ') + '. Use --force to proceed.');
    console.log('error-clobber');
} else {
    if (corrupt) console.error('Warning: proceeding with --force on corrupt file');
    if (lostKeys.length > 0) console.error('Warning: proceeding with --force, losing fields: ' + lostKeys.join(', '));
    fs.writeFileSync(f, JSON.stringify(config, null, 2) + '\n');

    // Post-write validation
    const _v = JSON.parse(fs.readFileSync(f, 'utf8'));
    if (!_v.mcpServers) { console.error('Validation failed: missing mcpServers'); process.exit(1); }
    console.log('ok');
}
" "$mcp_json" "$DRY_RUN" "$FORCE")

case "$MERGE_RESULT" in
    ok)
        log_ok "Cursor MCP config written to $(display_path "$mcp_json")"
        log "Servers configured: chrome-devtools (stdio), vercel (http), webflow (http)"
        write_summary OK "cursor MCP    merged" ;;
    dry-run)
        log "[DRY RUN] Would write Cursor MCP config"
        log "  Servers: chrome-devtools (stdio), vercel (http), webflow (http)" ;;
    error-corrupt)
        log_error "$(display_path "$mcp_json") is corrupt. Use --force to overwrite." ;;
    error-clobber)
        log_error "$(display_path "$mcp_json") merge would lose fields. Use --force to proceed." ;;
    *)
        log_error "Unexpected merge result: $MERGE_RESULT" ;;
esac

# --- Disable vercel/webflow via Cursor CLI if available ---
if [ "$DRY_RUN" = "true" ]; then
    log "[DRY RUN] Would disable vercel/webflow via Cursor CLI (if available)"
elif command -v agent &>/dev/null; then
    for server in vercel webflow; do
        if agent mcp disable "$server" 2>&1; then
            log_ok "$server disabled in Cursor"
        else
            log_error "Failed to disable $server in Cursor"
        fi
    done
else
    log "Cursor CLI (agent) not found -- disable vercel/webflow manually:"
    log "  Cursor Settings > Features > MCP > toggle off vercel and webflow"
    log "  Or install Cursor CLI: aitools install"
fi

log ""
log "Next steps:"
log "  1. Restart Cursor"
log "  2. Go to Cursor Settings > Tools & MCP to verify servers"
log "  3. To enable vercel/webflow per project: aitools --addmcp vercel"

# --- Exit ---
if [ "$ERRORS" -gt 0 ]; then
    log "FAILED with $ERRORS error(s). See log: $LOG_FILE"
    exit 1
else
    log "COMPLETED successfully"
    exit 0
fi
