# Generated by scripts/build-deploy.sh — do not edit directly.
# setup-typst.ps1 -- Installs/updates Typst (document typesetting / PDF compiler) on Windows
# Safe to re-run -- detects existing install and upgrades as needed.
#
# Windows: Uses winget (preferred). Removes non-preferred installs (cargo, npm).
#
# See reference/tool-registry.md for install source details.

# --- Shared library ---
# aitools-lib.ps1 -- shared helpers for all aitools PowerShell scripts
# Dot-sourced, not executed directly.
#
# Provides: ReadConfigKey, Initialize-Logging, Log/LogOk/LogError/LogWarn,
# Write-Summary, Show-Summary.
#
# Usage:
#   . (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "aitools-lib.ps1")
#   Initialize-Logging "script-name"
#
# Entry points (aitools.ps1, aitools-install.ps1) override log functions after
# sourcing for specialized logging (file-only, JSONL, etc.).
#
# Platform detection uses PS 7+ built-in $IsMacOS/$IsWindows -- no custom variables.

# ---------------------------------------------------------------------------
# Config reader (PS 5.1 compatible)
# ---------------------------------------------------------------------------
function ReadConfigKey {
    param([string]$File, [string]$Key)
    if (-not (Test-Path $File)) { return $null }
    try {
        $json = Get-Content $File -Raw -ErrorAction Stop | ConvertFrom-Json
        $val = $json.$Key
        if ($val) { return $val }
    } catch {
        # File exists but is invalid JSON -- warn so callers know the null
        # return means "corrupt", not "missing key"
        Write-Host "      WARN: could not parse $File" -ForegroundColor Yellow
    }
    return $null
}

# ---------------------------------------------------------------------------
# Logging init
# ---------------------------------------------------------------------------
# Sets $script:scriptName, $script:logDir, $script:logFile; resets
# $script:errors, $script:warnings. Creates log directory.
# Usage: Initialize-Logging "setup-foo"
function Initialize-Logging {
    param([Parameter(Mandatory)][string]$Name)
    $script:scriptName = $Name
    if ($IsWindows -or (-not (Test-Path variable:IsMacOS))) {
        # Windows (PS 7+) or PS 5.1 (always Windows)
        $script:logDir = Join-Path $env:LOCALAPPDATA "aitools"
    } else {
        # macOS/Linux
        $script:logDir = Join-Path $HOME "Library/Logs/aitools"
    }
    $script:logFile = Join-Path $script:logDir "deploy.log"
    if (-not (Test-Path $script:logDir)) {
        New-Item -ItemType Directory -Path $script:logDir -Force | Out-Null
    }
    $script:errors = 0
    $script:warnings = 0
}

# ---------------------------------------------------------------------------
# Standard logging (console + log file, with [level] tag)
# ---------------------------------------------------------------------------
function Log($msg, $level = "info") {
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $line = "[$ts] [$scriptName] [$level] $msg"
    Add-Content -Path $logFile -Value $line
    switch ($level) {
        "error" { Write-Host $line -ForegroundColor Red }
        "warn"  { Write-Host $line -ForegroundColor Yellow }
        default { Write-Host $line }
    }
}
function LogOk($msg)    { Log $msg "ok" }
function LogError($msg) { Log $msg "error"; $script:errors++ }
function LogWarn($msg)  { Log $msg "warn"; $script:warnings++ }

# ---------------------------------------------------------------------------
# Summary writer (3-arg: category, tool, detail)
# ---------------------------------------------------------------------------
function Write-Summary($cat, $tool, $detail) {
    if ($env:AITOOLS_SUMMARY_FILE) {
        Add-Content -Path $env:AITOOLS_SUMMARY_FILE -Value "${cat}|${tool}|${detail}"
    }
}

# ---------------------------------------------------------------------------
# Summary panel renderer
# ---------------------------------------------------------------------------
# Reads AITOOLS_SUMMARY_FILE, displays colored panel, cleans up.
# Silent no-op if file unset, missing, or empty.
function Show-Summary {
    $sfile = $env:AITOOLS_SUMMARY_FILE
    if (-not $sfile -or -not (Test-Path $sfile)) { return }
    $lines = Get-Content $sfile -ErrorAction SilentlyContinue
    if (-not $lines) { Remove-Item $sfile -ErrorAction SilentlyContinue; return }
    Write-Host ""
    Write-Host "------------------------------------------------------------"
    foreach ($line in $lines) {
        $parts = $line -split '\|', 3
        if ($parts[0] -eq 'OK') { Write-Host ("  [ok]  {0,-16} {1}" -f $parts[1], $parts[2]) -ForegroundColor Green }
    }
    foreach ($line in $lines) {
        $parts = $line -split '\|', 3
        if ($parts[0] -eq 'WARN') { Write-Host ("  [!]   {0,-16} {1}" -f $parts[1], $parts[2]) -ForegroundColor Yellow }
    }
    foreach ($line in $lines) {
        $parts = $line -split '\|', 3
        if ($parts[0] -eq 'ERROR') { Write-Host ("  [ERR] {0,-16} {1}" -f $parts[1], $parts[2]) -ForegroundColor Red }
    }
    $firstAction = $true
    foreach ($line in $lines) {
        $parts = $line -split '\|', 3
        if ($parts[0] -eq 'ACTION') {
            if ($firstAction) {
                Write-Host ""
                Write-Host "  ACTION REQUIRED -- run before tools are ready:" -ForegroundColor Magenta
                $firstAction = $false
            }
            Write-Host "  >>  $($parts[2])" -ForegroundColor Magenta
        }
    }
    Write-Host "------------------------------------------------------------"
    Remove-Item $sfile -ErrorAction SilentlyContinue
}
Initialize-Logging "setup-typst"

# --- OS guard ---
if ($PSVersionTable.PSVersion.Major -ge 6 -and -not $IsWindows) {
    LogError "This script is for Windows. On macOS/Linux, use the .sh version."
    exit 1
}

# Helper: refresh PATH from registry (picks up winget installs in same session)
function Refresh-Path {
    $machinePath = [Environment]::GetEnvironmentVariable("Path", "Machine")
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    $env:Path = "$machinePath;$userPath"
}

# --- Cleanup non-preferred installs ---
# Cargo typst-cli: different binary path, may shadow winget install
$cargoCmd = Get-Command cargo -ErrorAction SilentlyContinue
# Get-Command exempt: command-existence check with if/else fallback
if ($cargoCmd) {
    Log "Checking for cargo typst-cli..."
    # Cleanup: cargo stderr may contain "not installed" msg; non-blocking, winget install follows
    & cargo uninstall typst-cli 2>$null
}
# npm typst: third-party wrapper, not official
$npmCmd = Get-Command npm -ErrorAction SilentlyContinue
# Get-Command exempt: command-existence check with if/else fallback
if ($npmCmd) {
    Log "Checking for npm typst..."
    # Cleanup: npm stderr may contain "not installed" msg; non-blocking, winget install follows
    & npm uninstall -g typst 2>$null
}

# --- Install/update ---
$typstCmd = Get-Command typst -ErrorAction SilentlyContinue
# Get-Command exempt: command-existence check with if/else fallback
if ($typstCmd) {
    Log "Typst found -- upgrading via winget..."
    $wingetOutput = winget upgrade --id Typst.Typst --accept-package-agreements --accept-source-agreements 2>&1 | Out-String
    $wingetOutput.Trim().Split("`n") | ForEach-Object {
        $l = $_.TrimEnd()
        if ($l.Trim() -and $l.Trim() -notmatch '^[-\\|/]+$') { Log $l }
    }
    if ($wingetOutput -match 'No available upgrade|No newer package versions') {
        LogOk "Typst already up to date"
    } elseif ($LASTEXITCODE -ne 0) {
        LogError "winget upgrade typst failed (exit code $LASTEXITCODE)"
        Write-Summary "ERROR" "typst" "winget upgrade failed (exit $LASTEXITCODE)"
    }
    Refresh-Path
    # Suppress stderr: typst may emit warnings on some configs; result checked immediately
    $version = (typst --version 2>$null)
    if ($version) {
        LogOk $version
        Write-Summary "OK" "typst" "$version"
    } else {
        LogError "typst --version failed after upgrade"
        Write-Summary "ERROR" "typst" "version check failed after upgrade"
    }
} else {
    Log "Installing Typst via winget..."
    $wingetOutput = winget install --id Typst.Typst --accept-package-agreements --accept-source-agreements 2>&1 | Out-String
    $wingetOutput.Trim().Split("`n") | ForEach-Object {
        $l = $_.TrimEnd()
        if ($l.Trim() -and $l.Trim() -notmatch '^[-\\|/]+$') { Log $l }
    }
    if ($LASTEXITCODE -ne 0) {
        LogError "winget install typst failed (exit code $LASTEXITCODE)"
        Write-Summary "ERROR" "typst" "winget install failed (exit $LASTEXITCODE)"
    }
    Refresh-Path
    $typstCmd = Get-Command typst -ErrorAction SilentlyContinue
    # Get-Command exempt: command-existence check with if/else fallback
    if ($typstCmd) {
        # Suppress stderr: typst may emit warnings on some configs; result used in log
        $version = (typst --version 2>$null)
        LogOk "Typst installed ($version)"
        Write-Summary "OK" "typst" "$version"
    } else {
        LogError "winget install completed but 'typst' not found in PATH"
        Write-Summary "ERROR" "typst" "install failed (not on PATH)"
    }
}

# --- Exit ---
if ($errors -gt 0) {
    Log "FAILED with $errors error(s). See log: $logFile" "error"
    exit 1
} elseif ($warnings -gt 0) {
    Log "COMPLETED with $warnings warning(s)" "warn"
    exit 0
} else {
    Log "COMPLETED successfully" "ok"
    exit 0
}
