#!/usr/bin/env bash
# Generated by scripts/build-deploy.sh — do not edit directly.
# setup-user-cursor.sh — Sets up Cursor CLI + dependencies on macOS/Linux
# Self-contained: User Rules content is embedded below. No repo or Drive needed.
# Safe to re-run — checks each step and skips what's already done.
#
# Does four things:
#   1. Installs ripgrep (rg) if not already present (required by Cursor CLI)
#   2. Installs Cursor CLI (agent command) if not already present
#   3. Writes ~/.cursor/cli-config.json (skips if already up to date)
#   4. Copies embedded User Rules to clipboard for pasting into Cursor Settings > Rules

set -euo pipefail

# --- Logging ---
LOG_DIR="$HOME/Library/Logs"
[ "$(uname -s)" != "Darwin" ] && LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/ai-tooling"
LOG_FILE="$LOG_DIR/ai-tooling-deploy.log"
SCRIPT_NAME="setup-user-cursor"
ERRORS=0

mkdir -p "$LOG_DIR"

log()       { printf '[%s] [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%S)" "$SCRIPT_NAME" "$1" | tee -a "$LOG_FILE"; }
log_ok()    { log "OK: $1"; }
log_error() { log "ERROR: $1"; ERRORS=$((ERRORS + 1)); }

CURSOR_DIR="$HOME/.cursor"
CLI_CONFIG="$CURSOR_DIR/cli-config.json"

# --- 1. ripgrep (rg) ---
log "Step 1: ripgrep (rg)"

if command -v rg &>/dev/null; then
    RG_VERSION=$(rg --version | head -1)
    log_ok "Already installed: $RG_VERSION"
else
    if command -v brew &>/dev/null; then
        log "Installing ripgrep via brew..."
        brew install ripgrep
        if command -v rg &>/dev/null; then
            log_ok "Installed: $(rg --version | head -1)"
        else
            log_error "brew install completed but 'rg' not found in PATH"
        fi
    else
        log_error "Homebrew not found. Install ripgrep manually: brew install ripgrep"
    fi
fi

# --- 2. Cursor CLI (agent) ---
log "Step 2: Cursor CLI (agent)"

if command -v agent &>/dev/null; then
    AGENT_VERSION=$(agent --version)
    log_ok "Already installed: $AGENT_VERSION"
else
    log "Installing Cursor CLI..."
    curl https://cursor.com/install -fsS | bash
    if command -v agent &>/dev/null; then
        log_ok "Installed: $(agent --version)"
    else
        log_error "Cursor CLI install completed but 'agent' not found in PATH (restart terminal)"
    fi
fi

# --- 3. cli-config.json ---
log "Step 3: cli-config.json"

EXPECTED_CONFIG='{
  "version": 1,
  "editor": {
    "vimMode": false
  },
  "permissions": {
    "allow": [],
    "deny": []
  }
}'

mkdir -p "$CURSOR_DIR"

if [ -f "$CLI_CONFIG" ]; then
    EXISTING_CONFIG=$(cat "$CLI_CONFIG")
    if [ "$EXISTING_CONFIG" = "$EXPECTED_CONFIG" ]; then
        log_ok "Already up to date: $CLI_CONFIG"
    else
        printf '%s' "$EXPECTED_CONFIG" > "$CLI_CONFIG"
        log_ok "Updated: $CLI_CONFIG"
    fi
else
    printf '%s' "$EXPECTED_CONFIG" > "$CLI_CONFIG"
    log_ok "Created: $CLI_CONFIG"
fi

# --- 4. User Rules ---
log "Step 4: User Rules (embedded)"

# --- Embedded User Rules (from shared/cursor-rules/user-rules.md) ---
read -r -d "" USER_RULES_CONTENT <<'__EMBEDDED_USER_RULES__' || true
# Cursor User Rules

**How to apply:** Copy everything below the `---` line and paste it into
**Cursor Settings > Rules** on each machine.

Source of truth: `shared/cursor-rules/user-rules.md` in the ai-tooling repo.
The `setup-user-cursor` script copies this to your clipboard automatically.

---

## Identity

- Name: Jose
- Git: `Jose <jose@nobul.tech>`
- Company: Nobul

## Code Style Defaults

- Prefer simple, minimal solutions over clever abstractions
- Use type hints in Python; use TypeScript over plain JS
- Favor standard library over third-party when the gap is small
- Write CLI tools with `--help` support

## Cross-Platform Awareness

- I work on both Windows 11 and macOS — both are first-class
- Use forward slashes and `$HOME`/`~` in path references when possible
- Projects live in git repos under `~/repos/` (macOS) / `C:\repos\` (Windows)
- Some legacy projects still on Google Drive (`G:\My Drive\` / `~/Google Drive/My Drive/`) — migrate to git repos over time

## Git Conventions

- Always set local git identity (`Jose <jose@nobul.tech>`) before first commit in a new repo
- Commit messages: imperative mood, concise
- Branch naming: `feature/`, `fix/`, `docs/` prefixes

## Communication Style

- Be concise — skip filler and caveats
- Explain the "why" behind non-obvious decisions
- Don't add docstrings, comments, or type annotations to code you didn't change
__EMBEDDED_USER_RULES__

if command -v pbcopy &>/dev/null; then
    printf '%s' "$USER_RULES_CONTENT" | pbcopy
    log_ok "Copied User Rules to clipboard"
elif command -v xclip &>/dev/null; then
    printf '%s' "$USER_RULES_CONTENT" | xclip -selection clipboard
    log_ok "Copied User Rules to clipboard (xclip)"
else
    log_error "No clipboard command found (pbcopy/xclip). Copy manually from log."
fi

log "Paste User Rules into: Cursor Settings > Rules"

# --- Exit ---
if [ "$ERRORS" -gt 0 ]; then
    log "FAILED with $ERRORS error(s). See log: $LOG_FILE"
    exit 1
else
    log "COMPLETED successfully"
    exit 0
fi
