#!/usr/bin/env bash
# Generated by scripts/build-deploy.sh — do not edit directly.
set -euo pipefail

# --- Flag parsing ---
DRY_RUN=false
FORCE=false
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --force)   FORCE=true ;;
    esac
done
[ "${AITOOLS_DRY_RUN:-}" = "1" ] && DRY_RUN=true

# --- Shared library ---
# aitools-lib.sh -- shared helpers for all aitools bash scripts
# Sourced, not executed directly. No shebang, no set -euo pipefail (caller sets it).
#
# Provides: platform detection, display_path, read_config_key, logging_init,
# log/log_ok/log_error/log_warn, write_summary, show_summary,
# SORT_KEYS_JS, normalize_json.
#
# Usage:
#   source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/aitools-lib.sh"
#   logging_init "script-name"
#
# Entry points (aitools, aitools-install) override log functions after sourcing
# for specialized logging (file-only, JSONL, etc.).

# ---------------------------------------------------------------------------
# Platform detection
# ---------------------------------------------------------------------------
IS_MACOS=false
IS_WINDOWS=false
case "$(uname -s)" in
    Darwin*)              IS_MACOS=true ;;
    MINGW*|MSYS*|CYGWIN*) IS_WINDOWS=true ;;
esac

# ---------------------------------------------------------------------------
# Log directory (platform-aware)
# ---------------------------------------------------------------------------
AITOOLS_LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/aitools"
$IS_MACOS && AITOOLS_LOG_DIR="$HOME/Library/Logs/aitools"

# ---------------------------------------------------------------------------
# Module-level counters (safe for sourcing without logging_init under set -u)
# ---------------------------------------------------------------------------
ERRORS=0
WARNINGS=0

# ---------------------------------------------------------------------------
# Display-friendly path (native Windows on MSYS, no-op elsewhere)
# ---------------------------------------------------------------------------
display_path() {
    if command -v cygpath &>/dev/null; then
        cygpath -w "$1"
    else
        printf '%s' "$1"
    fi
}

# ---------------------------------------------------------------------------
# Config reader (pure bash, handles UTF-8 BOM)
# ---------------------------------------------------------------------------
# Read a top-level string value from a JSON config file.
# Handles UTF-8 BOM (PowerShell 5.x writes one) and JSON-escaped backslashes.
read_config_key() {
    local file="$1" key="$2"
    [ -f "$file" ] || return 1
    local val
    val=$(tr -d '\357\273\277' < "$file" \
        | grep -o "\"$key\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
        | head -1 \
        | cut -d'"' -f4)
    [ -n "$val" ] || return 1
    # Unescape JSON backslashes: \\ -> \
    printf '%b' "$val"
}

# ---------------------------------------------------------------------------
# Logging init
# ---------------------------------------------------------------------------
# Sets SCRIPT_NAME, LOG_DIR, LOG_FILE; resets ERRORS, WARNINGS; creates log dir.
# Usage: logging_init "setup-foo"
logging_init() {
    SCRIPT_NAME="${1:?logging_init requires a script name}"
    LOG_DIR="$AITOOLS_LOG_DIR"
    LOG_FILE="$LOG_DIR/deploy.log"
    mkdir -p "$LOG_DIR"
    ERRORS=0
    WARNINGS=0
}

# ---------------------------------------------------------------------------
# Standard logging (Pattern A: console + log file, with [level] tag)
# ---------------------------------------------------------------------------
log() {
    local level="${2:-info}"
    local ts; ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    local line="[$ts] [$SCRIPT_NAME] [$level] $1"
    printf '%s\n' "$line" >> "$LOG_FILE"
    case "$level" in
        error) printf '\033[31m%s\033[0m\n' "$line" ;;
        warn)  printf '\033[33m%s\033[0m\n' "$line" ;;
        *)     printf '%s\n' "$line" ;;
    esac
}
log_ok()    { log "$1" "ok"; }
log_error() { log "$1" "error"; ERRORS=$((ERRORS + 1)); }
log_warn()  { log "$1" "warn"; WARNINGS=$((WARNINGS + 1)); }

# ---------------------------------------------------------------------------
# Summary writer (3-arg: category, tool, detail)
# ---------------------------------------------------------------------------
write_summary() {
    if [ -n "${AITOOLS_SUMMARY_FILE:-}" ]; then
        local cat="$1"
        # Auto-promote OK to WARN when warnings have been logged
        if [ "$cat" = "OK" ] && [ "${WARNINGS:-0}" -gt 0 ]; then
            cat="WARN"
        fi
        printf '%s|%s|%s\n' "$cat" "$2" "$3" >> "$AITOOLS_SUMMARY_FILE"
    fi
}

# ---------------------------------------------------------------------------
# Backup a file before overwriting. Keeps at most $max_backups copies.
# ---------------------------------------------------------------------------
backup_file() {
    local file="$1" max_backups=20
    [ -f "$file" ] || return 0
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    cp "$file" "${file}.bak.${ts}"
    # Prune oldest beyond limit
    ls -1t "${file}.bak."* 2>/dev/null | tail -n +$((max_backups + 1)) | xargs rm -f 2>/dev/null
    log "Backed up $(display_path "$file")"
}

# ---------------------------------------------------------------------------
# Backup a directory before modifying managed files. Keeps at most $max_backups copies.
# ---------------------------------------------------------------------------
backup_dir() {
    local dir="$1" max_backups=5
    [ -d "$dir" ] || return 0
    local file_count
    file_count=$(find "$dir" -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')
    if [ "$file_count" -eq 0 ]; then
        return 0
    fi
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    if ! cp -R "$dir" "${dir}.bak.${ts}"; then
        log_warn "Could not back up $(display_path "$dir") -- proceeding without backup"
        return 0
    fi
    local old_backups
    old_backups=$(find "$(dirname "$dir")" -maxdepth 1 -name "$(basename "$dir").bak.*" -type d \
        | sort -r | tail -n +$((max_backups + 1)))
    if [ -n "$old_backups" ]; then
        printf '%s\n' "$old_backups" | while IFS= read -r old_dir; do
            rm -rf "$old_dir"
            log "Pruned old backup: $(display_path "$old_dir")"
        done
    fi
    log "Backed up $(display_path "$dir") ($file_count managed files)"
}

# ---------------------------------------------------------------------------
# Prompt user before overwriting a managed file with different content.
# Shows a unified diff and offers: Adopt / Overwrite / Skip / Abort.
#
# Args:
#   $1 = file path (deployed file on disk)
#   $2 = new content that would be written (from source template)
#   $3 = adopt target label (e.g., "profile", "shared/") or "" to hide adopt
#
# Sets global DIFF_REVIEW_RESULT to: "overwrite", "adopt", or "skip"
# Exits with code 2 on abort.
# Non-interactive / --force: sets "overwrite" and returns.
# ---------------------------------------------------------------------------
DIFF_REVIEW_RESULT=""
prompt_diff_review() {
    local file_path="$1"
    local new_content="$2"
    local adopt_label="${3:-}"

    DIFF_REVIEW_RESULT="overwrite"

    # --force or AITOOLS_FORCE: auto-overwrite
    if [ "${AITOOLS_FORCE:-}" = "1" ] || [ "${FORCE:-}" = "true" ]; then
        log_warn "Diff in $(display_path "$file_path") -- overwriting (--force)"
        return 0
    fi

    # Non-interactive: auto-overwrite (preserves current behavior).
    # [ -c /dev/tty ] is insufficient -- macOS reports the device exists even
    # when no controlling terminal is attached ("Device not configured").
    # Test with an actual write to catch both cases.
    if ! (printf '' > /dev/tty) 2>/dev/null; then
        log_warn "Diff in $(display_path "$file_path") -- overwriting (non-interactive)"
        return 0
    fi

    # Show diff via /dev/tty (bypasses stdout/stderr redirection in deploy_configs)
    printf '\n\033[33m[REVIEW]\033[0m %s differs from source.\n' \
        "$(display_path "$file_path")" > /dev/tty
    local diff_output
    # diff exits 1 on differences (expected), suppress set -e abort
    diff_output=$(diff -u <(printf '%s' "$new_content") "$file_path" \
        --label "source (would deploy)" --label "current (on disk)" 2>&1) || true
    local diff_lines
    diff_lines=$(printf '%s\n' "$diff_output" | wc -l | tr -d ' ')
    if [ "$diff_lines" -le 40 ]; then
        printf '%s\n' "$diff_output" > /dev/tty
    else
        printf '%s\n' "$diff_output" | head -30 > /dev/tty
        printf '  ... (%d more lines -- full diff in deploy log)\n' \
            "$((diff_lines - 30))" > /dev/tty
        printf '%s\n' "$diff_output" >> "${LOG_FILE:-/dev/null}"
    fi

    # Build prompt with conditional adopt option
    printf '\n' > /dev/tty
    if [ -n "$adopt_label" ]; then
        printf '  [A]dopt to %s  [O]verwrite (backup kept)  [S]kip  [X] Abort\n' \
            "$adopt_label" > /dev/tty
        printf '  Choice [A/O/s/x]: ' > /dev/tty
    else
        printf '  [O]verwrite (backup kept)  [S]kip  [X] Abort\n' > /dev/tty
        printf '  Choice [O/s/x]: ' > /dev/tty
    fi
    local choice
    read -r choice < /dev/tty
    case "$(printf '%s' "$choice" | tr '[:upper:]' '[:lower:]')" in
        a)  if [ -n "$adopt_label" ]; then
                DIFF_REVIEW_RESULT="adopt"
            else
                DIFF_REVIEW_RESULT="overwrite"
            fi ;;
        s)  DIFF_REVIEW_RESULT="skip" ;;
        x)  log_error "Aborted by user"
            exit 2 ;;
        *)  DIFF_REVIEW_RESULT="overwrite" ;;
    esac
    return 0
}

# ---------------------------------------------------------------------------
# Repair broken uv tool environment (cross-platform)
# ---------------------------------------------------------------------------
# When `uv tool upgrade <tool>` fails with "missing a valid environment",
# find a working Python via `uv python find` (fallback: system python/python3)
# and reinstall with --force --python <path>.
# Returns 0 if repaired, 1 if not applicable or failed.
repair_uv_tool_env() {
    local tool_name="$1"
    local upgrade_output="${2:-}"

    if ! printf '%s\n' "$upgrade_output" | grep -q 'missing a valid environment'; then
        return 1
    fi

    log_warn "$tool_name uv environment is broken (Python removed?) -- repairing..."

    # Find a working Python -- uv's own Pythons first, then system
    local working_python=""
    local uv_python
    uv_python=$(uv python find 2>/dev/null) || true
    if [ -n "$uv_python" ] && [ -x "$uv_python" ]; then
        working_python="$uv_python"
    elif command -v python3 >/dev/null 2>&1; then
        working_python=$(command -v python3)
    elif command -v python >/dev/null 2>&1; then
        working_python=$(command -v python)
    fi

    if [ -z "$working_python" ]; then
        log_error "Cannot repair $tool_name -- no working Python found"
        return 1
    fi

    log "Repairing with: uv tool install --force --python $working_python $tool_name"
    local repair_output
    repair_output=$(uv tool install --force --python "$working_python" "$tool_name" 2>&1) || true
    printf '%s\n' "$repair_output" | while IFS= read -r line; do
        [ -n "$line" ] && log "$line"
    done

    if printf '%s\n' "$repair_output" | grep -qi 'error.*failed'; then
        log_error "$tool_name environment repair failed"
        return 1
    fi

    log_ok "Repaired $tool_name uv environment"
    return 0
}

# ---------------------------------------------------------------------------
# Parse CHANGED: lines from a node merge result and emit DETAIL summary entries.
# Usage: emit_merge_details "$MERGE_RESULT" "tool_name"
# Only processes lines prefixed with "CHANGED: " -- ignores status and other output.
# ---------------------------------------------------------------------------
emit_merge_details() {
    local merge_result="$1" tool_name="$2"
    local changed_keys
    changed_keys=$(echo "$merge_result" | perl -ne 'print if s/^CHANGED: //')
    if [ -n "$changed_keys" ]; then
        while IFS= read -r key_change; do
            log "  $key_change"
            write_summary DETAIL "$tool_name" "$key_change"
        done <<< "$changed_keys"
    fi
}

# ---------------------------------------------------------------------------
# JSON normalization for comparison (sorted keys, deterministic output)
# ---------------------------------------------------------------------------
# JavaScript JSON.stringify preserves insertion order, which may differ
# between runs or between PS1/bash variants writing the same file. Sorting
# keys before comparison ensures identical content produces identical JSON.
#
# SORT_KEYS_JS: minified sortKeys function for embedding in node -e blocks.
#   Usage: node -e "$SORT_KEYS_JS; ..."
#
# normalize_json: pipe-based wrapper for standalone use.
#   Usage: NORMALIZED=$(echo "$json_string" | normalize_json)
SORT_KEYS_JS='function sortKeys(o){if(o===null||typeof o!=="object")return o;if(Array.isArray(o))return o.map(sortKeys);var s={};Object.keys(o).sort().forEach(function(k){s[k]=sortKeys(o[k])});return s}'

normalize_json() {
    node -e "
        var input = require('fs').readFileSync('/dev/stdin', 'utf8');
        $SORT_KEYS_JS
        try {
            console.log(JSON.stringify(sortKeys(JSON.parse(input)), null, 2));
        } catch(e) {
            process.stderr.write('normalize_json: ' + e.message + '\n');
            process.exit(1);
        }
    "
}

# ---------------------------------------------------------------------------
# Go install provenance detection (macOS)
# Returns: "homebrew", "pkg-installer", "goenv", "manual", "none", or "unknown"
# ---------------------------------------------------------------------------
detect_go_provenance() {
    local go_path
    go_path=$(command -v go 2>/dev/null) || { echo "none"; return; }
    case "$go_path" in
        /opt/homebrew/*/go|/usr/local/Cellar/*/go)
            echo "homebrew" ;;
        /usr/local/go/bin/go)
            # Check if installed via macOS .pkg installer (pkgutil) or manual tarball
            if pkgutil --pkg-info=org.golang.go >/dev/null 2>&1; then
                echo "pkg-installer"
            else
                echo "manual"
            fi ;;
        */.goenv/*)
            echo "goenv" ;;
        *)
            echo "unknown" ;;
    esac
}

# ---------------------------------------------------------------------------
# Ensure GOPATH/bin is on PATH for current session
# Returns 0 if already on PATH, 1 if added (caller should warn re persistence)
# ---------------------------------------------------------------------------
ensure_gopath_bin_on_path() {
    local gopath_bin="${GOPATH:-$HOME/go}/bin"
    case ":$PATH:" in
        *":$gopath_bin:"*) return 0 ;;
    esac
    export PATH="$gopath_bin:$PATH"
    return 1
}

# ---------------------------------------------------------------------------
# Summary panel renderer
# ---------------------------------------------------------------------------
# Reads AITOOLS_SUMMARY_FILE, displays colored panel, cleans up.
# Silent no-op if file unset, missing, or empty.
show_summary() {
    local sfile="${AITOOLS_SUMMARY_FILE:-}"
    [ -n "$sfile" ] || return 0
    [ -f "$sfile" ] || return 0
    [ -s "$sfile" ] || { rm -f "$sfile"; return 0; }

    # Dedup by tool name: highest severity wins (ERROR > WARN > OK).
    # ACTIONs (empty tool name) are never deduped. DETAIL lines collected separately.
    # Output is pre-sorted: OK+details, WARN+details, ERROR+details, ACTIONs.
    local deduped
    deduped=$(perl -F'\|' -lane '
        BEGIN { %rank = (OK => 1, WARN => 2, ERROR => 3); }
        $cat = $F[0]; $tool = $F[1]; $det = join("|", @F[2..$#F]);
        if ($cat eq "DETAIL") {
            push @{$details{$tool}}, $det; next;
        }
        if ($cat eq "ACTION" || $tool eq "") {
            push @actions, $_; next;
        }
        $r = $rank{$cat} // 0;
        if (!exists $best{$tool}) {
            push @order, $tool;
            $best{$tool} = $cat; $detail{$tool} = $det;
        } elsif ($r > ($rank{$best{$tool}} // 0)) {
            $best{$tool} = $cat; $detail{$tool} = $det;
        }
        END {
            my (@ok, @warn, @err);
            for my $t (@order) {
                my @g = ("$best{$t}|$t|$detail{$t}",
                         map { "DETAIL|$t|$_" } @{$details{$t} // []});
                if    ($best{$t} eq "OK")    { push @ok,   @g }
                elsif ($best{$t} eq "WARN")  { push @warn, @g }
                elsif ($best{$t} eq "ERROR") { push @err,  @g }
            }
            print for @ok, @warn, @err, @actions;
        }
    ' "$sfile")

    # Single-pass display: Perl output is pre-sorted by severity.
    # DETAIL lines inherit the color of their preceding parent entry.
    echo ""
    echo "────────────────────────────────────────────────────────"
    local last_color="" first_action=true
    while IFS='|' read -r cat tool detail; do
        case "$cat" in
            OK)
                last_color='\033[32m'
                printf '\033[32m  [ok]  %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            WARN)
                last_color='\033[33m'
                printf '\033[33m  [!]   %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            ERROR)
                last_color='\033[31m'
                printf '\033[31m  [ERR] %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            DETAIL)
                printf '%b                          %s\033[0m\n' "$last_color" "$detail"
                ;;
            ACTION)
                if [ "$first_action" = true ]; then
                    echo ""
                    printf '\033[1;35m  ACTION REQUIRED -- run before tools are ready:\033[0m\n'
                    first_action=false
                fi
                printf '\033[1;35m  >>  %s\033[0m\n' "$detail"
                ;;
        esac
    done <<< "$deduped"
    echo "────────────────────────────────────────────────────────"

    # Preserve summary for log compliance checks
    if [ "${AITOOLS_PRESERVE_SUMMARY:-}" = "1" ]; then
        # cp may fail if log dir was cleaned up; non-blocking (summary already displayed)
        if ! cp "$sfile" "$LOG_DIR/last-summary.txt" 2>/dev/null; then
            printf 'warning: could not preserve summary file\n' >&2
        fi
    fi
    # Cleanup summary file (already displayed; rm -f ignores nonexistent files)
    rm -f "$sfile"
}

# ---------------------------------------------------------------------------
# Build prerequisite checking
# ---------------------------------------------------------------------------

# Check known build prerequisites for an ecosystem.
# Usage: check_build_prereqs "cargo"
#   Outputs missing prereq info to stdout (one per line: NAME|INSTALL_INSTRUCTION).
#   Returns 0 if all present, 1 if any missing.
check_build_prereqs() {
    local ecosystem="$1"
    local missing=0

    case "$ecosystem" in
        cargo)
            # NASM -- required by aws-lc-sys on x86_64
            if [ "$(uname -m)" = "x86_64" ] && ! command -v nasm >/dev/null 2>&1; then
                echo "NASM|brew install nasm (macOS) or apt-get install nasm (Linux)"
                missing=1
            fi
            # cmake -- required by some crates
            if ! command -v cmake >/dev/null 2>&1; then
                echo "CMake|brew install cmake (macOS) or apt-get install cmake (Linux)"
                missing=1
            fi
            ;;
        pip)
            # Add pip-specific prereqs here as discovered
            ;;
        go)
            # Add go-specific prereqs here as discovered
            ;;
    esac

    return $missing
}

# ---------------------------------------------------------------------------
# Build failure diagnosis
# ---------------------------------------------------------------------------

# Scan build output for known failure signatures.
# Usage: diagnose_build_failure "$output"
#   Prints "NAME|REMEDY" if a known signature is found.
#   Returns 0 if found, 1 if no match.
diagnose_build_failure() {
    local output="$1"

    # Table of known failure patterns -> remediation
    # Add new entries here when new build failures are discovered.
    local -a patterns=(
        "NASM command not found|NASM|brew install nasm / apt-get install nasm"
        "linker.*not found|Linker|Install build-essential (Linux) or Xcode CLI tools (macOS)"
        "cmake.*not found|CMake|brew install cmake / apt-get install cmake"
        "pkg-config.*not found|pkg-config|brew install pkg-config / apt-get install pkg-config"
        "Python\.h.*not found|Python headers|Install python3-dev or python3-devel"
        "openssl.*not found|OpenSSL|brew install openssl / apt-get install libssl-dev"
    )

    for entry in "${patterns[@]}"; do
        local pattern="${entry%%|*}"
        local rest="${entry#*|}"
        if printf '%s\n' "$output" | grep -qiE "$pattern"; then
            echo "$rest"
            return 0
        fi
    done
    return 1
}
logging_init "setup-user-mcp"

# --- OS guard ---
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        log_error "This script is for macOS/Linux. On Windows, use ${SCRIPT_NAME}.ps1 instead."
        exit 1 ;;
esac

[ "$DRY_RUN" = "true" ] && log "[DRY RUN] Preview mode -- no files will be written"

# Check that claude CLI is available
if ! command -v claude &> /dev/null; then
    log_error "'claude' CLI not found in PATH. Install Claude Code first: https://claude.ai/download"
    exit 1
fi

# Check that Node.js is available (required for Chrome DevTools MCP and settings merge)
if ! command -v node &> /dev/null; then
    log_error "Node.js not found. Install via 'aitools install' or manually: https://nodejs.org"
    exit 1
else
    log_ok "Node.js $(node --version) found"
fi

# --- Check existing MCP server configs via claude mcp list ---
# Stores parsed output as newline-separated "name=details" pairs.
# Avoids bash 4+ associative arrays for macOS compatibility (bash 3.2).
mcp_current_data=""
mcp_current_count=0

saved_claudecode="${CLAUDECODE:-}"
unset CLAUDECODE

mcp_list_rc=0
mcp_list_output=$(claude mcp list 2>/dev/null) || mcp_list_rc=$?

if [ -n "$saved_claudecode" ]; then
    export CLAUDECODE="$saved_claudecode"
fi

if [ $mcp_list_rc -eq 0 ] && [ -n "$mcp_list_output" ]; then
    mcp_current_data=$(printf '%s\n' "$mcp_list_output" | perl -ne '
        s/\e\[[0-9;]*m//g;
        next unless /^(.+?):\s+(.+)\s+-\s+.+$/;
        my ($name, $details) = ($1, $2);
        $details =~ s/\s+\(HTTP\)$//;
        $details =~ s/\s+$//;
        print "$name=$details\n";
    ')
    if [ -n "$mcp_current_data" ]; then
        mcp_current_count=$(printf '%s\n' "$mcp_current_data" | wc -l | tr -d ' ')
    fi
    log_ok "Checked existing MCP config ($mcp_current_count servers found)"
else
    log_warn "Could not check existing MCP config; will re-add all servers"
fi

# Check if a server's current config matches expected.
server_config_matches() {
    local name="$1" expected="$2"
    [ -n "$mcp_current_data" ] || return 1
    local line
    line=$(printf '%s\n' "$mcp_current_data" | grep "^${name}=" | head -1 || true)
    [ -n "$line" ] || return 1
    local current="${line#*=}"
    [ "$current" = "$expected" ]
}

# --- Add all three MCP servers at user scope ---

add_mcp_server() {
    local name="$1"
    shift

    # Unset CLAUDECODE to allow running inside a Claude Code session
    local saved_claudecode="${CLAUDECODE:-}"
    unset CLAUDECODE

    # Remove existing (ignore errors if not found)
    if claude mcp remove "$name" --scope user 2>/dev/null; then
        log "Removed existing $name config"
    fi

    log "Adding $name..."
    if claude mcp add "$@"; then
        log_ok "$name configured"
        MCP_CHANGED=true
    else
        log_error "Failed to add $name"
        write_summary ERROR "claude mcp" "failed to add $name"
    fi

    # Restore CLAUDECODE
    if [ -n "$saved_claudecode" ]; then
        export CLAUDECODE="$saved_claudecode"
    fi
}

MCP_CHANGED=false
log "Setting up MCP servers for Claude Code (user scope)..."

# Chrome DevTools — local stdio server via npx
if [ "$FORCE" = "true" ]; then
    if [ "$DRY_RUN" = "true" ]; then
        log "[DRY RUN] Would re-add MCP server: chrome-devtools (--force)"
    else
        add_mcp_server "chrome-devtools" chrome-devtools --scope user -- npx chrome-devtools-mcp@latest --isolated
    fi
elif server_config_matches "chrome-devtools" "npx chrome-devtools-mcp@latest --isolated"; then
    log_ok "chrome-devtools already configured, skipping (use --force to re-add)"
else
    if [ "$DRY_RUN" = "true" ]; then
        log "[DRY RUN] Would add MCP server: chrome-devtools (stdio, --isolated)"
    else
        add_mcp_server "chrome-devtools" chrome-devtools --scope user -- npx chrome-devtools-mcp@latest --isolated
    fi
fi

# Vercel — remote HTTP server (disabled by default via deny rules below)
if [ "$FORCE" = "true" ]; then
    if [ "$DRY_RUN" = "true" ]; then
        log "[DRY RUN] Would re-add MCP server: vercel (--force)"
    else
        add_mcp_server "vercel" --transport http --scope user vercel https://mcp.vercel.com
    fi
elif server_config_matches "vercel" "https://mcp.vercel.com"; then
    log_ok "vercel already configured, skipping (use --force to re-add)"
else
    if [ "$DRY_RUN" = "true" ]; then
        log "[DRY RUN] Would add MCP server: vercel (http)"
    else
        add_mcp_server "vercel" --transport http --scope user vercel https://mcp.vercel.com
    fi
fi

# Webflow — remote HTTP server (disabled by default via deny rules below)
if [ "$FORCE" = "true" ]; then
    if [ "$DRY_RUN" = "true" ]; then
        log "[DRY RUN] Would re-add MCP server: webflow (--force)"
    else
        add_mcp_server "webflow" --transport http --scope user webflow https://mcp.webflow.com/mcp
    fi
elif server_config_matches "webflow" "https://mcp.webflow.com/mcp"; then
    log_ok "webflow already configured, skipping (use --force to re-add)"
else
    if [ "$DRY_RUN" = "true" ]; then
        log "[DRY RUN] Would add MCP server: webflow (http)"
    else
        add_mcp_server "webflow" --transport http --scope user webflow https://mcp.webflow.com/mcp
    fi
fi

# --- Merge deny rules into ~/.claude/settings.json ---
# Vercel and Webflow are disabled by default at user level.
# Projects enable them via .claude/settings.local.json (aitools --addmcp).

settings_file="$HOME/.claude/settings.json"
if [ "$DRY_RUN" != "true" ]; then
    backup_file "$settings_file"
fi
log "Merging deny rules into $(display_path "$settings_file")..."

DENY_RESULT=$(node -e "
$SORT_KEYS_JS
const fs = require('fs');
const path = require('path');
const f = process.argv[1];
const dryRun = process.argv[2] === 'true';
const force = process.argv[3] === 'true';
const dir = path.dirname(f);

// Ensure directory exists
if (!dryRun && !fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

// Read existing settings
let settings = {};
let corrupt = false;
try {
    settings = JSON.parse(fs.readFileSync(f, 'utf8'));
} catch (e) {
    if (e.code !== 'ENOENT') {
        corrupt = true;
        console.error('Warning: ' + f + ' is invalid JSON');
    }
}
const beforeKeys = Object.keys(settings);

// Ensure permissions.deny exists
if (!settings.permissions) settings.permissions = {};
if (!Array.isArray(settings.permissions.deny)) settings.permissions.deny = [];

// Add deny rules if not already present
const denyRules = ['MCP(vercel)', 'MCP(webflow)'];
for (const rule of denyRules) {
    if (!settings.permissions.deny.includes(rule)) {
        settings.permissions.deny.push(rule);
    }
}

// Clobber detection
const managedKeys = ['permissions'];
const afterKeys = Object.keys(settings);
const lostKeys = beforeKeys.filter(k => !afterKeys.includes(k));

if (dryRun) {
    console.error('[DRY RUN] ' + f + ': merge deny rules');
    console.error('  Managed fields: permissions.deny');
    if (lostKeys.length > 0) console.error('  CLOBBER WARNING: would lose: ' + lostKeys.join(', '));
    if (corrupt) console.error('  File is corrupt -- --force required');
    console.log('dry-run');
} else if (corrupt && !force) {
    console.error('ERROR: ' + f + ' is corrupt. Use --force to overwrite, or fix manually.');
    console.log('error-corrupt');
} else if (lostKeys.length > 0 && !force) {
    console.error('ERROR: merge would lose fields: ' + lostKeys.join(', ') + '. Use --force to proceed.');
    console.log('error-clobber');
} else {
    if (corrupt) console.error('Warning: proceeding with --force on corrupt file');
    if (lostKeys.length > 0) console.error('Warning: proceeding with --force, losing fields: ' + lostKeys.join(', '));
    const newJson = JSON.stringify(sortKeys(settings), null, 2) + '\n';
    let existingJson = '';
    try { existingJson = fs.readFileSync(f, 'utf8'); } catch(e) { /* may not exist yet */ }
    const mergedNorm = JSON.stringify(sortKeys(settings));
    const existingNorm = existingJson ? JSON.stringify(sortKeys(JSON.parse(existingJson))) : '';
    if (!corrupt && lostKeys.length === 0 && mergedNorm === existingNorm) {
        console.log('unchanged');
    } else {
        fs.writeFileSync(f, newJson);

        // Post-write validation
        const _v = JSON.parse(fs.readFileSync(f, 'utf8'));
        if (!_v.permissions) { console.error('Validation failed: missing permissions'); process.exit(1); }
        console.log('ok');
    }
}
" "$settings_file" "$DRY_RUN" "$FORCE")

case "$DENY_RESULT" in
    unchanged)
        log_ok "Deny rules unchanged in $(display_path "$settings_file")" ;;
    ok)
        log_ok "Deny rules set for vercel, webflow in $(display_path "$settings_file")"
        MCP_CHANGED=true ;;
    dry-run)
        log "[DRY RUN] Would set deny rules for vercel, webflow" ;;
    error-corrupt)
        log_error "$(display_path "$settings_file") is corrupt. Use --force to overwrite."
        write_summary ERROR "claude mcp" "settings corrupt" ;;
    error-clobber)
        log_error "$(display_path "$settings_file") merge would lose fields. Use --force to proceed."
        write_summary ERROR "claude mcp" "merge would lose fields" ;;
    *)
        log_error "Unexpected deny merge result: $DENY_RESULT"
        write_summary ERROR "claude mcp" "unexpected error" ;;
esac

if [ "$DRY_RUN" != "true" ]; then
    log_ok "User-level MCP configured (all servers; vercel/webflow disabled by default)"
    if [ "$ERRORS" -eq 0 ]; then
        if [ "$MCP_CHANGED" = "true" ]; then
            write_summary OK "claude mcp" "configured"
        else
            write_summary OK "claude mcp" "unchanged"
        fi
    fi
else
    log "[DRY RUN] Would configure user-level MCP (all servers; vercel/webflow disabled by default)"
fi
log "To enable per project: aitools --addmcp vercel"
log "To check status: aitools mcp"

# Display cloud MCP servers configured at claude.ai.
# Silent no-op if claude CLI unavailable or no cloud servers found.
show_cloud_mcp_status() {
    command -v claude &>/dev/null || return 0
    local saved_claudecode="${CLAUDECODE:-}"
    unset CLAUDECODE
    local raw
    raw=$(claude mcp list 2>/dev/null) || true
    if [ -n "$saved_claudecode" ]; then export CLAUDECODE="$saved_claudecode"; fi
    [ -n "$raw" ] || return 0
    local parsed
    parsed=$(printf '%s\n' "$raw" | perl -ne '
        s/\e\[[0-9;]*m//g;
        next unless /^claude\.ai\s+(.+?):\s+.+\s+-\s+(.+)$/;
        my ($name, $status) = ($1, $2);
        $status =~ s/\s+$//;
        my $pad = length($name) < 24 ? " " x (24 - length($name)) : " ";
        printf "  %s%s%s\n", $name, $pad, $status;
    ')
    [ -n "$parsed" ] || return 0
    log "Cloud MCP servers (configured at claude.ai):"
    while IFS= read -r line; do
        log "$line"
    done <<< "$parsed"
}

# --- Deploy Chrome DevTools skills (embedded) ---
# Vendored from https://github.com/ChromeDevTools/chrome-devtools-mcp/tree/main/skills
# Content embedded at build time by build-deploy.sh for self-contained deployment.

SKILLS_DEST="$HOME/.claude/skills"
SKILLS_DEST_CURSOR="$HOME/.cursor/skills"
ALL_SKILL_DESTS="$SKILLS_DEST $SKILLS_DEST_CURSOR"

deploy_embedded_skill() {
    local skill_name="$1"
    local dest_base="$2"
    local tool_name="$3"
    local content_file="$4"

    local dest_dir="$dest_base/$skill_name"
    local dest="$dest_dir/SKILL.md"

    if [ "$DRY_RUN" = "true" ]; then
        log "[DRY RUN] Would deploy skill: $skill_name -> $(display_path "$dest")"
        return
    fi

    mkdir -p "$dest_dir"

    if [ -f "$dest" ]; then
        # diff -q: exits 0 if identical, 1 if different (expected, not an error)
        if diff -q "$content_file" "$dest" >/dev/null 2>&1; then
            log_ok "Skill unchanged: $skill_name"
            return
        fi
        # File differs -- backup and review
        backup_file "$dest"
        _adopt_label=""
        _repo_path=$(read_config_key "$HOME/.aitools/config.json" "repoPath")
        if [ -n "$_repo_path" ]; then
            _adopt_label="shared/"
        fi
        prompt_diff_review "$dest" "$(cat "$content_file")" "$_adopt_label"
        case "$DIFF_REVIEW_RESULT" in
            adopt)
                if [ -n "$_repo_path" ]; then
                    mkdir -p "$_repo_path/shared/skills/$skill_name"
                    cp "$dest" "$_repo_path/shared/skills/$skill_name/SKILL.md"
                    log_ok "Adopted skill to shared/: $skill_name"
                    write_summary DETAIL "$tool_name" "adopted: $skill_name"
                fi
                # Sync adopted content to all other deploy targets so
                # subsequent deploy loops see no diff (prevents clobber)
                for _other_base in $ALL_SKILL_DESTS; do
                    [ "$_other_base" = "$dest_base" ] && continue
                    mkdir -p "$_other_base/$skill_name"
                    cp "$dest" "$_other_base/$skill_name/SKILL.md"
                done
                return
                ;;
            skip)
                log_warn "Skill skipped: $skill_name"
                write_summary DETAIL "$tool_name" "skipped: $skill_name"
                return
                ;;
        esac
    fi
    # Write content (new file or overwrite after review)
    cp "$content_file" "$dest"
    log_ok "Deployed skill: $skill_name -> $(display_path "$dest")"
}

_skill_tmp=$(mktemp -d)
cat > "$_skill_tmp/chrome-devtools.md" <<'__SKILL_CHROME_DEVTOOLS__'
---
name: chrome-devtools
description: Uses Chrome DevTools via MCP for efficient debugging, troubleshooting and browser automation. Use when debugging web pages, automating browser interactions, analyzing performance, or inspecting network requests.
---

## Core Concepts

**Browser lifecycle**: Browser starts automatically on first tool call using a persistent Chrome profile. Configure via CLI args in the MCP server configuration: `npx chrome-devtools-mcp@latest --help`.

**Page selection**: Tools operate on the currently selected page. Use `list_pages` to see available pages, then `select_page` to switch context.

**Element interaction**: Use `take_snapshot` to get page structure with element `uid`s. Each element has a unique `uid` for interaction. If an element isn't found, take a fresh snapshot - the element may have been removed or the page changed.

## Workflow Patterns

### Before interacting with a page

1. Navigate: `navigate_page` or `new_page`
2. Wait: `wait_for` to ensure content is loaded if you know what you look for.
3. Snapshot: `take_snapshot` to understand page structure
4. Interact: Use element `uid`s from snapshot for `click`, `fill`, etc.

### Efficient data retrieval

- Use `filePath` parameter for large outputs (screenshots, snapshots, traces)
- Use pagination (`pageIdx`, `pageSize`) and filtering (`types`) to minimize data
- Set `includeSnapshot: false` on input actions unless you need updated page state

### Tool selection

- **Automation/interaction**: `take_snapshot` (text-based, faster, better for automation)
- **Visual inspection**: `take_screenshot` (when user needs to see visual state)
- **Additional details**: `evaluate_script` for data not in accessibility tree

### Expanding accordions, tabs, and FAQs

Many pages use JS-rendered accordions/tabs (e.g., FAQ sections) whose content is hidden until clicked. The a11y tree shows them as `tab` or `button` elements with `expandable` state but no inner content until expanded.

**Pattern:**
1. `take_snapshot` — identify the collapsed elements (look for `tab`/`button` with `expandable` but NOT `expanded`)
2. `click` on the element `uid` to expand it
3. `take_snapshot` again — the expanded content now appears inline in the tab/button's accessible name or as child nodes
4. Repeat for each accordion item

**Tips:**
- Only one accordion panel may be open at a time (clicking the next may collapse the previous) — snapshot after each click
- The expanded content often appears directly in the element's accessible name text, not as separate child nodes
- Save each snapshot to `filePath` to avoid flooding context when extracting large amounts of content
- If clicking doesn't expand (some require user interaction), ask the user to expand manually, then snapshot

### Parallel execution

You can send multiple tool calls in parallel, but maintain correct order: navigate → wait → snapshot → interact.

## Troubleshooting

If `chrome-devtools-mcp` is insufficient, guide users to use Chrome DevTools UI:

- https://developer.chrome.com/docs/devtools
- https://developer.chrome.com/docs/devtools/ai-assistance

If there are errors launching `chrome-devtools-mcp` or Chrome, refer to https://github.com/ChromeDevTools/chrome-devtools-mcp/blob/main/docs/troubleshooting.md.
__SKILL_CHROME_DEVTOOLS__

cat > "$_skill_tmp/a11y-debugging.md" <<'__SKILL_A11Y_DEBUGGING__'
---
name: a11y-debugging
description: Uses Chrome DevTools MCP for accessibility (a11y) debugging and auditing based on web.dev guidelines. Use when testing semantic HTML, ARIA labels, focus states, keyboard navigation, tap targets, and color contrast.
---

## Core Concepts

**Accessibility Tree vs DOM**: Visually hiding an element (e.g., `CSS opacity: 0`) behaves differently for screen readers than `display: none` or `aria-hidden="true"`. The `take_snapshot` tool returns the accessibility tree of the page, which represents what assistive technologies "see", making it the most reliable source of truth for semantic structure.

**Reading web.dev documentation**: If you need to research specific accessibility guidelines (like `https://web.dev/articles/accessible-tap-targets`), you can append `.md.txt` to the URL (e.g., `https://web.dev/articles/accessible-tap-targets.md.txt`) to fetch the clean, raw markdown version. This is much easier to read!

## Workflow Patterns

### 1. Browser Issues & Audits

Chrome automatically checks for common accessibility problems. Use `list_console_messages` to check for these native audits first:

- `types`: `["issue"]`
- `includePreservedMessages`: `true` (to catch issues that occurred during page load)

This often reveals missing labels, invalid ARIA attributes, and other critical errors without manual investigation.

### 2. Semantics & Structure

The accessibility tree exposes the heading hierarchy and semantic landmarks.

1.  Navigate to the page.
2.  Use `take_snapshot` to capture the accessibility tree.
3.  **Check Heading Levels**: Ensure heading levels (`h1`, `h2`, `h3`, etc.) are logical and do not skip levels. The snapshot will include heading roles.
4.  **Content Reordering**: Verify that the DOM order (which drives the accessibility tree) matches the visual reading order. Use `take_screenshot` to inspect the visual layout and compare it against the snapshot structure to catch CSS floats or absolute positioning that jumbles the logical flow.

### 3. Labels, Forms & Text Alternatives

1.  Locate buttons, inputs, and images in the `take_snapshot` output.
2.  Ensure interactive elements have an accessible name (e.g., a button should not just say `""` if it only contains an icon).
3.  **Orphaned Inputs**: Verify that all form inputs have associated labels. Use `evaluate_script` to check for inputs missing `id` (for `label[for]`) or `aria-label`:
    ```js
    () =>
      Array.from(document.querySelectorAll('input, select, textarea'))
        .filter(i => {
          const hasId = i.id && document.querySelector(`label[for="${i.id}"]`);
          const hasAria =
            i.getAttribute('aria-label') || i.getAttribute('aria-labelledby');
          return !hasId && !hasAria && !i.closest('label');
        })
        .map(i => ({
          tag: i.tagName,
          id: i.id,
          name: i.name,
          placeholder: i.placeholder,
        }));
    ```

4.  Check images for `alt` text.

### 4. Focus & Keyboard Navigation

Testing "keyboard traps" and proper focus management without visual feedback relies on tracking the focused element.

1.  Use the `press_key` tool with `"Tab"` or `"Shift+Tab"` to move focus.
2.  Use `take_snapshot` to capture the updated accessibility tree.
3.  Locate the element marked as focused in the snapshot to verify focus moved to the expected interactive element.
4.  If a modal opens, focus must move into the modal and "trap" within it until closed.

### 5. Tap Targets and Visuals

According to web.dev, tap targets should be at least 48x48 pixels with sufficient spacing. Since the accessibility tree doesn't show sizes, use `evaluate_script`:

```js
// Usage in console: copy, paste, and call with element: fn(element)
el => {
 const rect = el.getBoundingClientRect();
 return {width: rect.width, height: rect.height};
};
```

_Pass the element's `uid` from the snapshot as an argument to `evaluate_script`._

### 6. Color Contrast

To verify color contrast ratios, start by checking for native accessibility issues:

1.  Call `list_console_messages` with `types: ["issue"]`.
2.  Look for "Low Contrast" issues in the output.

If native audits do not report issues (which may happen in some headless environments) or if you need to check a specific element manually, you can use the following script as a fallback approximation.

**Note**: This script uses a simplified algorithm and may not account for transparency, gradients, or background images. For production-grade auditing, consider injecting `axe-core`.

```js
el => {
  function getRGB(colorStr) {
    const match = colorStr.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
    return match
      ? [parseInt(match[1]), parseInt(match[2]), parseInt(match[3])]
      : [255, 255, 255];
  }
  function luminance(r, g, b) {
    const a = [r, g, b].map(function (v) {
      v /= 255;
      return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4);
    });
    return a[0] * 0.2126 + a[1] * 0.7152 + a[2] * 0.0722;
  }

  const style = window.getComputedStyle(el);
  const fg = getRGB(style.color);
  let bg = getRGB(style.backgroundColor);

  // Basic contrast calculation (Note: Doesn't account for transparency over background images)
  const l1 = luminance(fg[0], fg[1], fg[2]);
  const l2 = luminance(bg[0], bg[1], bg[2]);
  const ratio = (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);

  return {
    color: style.color,
    bg: style.backgroundColor,
    contrastRatio: ratio.toFixed(2),
  };
};
```

_Pass the element's `uid` to test the contrast against WCAG AA (4.5:1 for normal text, 3:1 for large text)._

### 7. Global Page Checks

Verify document-level accessibility settings often missed in component testing:

```js
() => ({
  lang:
    document.documentElement.lang ||
    'MISSING - Screen readers need this for pronunciation',
  title: document.title || 'MISSING - Required for context',
  viewport:
    document.querySelector('meta[name="viewport"]')?.content ||
    'MISSING - Check for user-scalable=no (bad practice)',
  reducedMotion: window.matchMedia('(prefers-reduced-motion: reduce)').matches
    ? 'Enabled'
    : 'Disabled',
});
```

## Troubleshooting

If standard a11y queries fail or the `evaluate_script` snippets return unexpected results:

- **Visual Inspection**: If automated scripts cannot determine contrast (e.g., text over gradient images or complex backgrounds), use `take_screenshot` to capture the element. While models cannot measure exact contrast ratios from images, they can visually assess legibility and identifying obvious issues.
__SKILL_A11Y_DEBUGGING__

log "Deploying skills to $SKILLS_DEST..."
ERRORS_BEFORE_CLAUDE_SKILLS=$ERRORS
deploy_embedded_skill "chrome-devtools" "$SKILLS_DEST" "claude skills" "$_skill_tmp/chrome-devtools.md"
deploy_embedded_skill "a11y-debugging" "$SKILLS_DEST" "claude skills" "$_skill_tmp/a11y-debugging.md"
if [ "$ERRORS" -eq "$ERRORS_BEFORE_CLAUDE_SKILLS" ]; then
    write_summary OK "claude skills" "deployed"
else
    write_summary ERROR "claude skills" "deploy failed"
fi

log "Deploying skills to $SKILLS_DEST_CURSOR..."
ERRORS_BEFORE_CURSOR_SKILLS=$ERRORS
deploy_embedded_skill "chrome-devtools" "$SKILLS_DEST_CURSOR" "cursor skills" "$_skill_tmp/chrome-devtools.md"
deploy_embedded_skill "a11y-debugging" "$SKILLS_DEST_CURSOR" "cursor skills" "$_skill_tmp/a11y-debugging.md"
if [ "$ERRORS" -eq "$ERRORS_BEFORE_CURSOR_SKILLS" ]; then
    write_summary OK "cursor skills" "deployed"
else
    write_summary ERROR "cursor skills" "deploy failed"
fi

rm -rf "$_skill_tmp"

if [ "$ERRORS" -gt 0 ]; then
    log "FAILED with $ERRORS error(s)" "error"
    exit 1
elif [ "$WARNINGS" -gt 0 ]; then
    show_cloud_mcp_status
    log "COMPLETED with $WARNINGS warning(s)" "warn"
    exit 0
else
    show_cloud_mcp_status
    log "COMPLETED successfully" "ok"
    exit 0
fi
