# Generated by scripts/build-deploy.sh — do not edit directly.
# setup-user-hooks.ps1 -- Deploys Claude Code hooks and preferences to ~/.claude/settings.json
# Self-contained: hook scripts and preferences are embedded below. No repo needed.
# Safe to re-run -- merges managed fields without clobbering existing settings.
#
# Managed fields: hooks.SessionEnd, hooks.PreToolUse, autoMemoryEnabled, alwaysThinkingEnabled, effortLevel
# Preserved: permissions, enabledPlugins, all other fields
#
# Hooks deployed:
#   SessionEnd: session-archive.sh (archives transcripts to user repo)
#   PreToolUse[Bash]: standing-order-guard.sh (enforces standing orders on Bash commands)
#
# Note: Hook scripts are bash-only (Claude Code hooks always run in bash on
# both platforms). This PS1 script only deploys the hook configuration.

param(
    [switch]$DryRun,
    [switch]$Force
)

# Env passthrough from parent (aitools CLI)
if ($env:AITOOLS_DRY_RUN -eq "1") { $DryRun = [switch]::Present }

# --- Shared library ---
# aitools-lib.ps1 -- shared helpers for all aitools PowerShell scripts
# Dot-sourced, not executed directly.
#
# Provides: ReadConfigKey, Initialize-Logging, Log/LogOk/LogError/LogWarn,
# Write-Summary, Show-Summary, Refresh-Path, Log-WingetOutput,
# Repair-UvToolEnv, Remove-OrphanedPythonDirs, Normalize-JsonForComparison.
#
# Usage:
#   . (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "aitools-lib.ps1")
#   Initialize-Logging "script-name"
#
# Entry points (aitools.ps1, aitools-install.ps1) override log functions after
# sourcing for specialized logging (file-only, JSONL, etc.).
#
# Platform detection uses PS 7+ built-in $IsMacOS/$IsWindows -- no custom variables.

# ---------------------------------------------------------------------------
# Config reader (PS 5.1 compatible)
# ---------------------------------------------------------------------------
function ReadConfigKey {
    param([string]$File, [string]$Key)
    if (-not (Test-Path $File)) { return $null }
    try {
        $json = Get-Content $File -Raw -ErrorAction Stop | ConvertFrom-Json
        $val = $json.$Key
        if ($val) { return $val }
    } catch {
        # File exists but is invalid JSON -- warn so callers know the null
        # return means "corrupt", not "missing key"
        Write-Host "      WARN: could not parse $File" -ForegroundColor Yellow
    }
    return $null
}

# ---------------------------------------------------------------------------
# Logging init
# ---------------------------------------------------------------------------
# Sets $script:scriptName, $script:logDir, $script:logFile; resets
# $script:errors, $script:warnings. Creates log directory.
# Usage: Initialize-Logging "setup-foo"
function Initialize-Logging {
    param([Parameter(Mandatory)][string]$Name)
    $script:scriptName = $Name
    if ($IsWindows -or (-not (Test-Path variable:IsMacOS))) {
        # Windows (PS 7+) or PS 5.1 (always Windows)
        $script:logDir = Join-Path $env:LOCALAPPDATA "aitools"
    } else {
        # macOS/Linux
        $script:logDir = Join-Path $HOME "Library/Logs/aitools"
    }
    $script:logFile = Join-Path $script:logDir "deploy.log"
    if (-not (Test-Path $script:logDir)) {
        New-Item -ItemType Directory -Path $script:logDir -Force | Out-Null
    }
    $script:errors = 0
    $script:warnings = 0
}

# ---------------------------------------------------------------------------
# Standard logging (console + log file, with [level] tag)
# ---------------------------------------------------------------------------
function Log($msg, $level = "info") {
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $line = "[$ts] [$scriptName] [$level] $msg"
    Add-Content -Path $logFile -Value $line
    switch ($level) {
        "error" { Write-Host $line -ForegroundColor Red }
        "warn"  { Write-Host $line -ForegroundColor Yellow }
        default { Write-Host $line }
    }
}
function LogOk($msg)    { Log $msg "ok" }
function LogError($msg) { Log $msg "error"; $script:errors++ }
function LogWarn($msg)  { Log $msg "warn"; $script:warnings++ }

# ---------------------------------------------------------------------------
# Summary writer (3-arg: category, tool, detail)
# ---------------------------------------------------------------------------
function Write-Summary($cat, $tool, $detail) {
    if ($env:AITOOLS_SUMMARY_FILE) {
        # Auto-promote OK to WARN when warnings have been logged
        if ($cat -eq "OK" -and $script:warnings -gt 0) {
            $cat = "WARN"
        }
        Add-Content -Path $env:AITOOLS_SUMMARY_FILE -Value "${cat}|${tool}|${detail}"
    }
}

# ---------------------------------------------------------------------------
# Backup a file before overwriting. Keeps at most $MaxBackups copies.
# ---------------------------------------------------------------------------
function Backup-File {
    param([string]$FilePath, [int]$MaxBackups = 20)
    if (-not (Test-Path $FilePath)) { return }
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHHmmssZ")
    $backupPath = "${FilePath}.bak.${ts}"
    Copy-Item -Path $FilePath -Destination $backupPath
    # Prune oldest beyond limit
    $backups = Get-ChildItem -Path "${FilePath}.bak.*" | Sort-Object LastWriteTime -Descending
    if ($backups.Count -gt $MaxBackups) {
        $backups | Select-Object -Skip $MaxBackups | Remove-Item -Force
    }
    Log "Backed up $FilePath"
}

# ---------------------------------------------------------------------------
# Backup a directory before modifying managed files. Keeps at most $MaxBackups copies.
# ---------------------------------------------------------------------------
function Backup-Dir {
    param([string]$DirPath, [int]$MaxBackups = 5)
    if (-not (Test-Path $DirPath)) { return }
    $mdFiles = Get-ChildItem -Path $DirPath -Filter "*.md" -File -ErrorAction SilentlyContinue
    if (-not $mdFiles -or $mdFiles.Count -eq 0) { return }
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHHmmssZ")
    $backupPath = "${DirPath}.bak.${ts}"
    try {
        Copy-Item -Path $DirPath -Destination $backupPath -Recurse -ErrorAction Stop
    } catch {
        LogWarn "Could not back up $DirPath -- proceeding without backup: $_"
        return
    }
    $parentDir = Split-Path $DirPath -Parent
    $dirName = Split-Path $DirPath -Leaf
    $backups = Get-ChildItem -Path $parentDir -Directory -Filter "${dirName}.bak.*" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending
    if ($backups -and $backups.Count -gt $MaxBackups) {
        $backups | Select-Object -Skip $MaxBackups | ForEach-Object {
            Remove-Item $_.FullName -Recurse -Force
            Log "Pruned old backup: $($_.FullName)"
        }
    }
    Log "Backed up $DirPath ($($mdFiles.Count) managed files)"
}

# ---------------------------------------------------------------------------
# Prompt user before overwriting a managed file with different content.
# Shows diff and offers: Adopt / Overwrite / Skip / Abort.
#
# Returns: "overwrite", "adopt", or "skip"
# Exits with code 2 on abort.
# Non-interactive / -Force: returns "overwrite".
# ---------------------------------------------------------------------------
function Prompt-DiffReview {
    param(
        [string]$FilePath,
        [string]$NewContent,
        [string]$AdoptLabel = ""
    )

    # -Force or AITOOLS_FORCE: auto-overwrite
    if ($env:AITOOLS_FORCE -eq "1" -or $Force) {
        LogWarn "Diff in $FilePath -- overwriting (-Force)"
        return "overwrite"
    }

    # Non-interactive: auto-overwrite (preserves current behavior)
    if (-not [Environment]::UserInteractive) {
        LogWarn "Diff in $FilePath -- overwriting (non-interactive)"
        return "overwrite"
    }

    # Show diff via [Console] (bypasses *> $null redirection in Deploy-Configs)
    [Console]::WriteLine("")
    [Console]::WriteLine("[REVIEW] $FilePath differs from source.")
    [Console]::WriteLine("")

    # Generate line-level diff
    $srcLines = @($NewContent -split "`n")
    try {
        $curContent = Get-Content $FilePath -Raw -ErrorAction Stop
    } catch {
        LogWarn "Cannot read $FilePath for diff: $_"
        return "overwrite"
    }
    $curLines = @($curContent -split "`n")
    $diffs = Compare-Object $srcLines $curLines
    $diffCount = 0
    if ($diffs) { $diffCount = @($diffs).Count }

    if ($diffCount -eq 0) {
        # Whitespace-only difference
        [Console]::WriteLine("  (whitespace-only differences)")
    } elseif ($diffCount -le 40) {
        foreach ($d in $diffs) {
            $indicator = if ($d.SideIndicator -eq "=>") { "+ " } else { "- " }
            [Console]::WriteLine("  $indicator$($d.InputObject)")
        }
    } else {
        $shown = 0
        foreach ($d in $diffs) {
            if ($shown -ge 30) { break }
            $indicator = if ($d.SideIndicator -eq "=>") { "+ " } else { "- " }
            [Console]::WriteLine("  $indicator$($d.InputObject)")
            $shown++
        }
        [Console]::WriteLine("  ... ($($diffCount - 30) more lines -- see deploy log)")
    }

    # Build prompt with conditional adopt option
    [Console]::WriteLine("")
    if ($AdoptLabel) {
        [Console]::WriteLine("  [A]dopt to $AdoptLabel  [O]verwrite (backup kept)  [S]kip  [X] Abort")
        [Console]::Write("  Choice [a/O/s/x]: ")
    } else {
        [Console]::WriteLine("  [O]verwrite (backup kept)  [S]kip  [X] Abort")
        [Console]::Write("  Choice [O/s/x]: ")
    }
    $choice = [Console]::ReadLine()
    switch ($choice.ToLower()) {
        "a" {
            if ($AdoptLabel) { return "adopt" }
            return "overwrite"
        }
        "s" { return "skip" }
        "x" {
            LogError "Aborted by user"
            exit 2
        }
        default { return "overwrite" }
    }
}

# ---------------------------------------------------------------------------
# PATH helpers
# ---------------------------------------------------------------------------

# Refresh-Path: Reload $env:Path from Machine + User registry values.
# Call after winget install/upgrade to pick up PATH changes in same session.
function Refresh-Path {
    $machinePath = [Environment]::GetEnvironmentVariable("Path", "Machine")
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    $env:Path = "$machinePath;$userPath"
}

# Log-WingetOutput: Filter and log captured winget command output.
# Strips spinner characters (- \ | /), download progress bars (KB/MB/GB),
# and empty lines. Remaining lines are logged at info level.
function Log-WingetOutput([string]$Output) {
    $Output.Trim().Split("`n") | ForEach-Object {
        $l = $_.TrimEnd()
        if ($l.Trim() -and $l.Trim() -notmatch '^[-\\|/]+$' -and $l -notmatch '\d+(\.\d+)?\s*(KB|MB|GB)\s*/\s*\d+') {
            Log $l
        }
    }
}

# ---------------------------------------------------------------------------
# Repair broken uv tool environment (cross-platform)
# ---------------------------------------------------------------------------
# When `uv tool upgrade <tool>` fails with "missing a valid environment",
# find a working Python via `uv python find` (fallback: system python/python3)
# and reinstall with --force --python <path>.
# Returns $true if repaired, $false if not applicable or failed.
function Repair-UvToolEnv {
    param(
        [Parameter(Mandatory)][string]$ToolName,
        [string]$UpgradeOutput = ""
    )

    if ($UpgradeOutput -notmatch 'missing a valid environment') { return $false }

    LogWarn "$ToolName uv environment is broken (Python removed?) -- repairing..."

    # Find a working Python -- uv's own Pythons first, then system
    # Get-Command exempt: command-existence check with fallback chain
    $workingPython = $null
    $uvPython = & uv python find 2>$null
    if ($LASTEXITCODE -eq 0 -and $uvPython -and (Test-Path $uvPython)) {
        $workingPython = $uvPython
    } elseif (Get-Command python -ErrorAction SilentlyContinue) {
        $workingPython = (Get-Command python).Source
    } elseif (Get-Command python3 -ErrorAction SilentlyContinue) {
        $workingPython = (Get-Command python3).Source
    }

    if (-not $workingPython) {
        LogError "Cannot repair $ToolName -- no working Python found"
        return $false
    }

    Log "Repairing with: uv tool install --force --python $workingPython $ToolName"
    $repairOutput = & uv tool install --force --python $workingPython $ToolName 2>&1 | Out-String
    $repairOutput.Trim().Split("`n") | ForEach-Object {
        $l = $_.TrimEnd(); if ($l.Trim()) { Log $l }
    }

    if ($LASTEXITCODE -ne 0) {
        LogError "$ToolName environment repair failed (exit $LASTEXITCODE)"
        return $false
    }

    LogOk "Repaired $ToolName uv environment"
    return $true
}

# ---------------------------------------------------------------------------
# Remove orphaned Python directories (Windows only)
# ---------------------------------------------------------------------------
# Scans %LOCALAPPDATA%\Programs\Python\ for PythonXYZ\ directories where
# python.exe is gone (uninstalled). Removes the orphaned directory tree and
# cleans stale entries from User PATH.
# Returns count of directories removed (0 = nothing to clean).
function Remove-OrphanedPythonDirs {
    if (-not $IsWindows) { return 0 }

    $pythonBase = Join-Path $env:LOCALAPPDATA "Programs\Python"
    if (-not (Test-Path $pythonBase)) { return 0 }

    $removedCount = 0
    $candidates = Get-ChildItem -Path $pythonBase -Directory -ErrorAction SilentlyContinue
    if (-not $candidates) { return 0 }

    foreach ($dir in $candidates) {
        # Skip the Launcher directory (belongs to pymanager)
        if ($dir.Name -eq "Launcher") { continue }

        # Orphaned = python.exe is gone
        $pythonExe = Join-Path $dir.FullName "python.exe"
        if (Test-Path $pythonExe) { continue }

        # Log stale executables for visibility
        $scriptsDir = Join-Path $dir.FullName "Scripts"
        if (Test-Path $scriptsDir) {
            $staleExes = Get-ChildItem $scriptsDir -Filter "*.exe" -File -ErrorAction SilentlyContinue
            if ($staleExes) {
                $names = ($staleExes | Select-Object -First 5 | ForEach-Object { $_.Name }) -join ", "
                LogWarn "Orphaned Python dir with stale executables: $($dir.Name) ($names)"
            }
        }

        try {
            Remove-Item -Path $dir.FullName -Recurse -Force -ErrorAction Stop
            LogOk "Removed orphaned directory: $($dir.FullName)"
            $removedCount++
        } catch {
            LogError "Failed to remove $($dir.FullName): $_"
        }
    }

    # Clean stale User PATH entries pointing to removed Python dirs
    if ($removedCount -gt 0) {
        $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
        if ($userPath) {
            $entries = $userPath -split ";"
            $cleanEntries = @()
            $removedEntries = @()

            foreach ($entry in $entries) {
                $trimmed = $entry.TrimEnd("\", "/")
                if ($trimmed -match '\\Programs\\Python\\Python\d+' -and -not (Test-Path $trimmed)) {
                    $removedEntries += $trimmed
                } else {
                    $cleanEntries += $entry
                }
            }

            if ($removedEntries.Count -gt 0) {
                $newPath = $cleanEntries -join ";"
                [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
                foreach ($re in $removedEntries) {
                    LogOk "Removed stale User PATH entry: $re"
                }
            }
        }

        Refresh-Path
    }

    return $removedCount
}

# ---------------------------------------------------------------------------
# PS 5.1 compatibility: ConvertFrom-Json -> Hashtable (recursive, array-aware)
# ---------------------------------------------------------------------------
function ConvertPSObjectToHashtable($obj) {
    if ($null -eq $obj) { return @{} }
    if ($obj -is [array]) {
        return ,@($obj | ForEach-Object { ConvertPSObjectToHashtable $_ })
    }
    if ($obj -isnot [System.Management.Automation.PSCustomObject]) { return $obj }
    $ht = @{}
    foreach ($prop in $obj.PSObject.Properties) {
        $ht[$prop.Name] = ConvertPSObjectToHashtable $prop.Value
    }
    return $ht
}

# ---------------------------------------------------------------------------
# Emit DETAIL summary entries from a list of change descriptions.
# Usage: Emit-MergeDetails -Changes @("key: old -> new") -ToolName "tool_name"
# ---------------------------------------------------------------------------
function Emit-MergeDetails {
    param(
        [string[]]$Changes,
        [string]$ToolName
    )
    foreach ($change in $Changes) {
        Log "  $change"
        Write-Summary "DETAIL" $ToolName "$change"
    }
}

# ---------------------------------------------------------------------------
# JSON normalization for comparison (sorted keys, deterministic output)
# ---------------------------------------------------------------------------
# PowerShell hashtable key ordering is non-deterministic. ConvertTo-Json
# produces different strings for semantically identical objects, causing
# false-positive change detection. These functions recursively sort keys
# before serializing, ensuring identical content produces identical JSON.
#
# Usage:
#   $norm = Normalize-JsonForComparison $hashtable
#   $norm = Normalize-JsonForComparison $hashtable -Depth 5 -Compress
function ConvertTo-CanonicalObject($obj) {
    if ($null -eq $obj) { return $null }
    if ($obj -is [array]) {
        return ,@($obj | ForEach-Object { ConvertTo-CanonicalObject $_ })
    }
    if ($obj -is [hashtable]) {
        $ordered = [ordered]@{}
        foreach ($key in ($obj.Keys | Sort-Object)) {
            $ordered[$key] = ConvertTo-CanonicalObject $obj[$key]
        }
        return [PSCustomObject]$ordered
    }
    if ($obj -is [System.Management.Automation.PSCustomObject]) {
        $ordered = [ordered]@{}
        foreach ($prop in ($obj.PSObject.Properties | Sort-Object Name)) {
            $ordered[$prop.Name] = ConvertTo-CanonicalObject $prop.Value
        }
        return [PSCustomObject]$ordered
    }
    return $obj
}

function Normalize-JsonForComparison {
    param($Value, [int]$Depth = 10, [switch]$Compress)
    if ($null -eq $Value) { return "null" }
    $canonical = ConvertTo-CanonicalObject $Value
    $canonical | ConvertTo-Json -Depth $Depth -Compress:$Compress
}

# ---------------------------------------------------------------------------
# Go install provenance detection (Windows)
# Returns: "winget", "chocolatey", "scoop", "msi", "none", or "unknown"
# ---------------------------------------------------------------------------
function Get-GoProvenance {
    # Get-Command exempt: command-existence check with explicit fallback
    $goCmd = Get-Command go -ErrorAction SilentlyContinue
    if (-not $goCmd) { return "none" }
    $goSource = $goCmd.Source
    if ($goSource -like '*\Program Files\Go\*') {
        $wingetCheck = winget list --id GoLang.Go --accept-source-agreements 2>&1 | Out-String
        if ($wingetCheck -match 'GoLang\.Go') { return "winget" }
        return "msi"
    }
    if ($goSource -like '*\chocolatey\*') { return "chocolatey" }
    if ($goSource -like '*\scoop\*') { return "scoop" }
    return "unknown"
}

# ---------------------------------------------------------------------------
# Ensure GOPATH\bin is on persistent User PATH (Windows)
# Returns $true if already present, $false if added
# ---------------------------------------------------------------------------
function Ensure-GopathBinOnPath {
    $gopath = $env:GOPATH
    if (-not $gopath) { $gopath = Join-Path $env:USERPROFILE "go" }
    $gopathBin = Join-Path $gopath "bin"
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    if ($userPath -like "*$gopathBin*") { return $true }
    [Environment]::SetEnvironmentVariable("Path", "$userPath;$gopathBin", "User")
    Refresh-Path
    return $false
}

# ---------------------------------------------------------------------------
# Summary panel renderer
# ---------------------------------------------------------------------------
# Reads AITOOLS_SUMMARY_FILE, displays colored panel, cleans up.
# Silent no-op if file unset, missing, or empty.
function Show-Summary {
    $sfile = $env:AITOOLS_SUMMARY_FILE
    if (-not $sfile -or -not (Test-Path $sfile)) { return }
    # Read summary file; -ErrorAction SilentlyContinue checked on next line
    $lines = Get-Content $sfile -ErrorAction SilentlyContinue
    if (-not $lines) {
        # Summary file empty or unreadable; clean up and return
        try { Remove-Item $sfile -Force -ErrorAction Stop }
        catch { Write-Host "  note: could not remove empty summary file" -ForegroundColor Gray }
        return
    }

    # Dedup by tool name: highest severity wins (ERROR > WARN > OK).
    # ACTIONs (empty tool name) are never deduped. DETAIL lines collected separately.
    $rank = @{ 'OK' = 1; 'WARN' = 2; 'ERROR' = 3 }
    $order = [System.Collections.Generic.List[string]]::new()
    $best = @{}
    $bestDetail = @{}
    $detailMap = @{}
    $actions = [System.Collections.Generic.List[string]]::new()

    foreach ($line in $lines) {
        $parts = $line -split '\|', 3
        $cat = $parts[0]
        $tool = $parts[1]
        $det = $parts[2]
        if ($cat -eq 'DETAIL') {
            if (-not $detailMap.ContainsKey($tool)) { $detailMap[$tool] = [System.Collections.Generic.List[string]]::new() }
            $detailMap[$tool].Add($det)
            continue
        }
        if ($cat -eq 'ACTION' -or $tool -eq '') {
            $actions.Add($line)
            continue
        }
        $r = if ($rank.ContainsKey($cat)) { $rank[$cat] } else { 0 }
        if (-not $best.ContainsKey($tool)) {
            $order.Add($tool)
            $best[$tool] = $cat
            $bestDetail[$tool] = $det
        } elseif ($r -gt $rank[$best[$tool]]) {
            $best[$tool] = $cat
            $bestDetail[$tool] = $det
        }
    }

    # Build deduped lines, pre-sorted: OK+details, WARN+details, ERROR+details, ACTIONs
    $deduped = [System.Collections.Generic.List[string]]::new()
    foreach ($sev in @('OK', 'WARN', 'ERROR')) {
        foreach ($t in $order) {
            if ($best[$t] -ne $sev) { continue }
            $deduped.Add("$sev|$t|$($bestDetail[$t])")
            if ($detailMap.ContainsKey($t)) {
                foreach ($d in $detailMap[$t]) { $deduped.Add("DETAIL|$t|$d") }
            }
        }
    }
    foreach ($a in $actions) { $deduped.Add($a) }

    # Color and tag maps for severity categories
    $colorMap = @{ 'OK' = 'Green'; 'WARN' = 'Yellow'; 'ERROR' = 'Red' }
    $tagMap = @{ 'OK' = '  [ok]  '; 'WARN' = '  [!]   '; 'ERROR' = '  [ERR] ' }

    # Single-pass display: deduped list is pre-sorted by severity.
    # DETAIL lines inherit the color of their preceding parent entry.
    Write-Host ""
    Write-Host "------------------------------------------------------------"
    $lastColor = 'Green'
    $firstAction = $true
    foreach ($line in $deduped) {
        $parts = $line -split '\|', 3
        $cat = $parts[0]
        if ($cat -eq 'DETAIL') {
            Write-Host ("                          {0}" -f $parts[2]) -ForegroundColor $lastColor
            continue
        }
        if ($colorMap.ContainsKey($cat)) {
            $lastColor = $colorMap[$cat]
            Write-Host ("{0}{1,-16} {2}" -f $tagMap[$cat], $parts[1], $parts[2]) -ForegroundColor $lastColor
            continue
        }
        if ($cat -eq 'ACTION') {
            if ($firstAction) {
                Write-Host ""
                Write-Host "  ACTION REQUIRED -- run before tools are ready:" -ForegroundColor Magenta
                $firstAction = $false
            }
            Write-Host "  >>  $($parts[2])" -ForegroundColor Magenta
        }
    }
    Write-Host "------------------------------------------------------------"

    # Preserve summary for log compliance checks
    if ($env:AITOOLS_PRESERVE_SUMMARY -eq "1") {
        $preserveDest = Join-Path $script:logDir "last-summary.txt"
        try { Copy-Item $sfile $preserveDest -Force -ErrorAction Stop }
        catch {
            # Non-blocking: summary already displayed; preservation is for compliance checks
            Write-Host "  warning: could not preserve summary: $_" -ForegroundColor Yellow
        }
    }
    # Summary file cleanup (already displayed; next run creates a fresh one)
    try { Remove-Item $sfile -Force -ErrorAction Stop }
    catch { Write-Host "  note: could not remove summary file" -ForegroundColor Gray }
}
Initialize-Logging "setup-user-hooks"

# --- OS guard ---
if ($PSVersionTable.PSVersion.Major -ge 6 -and -not $IsWindows) {
    LogError "This script is for Windows. On macOS/Linux, use the .sh version."
    exit 1
}

if ($DryRun) { Log "[DRY RUN] Preview mode -- no files will be written" }

# --- Deploy embedded hook scripts to ~/.claude/hooks/ ---
$claudeDir = Join-Path $env:USERPROFILE ".claude"
$hooksDir = Join-Path $claudeDir "hooks"
if (-not (Test-Path $hooksDir)) { New-Item -ItemType Directory -Path $hooksDir -Force | Out-Null }

$hookDest = Join-Path $hooksDir "session-archive.sh"
$guardDest = Join-Path $hooksDir "standing-order-guard.sh"

$hookContent = @'
#!/usr/bin/env bash
# session-archive.sh — Claude Code SessionEnd hook
# Archives session transcript to user repo after each session ends.
#
# Baseline: Claude Code 2.1.51 -- hook schema (session_id, cwd, transcript_path)
# Hook input: JSON on stdin with session_id, cwd, transcript_path, etc.
# See reference/user-repo.md for the archiving pattern.
#
# Design decisions:
#   - Silent exit on any misconfiguration (hook must never break Claude Code)
#   - No git operations (user commits/pushes on their own schedule)
#   - Pure-bash JSON parsing (jq not guaranteed in hook environment)
#   - Uses transcript file birth time for date (session start), fallback to today

set -euo pipefail

# Read hook input from stdin
INPUT=$(cat)

# --- Pure-bash JSON field extraction ---
# Extracts a top-level string value from JSON. Handles simple cases only.
json_field() {
    local json="$1" key="$2"
    local val
    val=$(printf '%s' "$json" \
        | grep -o "\"$key\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
        | head -1 \
        | sed 's/.*"'"$key"'"[[:space:]]*:[[:space:]]*"//' \
        | sed 's/"$//')
    printf '%s' "$val"
}

SESSION_ID=$(json_field "$INPUT" "session_id")
CWD=$(json_field "$INPUT" "cwd")
TRANSCRIPT=$(json_field "$INPUT" "transcript_path")

# All three fields are required
if [ -z "$SESSION_ID" ] || [ -z "$CWD" ] || [ -z "$TRANSCRIPT" ]; then
    exit 0
fi

# Transcript file must exist
if [ ! -f "$TRANSCRIPT" ]; then
    exit 0
fi

# --- Read user repo path from aitools config ---
CONFIG_FILE="${HOME}/.aitools/config.json"
if [ ! -f "$CONFIG_FILE" ]; then
    exit 0  # aitools not configured
fi

USER_REPO=$(json_field "$(cat "$CONFIG_FILE")" "userRepoPath")

if [ -z "$USER_REPO" ] || [ ! -d "$USER_REPO" ]; then
    exit 0  # user repo not configured or missing
fi

# --- Derive project name ---
REPO_ROOT=$(cd "$CWD" 2>/dev/null && git rev-parse --show-toplevel 2>/dev/null || echo "")
if [ -n "$REPO_ROOT" ]; then
    PROJECT=$(basename "$REPO_ROOT")
else
    PROJECT=$(basename "$CWD" | tr 'A-Z' 'a-z' | sed 's/[^a-z0-9-]/-/g')
fi

# --- Derive date from transcript file creation time ---
if [ "$(uname -s)" = "Darwin" ]; then
    DATE=$(stat -f "%SB" -t "%Y-%m-%d" "$TRANSCRIPT" 2>/dev/null || date -u +%Y-%m-%d)
else
    # Linux: stat -c %W gives birth time (0 if unsupported), fallback to modify time
    BIRTH=$(stat -c "%W" "$TRANSCRIPT" 2>/dev/null || echo "0")
    if [ "$BIRTH" != "0" ] && [ -n "$BIRTH" ]; then
        DATE=$(date -u -d "@$BIRTH" +%Y-%m-%d 2>/dev/null || date -u +%Y-%m-%d)
    else
        DATE=$(date -u -d "@$(stat -c '%Y' "$TRANSCRIPT" 2>/dev/null)" +%Y-%m-%d 2>/dev/null || date -u +%Y-%m-%d)
    fi
fi

# --- Session ID prefix (first 8 chars) ---
PREFIX=$(printf '%s' "$SESSION_ID" | cut -c1-8)

# --- Target path ---
DEST_DIR="${USER_REPO}/sessions/${PROJECT}"
DEST_FILE="${DEST_DIR}/${DATE}_${PREFIX}.jsonl"

# Skip if already archived
if [ -f "$DEST_FILE" ]; then
    exit 0
fi

mkdir -p "$DEST_DIR"
cp "$TRANSCRIPT" "$DEST_FILE"
'@

$guardContent = @'
#!/usr/bin/env bash
# standing-order-guard.sh — Claude Code PreToolUse hook
# Enforces standing orders by inspecting tool calls before execution.
#
# Currently enforces:
#   USO: Dedicated tools for file ops (Read/Edit/Write/Grep/Glob, not Bash)
#   USO: Scratch files for complex scripting (no long inline commands)
#   USO: Simple Bash commands only (no &&, ||, ;, $(...), backticks, globs in rm)
#
# Hook contract:
#   - Receives JSON on stdin (tool_name, tool_input.command, etc.)
#   - Exit 0 = allow
#   - Exit 2 = block (stderr becomes Claude's feedback)
#   - Must never crash or hang (would break Claude Code)
#
# Rollout mode (per-check):
#   MODE_AND="enforce"      — && : zero false positives confirmed, blocking
#   MODE_SUBSHELL="enforce" — $(): zero false positives confirmed, blocking
#   MODE_REST="observe"     — ||, ;, backticks: false positives exist or low sample count
#   See .claude/rules/hook-rollout.md for the observe-then-enforce practice.
#
# Design decisions:
#   - Pure-bash JSON parsing (jq not guaranteed in hook environment)
#   - Conservative matching: only flag clear violations, allow ambiguous cases
#   - Helpful feedback: tell Claude which tool to use instead
#   - Pipeline exemption: cat/head/tail in pipelines (cmd | ...) are allowed
#     because the Read tool cannot pipe output into other commands

set -euo pipefail

# --- Mode and logging ---
MODE_AND="enforce"      # &&  — zero false positives confirmed; blocking
MODE_SUBSHELL="enforce" # $() — zero false positives confirmed; blocking
MODE_REST="observe"     # ||, ;, backticks — false positives or low sample; observe only

LOG_DIR="$HOME/.claude/hooks/logs"
LOG_FILE="$LOG_DIR/standing-order-guard.log"

# Ensure log directory exists (needed for observe logging; harmless in enforce-only runs)
mkdir -p "$LOG_DIR"

# violation() — dispatch based on per-check mode
# $1: message  $2: mode variable value (enforce or observe; defaults to MODE_REST)
# In enforce mode: write message to stderr, exit 2 (block)
# In observe mode: append to log file, exit 0 (allow)
violation() {
    local message="$1"
    local mode="${2:-$MODE_REST}"
    if [ "$mode" = "enforce" ]; then
        echo "$message" >&2
        exit 2
    else
        printf '%s [WOULD-BLOCK] %s | cmd: %s\n' \
            "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$message" "$COMMAND" \
            >> "$LOG_FILE"
        exit 0
    fi
}

INPUT=$(cat)

# --- Pure-bash JSON field extraction ---
# Same pattern as session-archive.sh. Handles simple top-level string values.
# Uses bash regex (zero external process forks) since this is a hot-path hook.
json_field() {
    local json="$1" key="$2"
    local pattern="\"${key}\"[[:space:]]*:[[:space:]]*\"([^\"]*)\""
    if [[ "$json" =~ $pattern ]]; then
        printf '%s' "${BASH_REMATCH[1]}"
    fi
}

# Extract tool_input.command — it's nested, so we need the command field
# from within tool_input. Since our JSON parser is simple, we can grep for
# the "command" key directly (it appears at the tool_input level).
COMMAND=$(json_field "$INPUT" "command")

# If no command found (shouldn't happen for Bash tool), allow
if [ -z "$COMMAND" ]; then
    exit 0
fi

# --- USO: Scratch files for complex scripting ---
# In JSON, newlines in strings are escaped as \n (literal two-char sequence).
# Count occurrences by measuring string length before/after removing \n sequences.
# This avoids grep exit-code issues with set -euo pipefail when no matches exist.
STRIPPED="${COMMAND//\\n/}"
CMD_LEN=${#COMMAND}
STRIPPED_LEN=${#STRIPPED}
NEWLINE_COUNT=$(( (CMD_LEN - STRIPPED_LEN) / 2 ))
# 5+ lines (4+ newlines) = too complex for inline. Write a temp file instead.
if [ "$NEWLINE_COUNT" -ge 4 ]; then
    LINE_COUNT=$((NEWLINE_COUNT + 1))
    violation "USO: Scratch files --: This command is ~${LINE_COUNT} lines long. Write it to a temp .sh or .ps1 file using the Write tool, execute with Bash, then clean up. USO: never inline long commands in the Bash tool."
fi

# --- USO: Simple Bash commands only ---
# Block compound operators and command substitution that trigger permission prompts.
# Pipelines (|) are explicitly OK per the USO.
# Checked before the first-token allowlist because compound commands like
# `git tag && git push` have `git` as first token and would exit early.
# Known gap: $(...) after quoted segments (e.g., git commit -m "$(...)") is
# invisible due to json_field truncation at \". Mitigated by the USO itself
# (use git commit -F) and by CC's permission system (which prompts anyway).
case "$COMMAND" in
    *'&&'*) violation "USO: Simple Bash commands only --: Don't use '&&' to chain commands. Make separate Bash tool calls instead. For git in another repo, use 'git -C /path' instead of 'cd /path && git'." "$MODE_AND" ;;
    *'||'*) violation "USO: Simple Bash commands only --: Don't use '||' to chain commands. Make separate Bash tool calls instead." "$MODE_REST" ;;
    *';'*)
        # Exempt ; inside scripting-language arguments: pwsh -Command '...;...' and perl -e '...;...'
        # The ; is a language-internal statement separator, not a shell command separator.
        case "$COMMAND" in
            pwsh\ *|powershell\ *|'perl -e'*|'perl -E'*) ;;
            *) violation "USO: Simple Bash commands only --: Don't use ';' to chain commands. Make separate Bash tool calls instead." "$MODE_REST" ;;
        esac
        ;;
    *'$('*) violation "USO: Simple Bash commands only --: Don't use '\$(...)' command substitution. For commit messages, write to a temp file with Write and use 'git commit -F'. For other values, compute in a prior step." "$MODE_SUBSHELL" ;;
    *'`'*)  violation "USO: Simple Bash commands only --: Don't use backtick command substitution. For commit messages, write to a temp file with Write and use 'git commit -F'. For other values, compute in a prior step." "$MODE_REST" ;;
esac

# --- USO: Dedicated tools for file operations ---
# Pattern: command starts with a file-op utility that has a dedicated tool.
# We check the first token of the command (before any arguments).
read -r FIRST_TOKEN _ <<< "$COMMAND"

# Allowlist: commands that look like file ops but are legitimate shell use.
# pwsh wrapping, git operations, npm/node, etc. are always OK.
case "$FIRST_TOKEN" in
    pwsh|powershell|git|npm|node|python*|pip*|cargo|rustup|brew|winget|choco)
        exit 0
        ;;
esac

# --- USO: Simple Bash commands only (glob in destructive operations) ---
# Glob patterns in rm can expand unexpectedly. Write a cleanup script instead.
case "$FIRST_TOKEN" in
    rm)
        case "$COMMAND" in
            *'*'*|*'?'*)
                violation "USO: Simple Bash commands only --: Don't use glob patterns (*, ?) with 'rm'. Write a cleanup script listing the specific files, execute it, then clean up the script."
                ;;
        esac
        ;;
esac

# Check for standalone file-reading commands (should use Read tool)
# Allow in pipelines (cmd | ...) — Read tool can't pipe output into other commands.
case "$FIRST_TOKEN" in
    cat)
        case "$COMMAND" in
            *\|*) ;;  # Pipeline — legitimate shell use
            *) violation "USO: Dedicated tools --: Use the Read tool instead of 'cat' to read files. The Read tool provides line numbers and handles large files better." ;;
        esac
        ;;
    head)
        case "$COMMAND" in
            *\|*) ;;
            *) violation "USO: Dedicated tools --: Use the Read tool with offset/limit parameters instead of 'head'. Example: Read with limit=20 for the first 20 lines." ;;
        esac
        ;;
    tail)
        case "$COMMAND" in
            *\|*) ;;
            *) violation "USO: Dedicated tools --: Use the Read tool with offset parameter instead of 'tail'. Example: Read with offset=100 to start from line 100." ;;
        esac
        ;;
esac

# Check for standalone file-search commands (should use Grep tool)
case "$FIRST_TOKEN" in
    grep|rg|egrep|fgrep)
        violation "USO: Dedicated tools --: Use the Grep tool instead of '$FIRST_TOKEN' to search file contents. The Grep tool supports regex, file filtering, and multiple output modes."
        ;;
esac

# Check for file-finding commands (should use Glob tool)
case "$FIRST_TOKEN" in
    find)
        violation "USO: Dedicated tools --: Use the Glob tool instead of 'find' to locate files. Example: Glob with pattern '**/*.sh' instead of 'find . -name \"*.sh\"'."
        ;;
    ls)
        # ls is borderline -- block when clearly used to list directory contents
        # for exploration (should use Glob or Bash 'ls' for quick checks).
        # Allow: ls is commonly used for quick verification before mkdir, etc.
        # Decision: allow ls, it's a gray area and commonly used in workflows.
        exit 0
        ;;
esac

# Check for file-editing commands (should use Edit tool)
case "$FIRST_TOKEN" in
    sed)
        violation "USO: Dedicated tools --: Use the Edit tool instead of 'sed' to modify files. For non-trivial string manipulation, use Perl (USO: Perl for string manipulation)."
        ;;
    awk)
        violation "USO: Dedicated tools --: Use the Read tool instead of 'awk' to process files. For string manipulation, use Perl (USO: Perl for string manipulation)."
        ;;
esac

# Check for file-writing patterns (should use Write tool)
# These are harder to detect by first token alone. Check the full first line
# for redirection patterns that indicate file creation.
FIRST_LINE=$(printf '%s' "$COMMAND" | head -1)
case "$FIRST_LINE" in
    echo*\>*|printf*\>*)
        # echo/printf redirecting to a file
        violation "USO: Dedicated tools --: Use the Write tool instead of echo/printf redirection to create files. The Write tool handles encoding and permissions correctly."
        ;;
esac

# All checks passed — allow the command
exit 0
'@

if ($DryRun) {
    Log "[DRY RUN] Would deploy hooks to ~/.claude/hooks/"
} else {
    $resolvedHook = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($hookDest)
    [System.IO.File]::WriteAllText($resolvedHook, $hookContent, [System.Text.UTF8Encoding]::new($false))
    LogOk "Deployed hook: $hookDest"
    $resolvedGuard = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($guardDest)
    [System.IO.File]::WriteAllText($resolvedGuard, $guardContent, [System.Text.UTF8Encoding]::new($false))
    LogOk "Deployed hook: $guardDest"
}

# --- Embedded preferences (from profile.json at build time) ---
$autoMemory = $false
$alwaysThinking = $true
$effortLevel = "high"
$validEffortLevels = @("low", "medium", "high")

# --- Merge hook + preferences into ~/.claude/settings.json ---
$settingsFile = Join-Path $claudeDir "settings.json"
if (-not (Test-Path $claudeDir)) {
    if (-not $DryRun) {
        New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null
    }
}

# Hook command uses Unix-style path (hooks run in bash even on Windows)
$hookDestPath = Join-Path $hooksDir "session-archive.sh"
$hookDestUnix = $hookDestPath -replace '\\', '/'
$hookCmd = "bash `"$hookDestUnix`""

# Read existing settings
$settings = @{}
$corrupt = $false
if (Test-Path $settingsFile) {
    try {
        $raw = Get-Content $settingsFile -Raw
        $settings = ConvertPSObjectToHashtable ($raw | ConvertFrom-Json)
    } catch {
        $corrupt = $true
        LogWarn "$settingsFile could not be parsed ($_)"
    }
}
$beforeKeys = @($settings.Keys)

# --- Merge hooks ---
if (-not $settings.ContainsKey("hooks")) { $settings["hooks"] = @{} }

# Helper: ensure exactly one entry for a hookId in an event array.
# Updates the command if found, adds if not, deduplicates extras.
function MergeHookEntry($eventName, $hookIdentifier, $matcherValue, $cmd) {
    if (-not $settings["hooks"].ContainsKey($eventName)) {
        $settings["hooks"][$eventName] = @()
    }
    $arr = @($settings["hooks"][$eventName])

    # Find first matching entry and update it
    $found = $false
    foreach ($rule in $arr) {
        if ($rule -is [System.Collections.Hashtable] -and $rule.ContainsKey("hooks")) {
            foreach ($h in @($rule["hooks"])) {
                if ($h -is [System.Collections.Hashtable] -and $h.ContainsKey("command") -and $h["command"] -match [regex]::Escape($hookIdentifier)) {
                    if (-not $found) {
                        $h["command"] = $cmd
                        $rule["matcher"] = $matcherValue
                        $found = $true
                    }
                }
            }
        }
    }
    if (-not $found) {
        $arr += @{
            matcher = $matcherValue
            hooks   = @(@{ type = "command"; command = $cmd })
        }
    }

    # Normalize: ensure hooks field in each rule is always an array
    # (fixes corruption from prior buggy writes where ConvertTo-Json unwrapped single-element arrays)
    foreach ($rule in $arr) {
        if ($rule -is [System.Collections.Hashtable] -and $rule.ContainsKey("hooks") -and $rule["hooks"] -isnot [array]) {
            $rule["hooks"] = @($rule["hooks"])
        }
    }

    # Deduplicate: keep only the first entry matching hookIdentifier
    $seen = $false
    $deduped = @()
    foreach ($rule in $arr) {
        $isMatch = $false
        if ($rule -is [System.Collections.Hashtable] -and $rule.ContainsKey("hooks")) {
            foreach ($h in @($rule["hooks"])) {
                if ($h -is [System.Collections.Hashtable] -and $h.ContainsKey("command") -and $h["command"] -match [regex]::Escape($hookIdentifier)) {
                    $isMatch = $true
                    break
                }
            }
        }
        if ($isMatch -and $seen) { continue }
        if ($isMatch) { $seen = $true }
        $deduped += $rule
    }
    $settings["hooks"][$eventName] = $deduped
}

# SessionEnd: session archive
MergeHookEntry "SessionEnd" "session-archive.sh" "" $hookCmd

# PreToolUse: standing order guard
$guardDestUnix = $guardDest -replace '\\', '/'
$guardCmd = "bash `"$guardDestUnix`""
MergeHookEntry "PreToolUse" "standing-order-guard.sh" "Bash" $guardCmd

# --- Track old values for change reporting ---
$oldAutoMemory = $settings["autoMemoryEnabled"]
$oldAlwaysThinking = $settings["alwaysThinkingEnabled"]
$oldEffortLevel = $settings["effortLevel"]

# --- Merge claude preferences ---
$settings["autoMemoryEnabled"] = $autoMemory
$settings["alwaysThinkingEnabled"] = $alwaysThinking
if ($effortLevel) { $settings["effortLevel"] = $effortLevel }

# --- Detect preference changes ---
$prefChanges = @()
if ($oldAutoMemory -ne $settings["autoMemoryEnabled"]) {
    $oldVal = if ($null -ne $oldAutoMemory) { $oldAutoMemory } else { "(not set)" }
    $prefChanges += "autoMemoryEnabled: $oldVal -> $($settings['autoMemoryEnabled'])"
}
if ($oldAlwaysThinking -ne $settings["alwaysThinkingEnabled"]) {
    $oldVal = if ($null -ne $oldAlwaysThinking) { $oldAlwaysThinking } else { "(not set)" }
    $prefChanges += "alwaysThinkingEnabled: $oldVal -> $($settings['alwaysThinkingEnabled'])"
}
if ($effortLevel -and $oldEffortLevel -ne $settings["effortLevel"]) {
    $oldEL = if ($oldEffortLevel) { $oldEffortLevel } else { "(not set)" }
    $prefChanges += "effortLevel: $oldEL -> $($settings['effortLevel'])"
}

# --- Clobber detection ---
$managedKeys = @("hooks", "autoMemoryEnabled", "alwaysThinkingEnabled", "effortLevel")
$lostKeys = @($beforeKeys | Where-Object { $_ -notin $settings.Keys })

if ($DryRun) {
    Log "[DRY RUN] $settingsFile`: merge"
    Log "  Managed fields: $($managedKeys -join ', ')"
    if ($lostKeys.Count -gt 0) {
        LogWarn "[DRY RUN] CLOBBER: would lose non-managed fields: $($lostKeys -join ', ')"
    }
    if ($corrupt) {
        LogWarn "[DRY RUN] File is corrupt -- -Force required to overwrite"
    }
    Log "[DRY RUN] SessionEnd hook: $hookCmd"
    Log "[DRY RUN] PreToolUse hook: $guardCmd"
    Log "[DRY RUN] autoMemoryEnabled: $autoMemory"
    Log "[DRY RUN] alwaysThinkingEnabled: $alwaysThinking"
    if ($effortLevel) { Log "[DRY RUN] effortLevel: $effortLevel" }
} else {
    if ($corrupt -and -not $Force) {
        LogError "$settingsFile is corrupt. Use -Force to overwrite, or fix manually."
        Write-Summary "ERROR" "claude hooks" "settings corrupt"
    } elseif ($lostKeys.Count -gt 0 -and -not $Force) {
        LogError "$settingsFile merge would lose fields: $($lostKeys -join ', '). Use -Force to proceed."
        Write-Summary "ERROR" "claude hooks" "merge would lose fields"
    } else {
        if ($corrupt) { LogWarn "Proceeding with -Force on corrupt file" }
        if ($lostKeys.Count -gt 0) { LogWarn "Proceeding with -Force, losing fields: $($lostKeys -join ', ')" }

        $mergedJson = $settings | ConvertTo-Json -Depth 10
        $mergedNorm = Normalize-JsonForComparison $settings -Depth 10
        $existingNorm = if (Test-Path $settingsFile) {
            try { Normalize-JsonForComparison (ConvertPSObjectToHashtable (Get-Content $settingsFile -Raw -ErrorAction Stop | ConvertFrom-Json)) -Depth 10 }
            catch { $null }
        } else { $null }
        if ($mergedNorm -eq $existingNorm) {
            LogOk "Settings unchanged: $settingsFile"
        } else {
            $resolvedPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($settingsFile)
            [System.IO.File]::WriteAllText($resolvedPath, $mergedJson, [System.Text.UTF8Encoding]::new($false))
            $hooksChanged = $true

            # Post-write validation
            try {
                $vContent = [System.IO.File]::ReadAllText($resolvedPath)
                $vParsed = $vContent | ConvertFrom-Json
                $requiredKeys = @("hooks", "autoMemoryEnabled", "alwaysThinkingEnabled")
                if ($effortLevel) { $requiredKeys += "effortLevel" }
                foreach ($rk in $requiredKeys) {
                    if (-not ($vParsed.PSObject.Properties.Name -contains $rk)) {
                        LogError "Validation failed: $settingsFile missing required field '$rk'"
                    }
                }
            } catch {
                LogError "Validation failed: $settingsFile is not valid JSON -- $_"
            }

            # Validate hook deduplication
            $seCount = @($vParsed.hooks.SessionEnd | Where-Object { $_.hooks.command -match 'session-archive\.sh' }).Count
            $ptCount = @($vParsed.hooks.PreToolUse | Where-Object { $_.hooks.command -match 'standing-order-guard\.sh' }).Count
            if ($seCount -ne 1) { LogError "Validation failed: expected 1 SessionEnd hook, got $seCount" }
            if ($ptCount -ne 1) { LogError "Validation failed: expected 1 PreToolUse hook, got $ptCount" }

            LogOk "Settings deployed to $settingsFile"
            Log "  SessionEnd hook: $hookCmd"
            Log "  PreToolUse hook: $guardCmd"
            Log "  autoMemoryEnabled: $autoMemory"
            Log "  alwaysThinkingEnabled: $alwaysThinking"
            $effortDisplay = if ($effortLevel) { $effortLevel } else { "(not set)" }
            Log "  effortLevel: $effortDisplay"
            if ($prefChanges.Count -gt 0) {
                Emit-MergeDetails -Changes $prefChanges -ToolName "claude hooks"
            }
        }
        if ($errors -eq 0) {
            if ($hooksChanged) {
                Write-Summary "OK" "claude hooks" "deployed"
            } else {
                Write-Summary "OK" "claude hooks" "unchanged"
            }
        }
    }
}
if ($errors -gt 0) {
    Log "FAILED with $errors error(s). See log: $logFile" "error"
    exit 1
} elseif ($warnings -gt 0) {
    Log "COMPLETED with $warnings warning(s)" "warn"
    exit 0
} else {
    Log "COMPLETED successfully" "ok"
    exit 0
}
