#!/usr/bin/env bash
# Generated by scripts/build-deploy.sh — do not edit directly.
# setup-user-cursor.sh — Sets up Cursor CLI + dependencies on macOS/Linux
# Self-contained. No repo or Drive needed.
# Safe to re-run — checks each step and skips what's already done.
#
# Does three things:
#   1. Installs ripgrep (rg) if not already present (required by Cursor CLI)
#   2. Installs Cursor CLI (agent command) if not already present
#   3. Merges preferences into ~/.cursor/cli-config.json (preserves CLI-managed fields)

set -euo pipefail

# --- Flag parsing ---
DRY_RUN=false
FORCE=false
for arg in "$@"; do
    case "$arg" in
        --dry-run) DRY_RUN=true ;;
        --force)   FORCE=true ;;
    esac
done
[ "${AITOOLS_DRY_RUN:-}" = "1" ] && DRY_RUN=true

# --- Shared library ---
# aitools-lib.sh -- shared helpers for all aitools bash scripts
# Sourced, not executed directly. No shebang, no set -euo pipefail (caller sets it).
#
# Provides: platform detection, display_path, read_config_key, logging_init,
# log/log_ok/log_error/log_warn, write_summary, show_summary,
# SORT_KEYS_JS, normalize_json.
#
# Usage:
#   source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/aitools-lib.sh"
#   logging_init "script-name"
#
# Entry points (aitools, aitools-install) override log functions after sourcing
# for specialized logging (file-only, JSONL, etc.).

# ---------------------------------------------------------------------------
# Platform detection
# ---------------------------------------------------------------------------
IS_MACOS=false
IS_WINDOWS=false
case "$(uname -s)" in
    Darwin*)              IS_MACOS=true ;;
    MINGW*|MSYS*|CYGWIN*) IS_WINDOWS=true ;;
esac

# ---------------------------------------------------------------------------
# Log directory (platform-aware)
# ---------------------------------------------------------------------------
AITOOLS_LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/aitools"
$IS_MACOS && AITOOLS_LOG_DIR="$HOME/Library/Logs/aitools"

# ---------------------------------------------------------------------------
# Module-level counters (safe for sourcing without logging_init under set -u)
# ---------------------------------------------------------------------------
ERRORS=0
WARNINGS=0

# ---------------------------------------------------------------------------
# Display-friendly path (native Windows on MSYS, no-op elsewhere)
# ---------------------------------------------------------------------------
display_path() {
    if command -v cygpath &>/dev/null; then
        cygpath -w "$1"
    else
        printf '%s' "$1"
    fi
}

# ---------------------------------------------------------------------------
# Config reader (pure bash, handles UTF-8 BOM)
# ---------------------------------------------------------------------------
# Read a top-level string value from a JSON config file.
# Handles UTF-8 BOM (PowerShell 5.x writes one) and JSON-escaped backslashes.
read_config_key() {
    local file="$1" key="$2"
    [ -f "$file" ] || return 1
    local val
    val=$(tr -d '\357\273\277' < "$file" \
        | grep -o "\"$key\"[[:space:]]*:[[:space:]]*\"[^\"]*\"" \
        | head -1 \
        | cut -d'"' -f4)
    [ -n "$val" ] || return 1
    # Unescape JSON backslashes: \\ -> \
    printf '%b' "$val"
}

# ---------------------------------------------------------------------------
# Logging init
# ---------------------------------------------------------------------------
# Sets SCRIPT_NAME, LOG_DIR, LOG_FILE; resets ERRORS, WARNINGS; creates log dir.
# Usage: logging_init "setup-foo"
logging_init() {
    SCRIPT_NAME="${1:?logging_init requires a script name}"
    LOG_DIR="$AITOOLS_LOG_DIR"
    LOG_FILE="$LOG_DIR/deploy.log"
    mkdir -p "$LOG_DIR"
    ERRORS=0
    WARNINGS=0
}

# ---------------------------------------------------------------------------
# Standard logging (Pattern A: console + log file, with [level] tag)
# ---------------------------------------------------------------------------
log() {
    local level="${2:-info}"
    local ts; ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    local line="[$ts] [$SCRIPT_NAME] [$level] $1"
    printf '%s\n' "$line" >> "$LOG_FILE"
    case "$level" in
        error) printf '\033[31m%s\033[0m\n' "$line" ;;
        warn)  printf '\033[33m%s\033[0m\n' "$line" ;;
        *)     printf '%s\n' "$line" ;;
    esac
}
log_ok()    { log "$1" "ok"; }
log_error() { log "$1" "error"; ERRORS=$((ERRORS + 1)); }
log_warn()  { log "$1" "warn"; WARNINGS=$((WARNINGS + 1)); }

# ---------------------------------------------------------------------------
# Summary writer (3-arg: category, tool, detail)
# ---------------------------------------------------------------------------
write_summary() {
    if [ -n "${AITOOLS_SUMMARY_FILE:-}" ]; then
        local cat="$1"
        # Auto-promote OK to WARN when warnings have been logged
        if [ "$cat" = "OK" ] && [ "${WARNINGS:-0}" -gt 0 ]; then
            cat="WARN"
        fi
        printf '%s|%s|%s\n' "$cat" "$2" "$3" >> "$AITOOLS_SUMMARY_FILE"
    fi
}

# ---------------------------------------------------------------------------
# Backup a file before overwriting. Keeps at most $max_backups copies.
# ---------------------------------------------------------------------------
backup_file() {
    local file="$1" max_backups=20
    [ -f "$file" ] || return 0
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    cp "$file" "${file}.bak.${ts}"
    # Prune oldest beyond limit
    ls -1t "${file}.bak."* 2>/dev/null | tail -n +$((max_backups + 1)) | xargs rm -f 2>/dev/null
    log "Backed up $(display_path "$file")"
}

# ---------------------------------------------------------------------------
# Backup a directory before modifying managed files. Keeps at most $max_backups copies.
# ---------------------------------------------------------------------------
backup_dir() {
    local dir="$1" max_backups=5
    [ -d "$dir" ] || return 0
    local file_count
    file_count=$(find "$dir" -maxdepth 1 -name '*.md' -type f | wc -l | tr -d ' ')
    if [ "$file_count" -eq 0 ]; then
        return 0
    fi
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    if ! cp -R "$dir" "${dir}.bak.${ts}"; then
        log_warn "Could not back up $(display_path "$dir") -- proceeding without backup"
        return 0
    fi
    local old_backups
    old_backups=$(find "$(dirname "$dir")" -maxdepth 1 -name "$(basename "$dir").bak.*" -type d \
        | sort -r | tail -n +$((max_backups + 1)))
    if [ -n "$old_backups" ]; then
        printf '%s\n' "$old_backups" | while IFS= read -r old_dir; do
            rm -rf "$old_dir"
            log "Pruned old backup: $(display_path "$old_dir")"
        done
    fi
    log "Backed up $(display_path "$dir") ($file_count managed files)"
}

# ---------------------------------------------------------------------------
# Repair broken uv tool environment (cross-platform)
# ---------------------------------------------------------------------------
# When `uv tool upgrade <tool>` fails with "missing a valid environment",
# find a working Python via `uv python find` (fallback: system python/python3)
# and reinstall with --force --python <path>.
# Returns 0 if repaired, 1 if not applicable or failed.
repair_uv_tool_env() {
    local tool_name="$1"
    local upgrade_output="${2:-}"

    if ! printf '%s\n' "$upgrade_output" | grep -q 'missing a valid environment'; then
        return 1
    fi

    log_warn "$tool_name uv environment is broken (Python removed?) -- repairing..."

    # Find a working Python -- uv's own Pythons first, then system
    local working_python=""
    local uv_python
    uv_python=$(uv python find 2>/dev/null) || true
    if [ -n "$uv_python" ] && [ -x "$uv_python" ]; then
        working_python="$uv_python"
    elif command -v python3 >/dev/null 2>&1; then
        working_python=$(command -v python3)
    elif command -v python >/dev/null 2>&1; then
        working_python=$(command -v python)
    fi

    if [ -z "$working_python" ]; then
        log_error "Cannot repair $tool_name -- no working Python found"
        return 1
    fi

    log "Repairing with: uv tool install --force --python $working_python $tool_name"
    local repair_output
    repair_output=$(uv tool install --force --python "$working_python" "$tool_name" 2>&1) || true
    printf '%s\n' "$repair_output" | while IFS= read -r line; do
        [ -n "$line" ] && log "$line"
    done

    if printf '%s\n' "$repair_output" | grep -qi 'error.*failed'; then
        log_error "$tool_name environment repair failed"
        return 1
    fi

    log_ok "Repaired $tool_name uv environment"
    return 0
}

# ---------------------------------------------------------------------------
# Parse CHANGED: lines from a node merge result and emit DETAIL summary entries.
# Usage: emit_merge_details "$MERGE_RESULT" "tool_name"
# Only processes lines prefixed with "CHANGED: " -- ignores status and other output.
# ---------------------------------------------------------------------------
emit_merge_details() {
    local merge_result="$1" tool_name="$2"
    local changed_keys
    changed_keys=$(echo "$merge_result" | perl -ne 'print if s/^CHANGED: //')
    if [ -n "$changed_keys" ]; then
        while IFS= read -r key_change; do
            log "  $key_change"
            write_summary DETAIL "$tool_name" "$key_change"
        done <<< "$changed_keys"
    fi
}

# ---------------------------------------------------------------------------
# JSON normalization for comparison (sorted keys, deterministic output)
# ---------------------------------------------------------------------------
# JavaScript JSON.stringify preserves insertion order, which may differ
# between runs or between PS1/bash variants writing the same file. Sorting
# keys before comparison ensures identical content produces identical JSON.
#
# SORT_KEYS_JS: minified sortKeys function for embedding in node -e blocks.
#   Usage: node -e "$SORT_KEYS_JS; ..."
#
# normalize_json: pipe-based wrapper for standalone use.
#   Usage: NORMALIZED=$(echo "$json_string" | normalize_json)
SORT_KEYS_JS='function sortKeys(o){if(o===null||typeof o!=="object")return o;if(Array.isArray(o))return o.map(sortKeys);var s={};Object.keys(o).sort().forEach(function(k){s[k]=sortKeys(o[k])});return s}'

normalize_json() {
    node -e "
        var input = require('fs').readFileSync('/dev/stdin', 'utf8');
        $SORT_KEYS_JS
        try {
            console.log(JSON.stringify(sortKeys(JSON.parse(input)), null, 2));
        } catch(e) {
            process.stderr.write('normalize_json: ' + e.message + '\n');
            process.exit(1);
        }
    "
}

# ---------------------------------------------------------------------------
# Go install provenance detection (macOS)
# Returns: "homebrew", "pkg-installer", "goenv", "manual", "none", or "unknown"
# ---------------------------------------------------------------------------
detect_go_provenance() {
    local go_path
    go_path=$(command -v go 2>/dev/null) || { echo "none"; return; }
    case "$go_path" in
        /opt/homebrew/*/go|/usr/local/Cellar/*/go)
            echo "homebrew" ;;
        /usr/local/go/bin/go)
            # Check if installed via macOS .pkg installer (pkgutil) or manual tarball
            if pkgutil --pkg-info=org.golang.go >/dev/null 2>&1; then
                echo "pkg-installer"
            else
                echo "manual"
            fi ;;
        */.goenv/*)
            echo "goenv" ;;
        *)
            echo "unknown" ;;
    esac
}

# ---------------------------------------------------------------------------
# Ensure GOPATH/bin is on PATH for current session
# Returns 0 if already on PATH, 1 if added (caller should warn re persistence)
# ---------------------------------------------------------------------------
ensure_gopath_bin_on_path() {
    local gopath_bin="${GOPATH:-$HOME/go}/bin"
    case ":$PATH:" in
        *":$gopath_bin:"*) return 0 ;;
    esac
    export PATH="$gopath_bin:$PATH"
    return 1
}

# ---------------------------------------------------------------------------
# Summary panel renderer
# ---------------------------------------------------------------------------
# Reads AITOOLS_SUMMARY_FILE, displays colored panel, cleans up.
# Silent no-op if file unset, missing, or empty.
show_summary() {
    local sfile="${AITOOLS_SUMMARY_FILE:-}"
    [ -n "$sfile" ] || return 0
    [ -f "$sfile" ] || return 0
    [ -s "$sfile" ] || { rm -f "$sfile"; return 0; }

    # Dedup by tool name: highest severity wins (ERROR > WARN > OK).
    # ACTIONs (empty tool name) are never deduped. DETAIL lines collected separately.
    # Output is pre-sorted: OK+details, WARN+details, ERROR+details, ACTIONs.
    local deduped
    deduped=$(perl -F'\|' -lane '
        BEGIN { %rank = (OK => 1, WARN => 2, ERROR => 3); }
        $cat = $F[0]; $tool = $F[1]; $det = join("|", @F[2..$#F]);
        if ($cat eq "DETAIL") {
            push @{$details{$tool}}, $det; next;
        }
        if ($cat eq "ACTION" || $tool eq "") {
            push @actions, $_; next;
        }
        $r = $rank{$cat} // 0;
        if (!exists $best{$tool}) {
            push @order, $tool;
            $best{$tool} = $cat; $detail{$tool} = $det;
        } elsif ($r > ($rank{$best{$tool}} // 0)) {
            $best{$tool} = $cat; $detail{$tool} = $det;
        }
        END {
            my (@ok, @warn, @err);
            for my $t (@order) {
                my @g = ("$best{$t}|$t|$detail{$t}",
                         map { "DETAIL|$t|$_" } @{$details{$t} // []});
                if    ($best{$t} eq "OK")    { push @ok,   @g }
                elsif ($best{$t} eq "WARN")  { push @warn, @g }
                elsif ($best{$t} eq "ERROR") { push @err,  @g }
            }
            print for @ok, @warn, @err, @actions;
        }
    ' "$sfile")

    # Single-pass display: Perl output is pre-sorted by severity.
    # DETAIL lines inherit the color of their preceding parent entry.
    echo ""
    echo "────────────────────────────────────────────────────────"
    local last_color="" first_action=true
    while IFS='|' read -r cat tool detail; do
        case "$cat" in
            OK)
                last_color='\033[32m'
                printf '\033[32m  [ok]  %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            WARN)
                last_color='\033[33m'
                printf '\033[33m  [!]   %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            ERROR)
                last_color='\033[31m'
                printf '\033[31m  [ERR] %-16s %s\033[0m\n' "$tool" "$detail"
                ;;
            DETAIL)
                printf '%b                          %s\033[0m\n' "$last_color" "$detail"
                ;;
            ACTION)
                if [ "$first_action" = true ]; then
                    echo ""
                    printf '\033[1;35m  ACTION REQUIRED -- run before tools are ready:\033[0m\n'
                    first_action=false
                fi
                printf '\033[1;35m  >>  %s\033[0m\n' "$detail"
                ;;
        esac
    done <<< "$deduped"
    echo "────────────────────────────────────────────────────────"

    # Preserve summary for log compliance checks
    if [ "${AITOOLS_PRESERVE_SUMMARY:-}" = "1" ]; then
        # cp may fail if log dir was cleaned up; non-blocking (summary already displayed)
        if ! cp "$sfile" "$LOG_DIR/last-summary.txt" 2>/dev/null; then
            printf 'warning: could not preserve summary file\n' >&2
        fi
    fi
    # Cleanup summary file (already displayed; rm -f ignores nonexistent files)
    rm -f "$sfile"
}
logging_init "setup-user-cursor"

# --- OS guard ---
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        log_error "This script is for macOS/Linux. On Windows, use ${SCRIPT_NAME}.ps1 instead."
        exit 1 ;;
esac

[ "$DRY_RUN" = "true" ] && log "[DRY RUN] Preview mode -- no files will be written"

CURSOR_DIR="$HOME/.cursor"
CLI_CONFIG="$CURSOR_DIR/cli-config.json"

# Track status for summary (plain vars -- bash 3.2 compat, no associative arrays)
STATUS_ripgrep=""
STATUS_cursorCli=""
STATUS_cliConfig=""

# --- 1. ripgrep (rg) ---

log "Step 1: ripgrep (rg)"

if [ "$DRY_RUN" = "true" ]; then
    if command -v rg &>/dev/null; then
        RG_VERSION=$(rg --version | head -1)
        log "[DRY RUN] ripgrep already installed: $RG_VERSION"
        STATUS_ripgrep="already installed ($RG_VERSION)"
    else
        log "[DRY RUN] Would install ripgrep via brew"
        STATUS_ripgrep="would install"
    fi
else
    if command -v rg &>/dev/null; then
        RG_VERSION=$(rg --version | head -1)
        log_ok "Already installed: $RG_VERSION"
        STATUS_ripgrep="already installed ($RG_VERSION)"
    else
        if command -v brew &>/dev/null; then
            log "Installing ripgrep via brew..."
            brew install ripgrep

            if command -v rg &>/dev/null; then
                RG_VERSION=$(rg --version | head -1)
                log_ok "Installed: $RG_VERSION"
                STATUS_ripgrep="installed ($RG_VERSION)"
            else
                log_warn "brew install completed but 'rg' not found in PATH. Restart terminal to verify."
                STATUS_ripgrep="installed (restart terminal to verify)"
            fi
        else
            log_warn "Homebrew not found. Install ripgrep manually: brew install ripgrep"
            STATUS_ripgrep="SKIPPED (brew not found)"
        fi
    fi
fi

# --- 2. Cursor CLI (agent) ---

log "Step 2: Cursor CLI (agent)"

if [ "$DRY_RUN" = "true" ]; then
    if command -v agent &>/dev/null; then
        AGENT_VERSION=$(agent --version)
        log "[DRY RUN] Cursor CLI already installed: $AGENT_VERSION"
        STATUS_cursorCli="already installed ($AGENT_VERSION)"
    else
        log "[DRY RUN] Would install Cursor CLI"
        STATUS_cursorCli="would install"
    fi
else
    if command -v agent &>/dev/null; then
        AGENT_VERSION=$(agent --version)
        log_ok "Already installed: $AGENT_VERSION"
        STATUS_cursorCli="already installed ($AGENT_VERSION)"
    else
        log "Installing Cursor CLI..."
        curl https://cursor.com/install -fsS | bash

        if command -v agent &>/dev/null; then
            AGENT_VERSION=$(agent --version)
            log_ok "Installed: $AGENT_VERSION"
            STATUS_cursorCli="installed ($AGENT_VERSION)"
        else
            log_warn "Cursor CLI install completed but 'agent' not found in PATH. Restart terminal to verify."
            STATUS_cursorCli="installed (restart terminal to verify)"
        fi
    fi
fi

# --- 3. cli-config.json (merge, not overwrite) ---

log "Step 3: cli-config.json"

if [ "$DRY_RUN" != "true" ]; then
    backup_file "$CLI_CONFIG"
fi

mkdir -p "$CURSOR_DIR"

if ! command -v node &>/dev/null; then
    log_warn "node not found -- skipping cli-config.json merge"
    STATUS_cliConfig="SKIPPED (node not found)"
else
    # Read cursor.cli preferences from profile.json (via config.json -> userRepoPath).
    # Falls back to defaults if profile not found.

    MERGE_RESULT=$(node -e "
$SORT_KEYS_JS
const fs = require('fs');
const path = require('path');
const f = process.argv[1];
const dryRun = process.argv[2] === 'true';
const force = process.argv[3] === 'true';
// --- Embedded preferences (from profile.json at build time) ---
const vimMode = true;
const modelId = 'auto';

// --- Read existing cli-config.json ---
let config = {};
let corrupt = false;
try {
    config = JSON.parse(fs.readFileSync(f, 'utf8'));
} catch (e) {
    if (e.code !== 'ENOENT') {
        corrupt = true;
        console.error('Warning: ' + f + ' is invalid JSON');
    }
}
const beforeKeys = Object.keys(config);
const before = JSON.stringify(sortKeys(config));

// Snapshot managed keys before merge for CHANGED: tracking
const snapshotKeys = ['version', 'editor', 'permissions', 'model', 'hasChangedDefaultModel'];
const beforeManaged = {};
for (const k of snapshotKeys) beforeManaged[k] = JSON.stringify(sortKeys(config[k]));

// --- Merge managed fields ---
config.version = 1;
if (!config.editor) config.editor = {};
config.editor.vimMode = vimMode;
if (!config.permissions) config.permissions = {};
if (!Array.isArray(config.permissions.allow)) config.permissions.allow = [];
if (!Array.isArray(config.permissions.deny)) config.permissions.deny = [];

// Model: only set if profile specifies 'auto' (the only supported value for now)
if (modelId === 'auto') {
    config.model = {
        modelId: 'default',
        displayModelId: 'auto',
        displayName: 'Auto',
        displayNameShort: 'Auto',
        aliases: ['auto'],
        maxMode: false
    };
    config.hasChangedDefaultModel = true;
}

// --- Clobber detection ---
const managedKeys = ['version', 'editor', 'permissions', 'model', 'hasChangedDefaultModel'];
const afterKeys = Object.keys(config);
const lostKeys = beforeKeys.filter(k => !afterKeys.includes(k));

const after = JSON.stringify(sortKeys(config));

if (dryRun) {
    console.error('[DRY RUN] ' + f + ': merge');
    console.error('  Managed fields: ' + managedKeys.join(', '));
    if (lostKeys.length > 0) console.error('  CLOBBER WARNING: would lose: ' + lostKeys.join(', '));
    if (corrupt) console.error('  File is corrupt -- --force required');
    console.log(before === after && !corrupt ? 'unchanged' : 'would-merge');
} else if (corrupt && !force) {
    console.error('ERROR: ' + f + ' is corrupt. Use --force to overwrite, or fix manually.');
    console.log('error-corrupt');
} else if (lostKeys.length > 0 && !force) {
    console.error('ERROR: merge would lose fields: ' + lostKeys.join(', ') + '. Use --force to proceed.');
    console.log('error-clobber');
} else {
    if (before === after) {
        console.log('unchanged');
    } else {
        if (corrupt) console.error('Warning: proceeding with --force on corrupt file');
        if (lostKeys.length > 0) console.error('Warning: proceeding with --force, losing fields: ' + lostKeys.join(', '));
        fs.writeFileSync(f, JSON.stringify(config, null, 2) + '\n');

        // Post-write validation
        const _v = JSON.parse(fs.readFileSync(f, 'utf8'));
        const _missing = ['version'].filter(k => !(k in _v));
        if (_missing.length) { console.error('Validation failed: missing ' + _missing.join(', ')); process.exit(1); }

        const changed = [];
        for (const k of snapshotKeys) {
            const oldVal = beforeManaged[k];
            const newVal = JSON.stringify(sortKeys(config[k]));
            if (oldVal !== newVal) changed.push(k + ': ' + (oldVal || '(unset)') + ' -> ' + (newVal || '(removed)'));
        }
        console.log(before === '{}' ? 'created' : 'merged');
        changed.forEach(c => console.log('CHANGED: ' + c));
    }
}
" "$CLI_CONFIG" "$DRY_RUN" "$FORCE")

    MERGE_STATUS=$(echo "$MERGE_RESULT" | head -1)
    case "$MERGE_STATUS" in
        unchanged)
            log_ok "Already up to date: $(display_path "$CLI_CONFIG")"
            STATUS_cliConfig="already up to date"
            write_summary OK "cursor cli" "unchanged" ;;
        created)
            log_ok "Created: $(display_path "$CLI_CONFIG")"
            STATUS_cliConfig="created"
            emit_merge_details "$MERGE_RESULT" "cursor cli"
            write_summary OK "cursor cli" "created" ;;
        merged)
            log_ok "Merged preferences into: $(display_path "$CLI_CONFIG")"
            STATUS_cliConfig="merged"
            emit_merge_details "$MERGE_RESULT" "cursor cli"
            write_summary OK "cursor cli" "updated" ;;
        would-merge)
            log "[DRY RUN] Would write merged config"
            STATUS_cliConfig="would merge (dry-run)" ;;
        error-corrupt)
            log_error "$(display_path "$CLI_CONFIG") is corrupt. Use --force to overwrite."
            STATUS_cliConfig="ERROR (corrupt, needs --force)"
            write_summary ERROR "cursor cli" "config corrupt" ;;
        error-clobber)
            log_error "$(display_path "$CLI_CONFIG") merge would lose fields. Use --force to proceed."
            STATUS_cliConfig="ERROR (clobber, needs --force)"
            write_summary ERROR "cursor cli" "merge would lose fields" ;;
        *)
            log_error "Unexpected merge result: $MERGE_STATUS"
            STATUS_cliConfig="ERROR"
            write_summary ERROR "cursor cli" "unexpected error" ;;
    esac
fi

# --- Summary ---

log "=============================="
log "Summary:"
log "  ripgrep:       ${STATUS_ripgrep}"
log "  Cursor CLI:    ${STATUS_cursorCli}"
log "  cli-config:    ${STATUS_cliConfig}"
log "=============================="
if [ "$ERRORS" -gt 0 ]; then
    log "FAILED with $ERRORS error(s)" "error"
    exit 1
elif [ "$WARNINGS" -gt 0 ]; then
    log "COMPLETED with $WARNINGS warning(s)" "warn"
    exit 0
else
    log "COMPLETED successfully" "ok"
    exit 0
fi
