#!/usr/bin/env python3
"""Rebuild the planning brief from scratch with KPIs, Datadog/Auth0 context,
updated framework intents, facts, and assumptions.

Writes to: .scratch/session-952OZxWICI/planning-brief.json
"""
import json, os

brief = {
    "meta": {
        "schemaVersion": "5.0",
        "plan": "plans/mission-command-and-platform-engineering.md",
        "created": "2026-03-16",
        "concept": "Adapted from MDMP Step 2 (Mission Analysis). Each decision is a resolved decision point. Facts are verified ground truths. Assumptions are accepted for planning but unverified. KPIs define how we measure success via Datadog telemetry (governance plan decision #13: local SQLite + Datadog).",
        "sourceFrameworks": [
            "MDMP Step 2: Mission Analysis (facts, assumptions, specified/implied tasks)",
            "Mission Command planning guidance (commander's resolved decisions)",
            "SRE production readiness review (checklist items with rationale)",
            "OPORD Situation paragraph (facts and assumptions that shape execution)"
        ],
        "sessions": {
            "thisSession": "b8a9ed4e — 2026-03-16, formulated this planning brief",
            "toolOpsPlanningSession": "84280c8b — 2026-03-15 20:08-22:57 UTC, delegation protocol, tool-ops framework, 7 plan rewrites. Transcript: sessions/aitools/2026-03-15_84280c8b.jsonl",
            "toolOpsExecutionSession": "eaacf9da — 2026-03-15 22:57-00:22 UTC, executed tool-ops plan, produced AAR + test suite. Transcript: sessions/aitools/2026-03-15_eaacf9da.jsonl",
            "skillsExtractionSession": "c8862b68 — 2026-03-15 17:08-20:01 UTC, setup-user-skills extraction. Transcript: sessions/aitools/2026-03-15_c8862b68.jsonl",
            "windowsSession": "Summary: /Users/pepe/Library/CloudStorage/GoogleDrive-jose@nobul.tech/My Drive/nobul co/scratch/chat-summary-macos-work.md",
            "planFile": "~/.claude/plans/gleaming-cooking-unicorn.md (local only, see decision #18)"
        },
        "workProducts": {
            "aar": "harvesting/2026-03-16_aar-tool-ops-plan.md (731 lines, 10 decisions, 7 plan revisions)",
            "testSuite": "harvesting/2026-03-16_test-tool-ops.py (42 tests, 5 suites)",
            "delegationEvolution": ".scratch/session-952OZxWICI/delegation-evolution.md",
            "decisionQualityAudit": ".scratch/session-952OZxWICI/decision-quality-audit.md",
            "researchSynthesis": ".scratch/session-952OZxWICI/research-synthesis.md",
            "intentApprovalEvolution": ".scratch/session-952OZxWICI/intent-approval-evolution.md",
            "incidentRegistryAudit": ".scratch/session-952OZxWICI/investigate-incident-registry.md",
            "crossRefAudit": ".scratch/session-952OZxWICI/investigate-cross-refs.md",
            "sessionGapAudit": ".scratch/session-952OZxWICI/investigate-session-gaps.md",
            "harnessStateAudit": ".scratch/session-952OZxWICI/investigate-harness-state.md",
            "crossPlatformAudit": ".scratch/session-952OZxWICI/cross-platform-full-audit.md",
            "knownStateAudit": ".scratch/session-952OZxWICI/known-state-audit.md"
        },
        "telemetry": {
            "strategy": "Local SQLite (~/.aitools/telemetry/governance.db, WAL mode) + Datadog via log_ship (plans/datadog-log-integration.md). Auth0 manages datadogApiKey (plans/nobul-auth0-platform.md Phase 2).",
            "datadogPlan": "plans/datadog-log-integration.md — 5 phases: foundation (log_ship), dashboards, CI visibility, MCP integration, post-credits migration to Axiom",
            "auth0Plan": "plans/nobul-auth0-platform.md — 5 phases: tenant setup, GitHub MVP, multi-provider, token lifecycle, web apps + RBAC"
        },
        "kpiSchema": {
            "description": "Each decision has a kpis array. Each KPI has: name (metric name), source (what generates it), unit (measurement), target (success threshold). KPIs ship to Datadog via log_ship at SessionEnd.",
            "example": {"name": "delegationComplianceRate", "source": "channel SITREPs", "unit": "percent", "target": ">= 95% of delegations include all 8 components"}
        }
    },
    "facts": [
        {
            "id": "F1", "severity": "critical", "blocksPlanning": True,
            "observation": "/tool-registry skill (SKILL.md lines 20, 64, 72, 102) references reference/tool-registry.json which does not exist. Any agent invoking /tool-registry gets broken behavior.",
            "verified": "Session b8a9ed4e: cross-reference investigator confirmed. RCA: harvesting/2026-03-15_rca-registry-bypass.md. Incident #21 tracks migration but no corrective action taken.",
            "impact": "Agent-breaking. /tool-registry skill is non-functional.",
            "frameworks": ["Incident governance", "Tool lifecycle"]
        },
        {
            "id": "F2", "severity": "critical", "blocksPlanning": True,
            "observation": "/harvest skill (SKILL.md lines 29, 69) references @reference/harvest-manifest.json but actual file is harvesting/harvest-manifest.json — wrong directory.",
            "verified": "Session b8a9ed4e: cross-reference investigator confirmed.",
            "impact": "Agent-breaking. /harvest skill cannot read manifest.",
            "frameworks": ["Artifact harvesting", "Incident governance"]
        },
        {
            "id": "F3", "severity": "high", "blocksPlanning": False,
            "observation": ".claude/rules/frameworks.md registries table (line 30, always in context) lists phantom @reference/tool-registry.json.",
            "verified": "Session b8a9ed4e: cross-reference investigator confirmed.",
            "impact": "Every agent sees the broken reference. Reinforces phantom.",
            "frameworks": ["Incident governance"]
        },
        {
            "id": "F4", "severity": "high", "blocksPlanning": False,
            "observation": "surfacing-duty-stop.sh lines 53/56 use stat -f (BSD-only) with no platform dispatch. Crashes on every Stop hook on Windows: 'line 54: File: unbound variable'.",
            "verified": "Windows session: error visible twice. Session b8a9ed4e: confirmed by reading hook source.",
            "impact": "Surfacing duty disabled on Windows. Incident-acknowledgment detection never fires.",
            "frameworks": ["Platform engineering (proposed)", "Tool operations"]
        },
        {
            "id": "F5", "severity": "high", "blocksPlanning": False,
            "observation": "8 incidents silently resolved (IDs: 8, 15, 17, 18, 32, 36, 40, 47). Code fixed, incidents never closed.",
            "verified": "Session b8a9ed4e: incident registry auditor verified each.",
            "impact": "Registry shows 42 open when real count is ~25. Planning based on inflated count.",
            "frameworks": ["Incident governance"]
        },
        {
            "id": "F6", "severity": "high", "blocksPlanning": False,
            "observation": "3 stale duplicate incidents (39, 41, 46) duplicate #43. 3 'planned' incidents (28, 30, 33) have corrective actions but linked=null.",
            "verified": "Session b8a9ed4e: incident registry auditor confirmed.",
            "impact": "6 more entries that should be closed or updated.",
            "frameworks": ["Incident governance"]
        },
        {
            "id": "F7", "severity": "high", "blocksPlanning": False,
            "observation": "5 unfiled issues: (1) stop hook crash Windows, (2) 3 uncommitted sessions Mac, (3) phantom session ID 2Hb40B0VEu in harvest manifest, (4) date mismatch between hooks, (5) Explore agents can't write to scratch.",
            "verified": "Session b8a9ed4e: session gap investigator confirmed all 5 with draft fields. Report: .scratch/session-952OZxWICI/investigate-session-gaps.md",
            "impact": "Surfacing duty gap. Issues discussed but never tracked.",
            "frameworks": ["Incident governance"]
        },
        {
            "id": "F8", "severity": "medium", "blocksPlanning": False,
            "observation": "14/22 rules (64%) lack intent statements. 3/17 skills lack intent.",
            "verified": "Session b8a9ed4e: harness state auditor confirmed.",
            "impact": "Violates 'Document intent' design principle.",
            "frameworks": ["Intent documentation"]
        },
        {
            "id": "F9", "severity": "medium", "blocksPlanning": False,
            "observation": "7/8 user-level skills have no trigger directive in any rule.",
            "verified": "Session b8a9ed4e: harness state auditor confirmed.",
            "impact": "Skills may not auto-fire. No detection hook catches bypass.",
            "frameworks": ["Three-layer governance"]
        },
        {
            "id": "F10", "severity": "medium", "blocksPlanning": False,
            "observation": "4 glossary terms in JSON (hook, incident, rule, skill) missing from rule word list. governed file definition omits tool-ops.json.",
            "verified": "Session b8a9ed4e: harness state auditor confirmed.",
            "impact": "Terms invisible to agents (they read the rule, not JSON).",
            "frameworks": ["Governed vocabulary"]
        },
        {
            "id": "F11", "severity": "medium", "blocksPlanning": False,
            "observation": "reference/evaluations/ directory empty. No tool evaluation artifacts exist.",
            "verified": "Session b8a9ed4e: harness state auditor confirmed.",
            "impact": "Tool evaluation framework has no instances.",
            "frameworks": ["Tool lifecycle"]
        },
        {
            "id": "F12", "severity": "medium", "blocksPlanning": False,
            "observation": "cursor-rule-parity.md deleted v0.54 but still referenced by 2 files. 2 checklist paths wrong in tool-ops-claude-code.md.",
            "verified": "Session b8a9ed4e: cross-reference investigator confirmed.",
            "impact": "Broken cross-references — agents hit dead ends.",
            "frameworks": ["Incident governance"]
        },
        {
            "id": "F13", "severity": "low", "blocksPlanning": False,
            "observation": "8 framework lastUpdated timestamps are 2026-03-14 despite 22 commits on 2026-03-15.",
            "verified": "Session b8a9ed4e: harness state auditor confirmed.",
            "impact": "May trigger false staleness warnings.",
            "frameworks": ["Framework adoption"]
        },
        {
            "id": "F14", "severity": "medium", "blocksPlanning": False,
            "observation": "Datadog log_ship helper designed (plans/datadog-log-integration.md) but not built. KPI telemetry pipeline does not exist yet. Local SQLite governance.db does not exist yet.",
            "verified": "Session b8a9ed4e: read Datadog plan. No log_ship function in aitools-lib.sh.",
            "impact": "No KPIs can be measured until log_ship + SQLite are built. Framework effectiveness is unmeasured.",
            "frameworks": ["Tool operations", "Three-layer governance"]
        },
        {
            "id": "F15", "severity": "medium", "blocksPlanning": False,
            "observation": "Auth0 tenant provisioned (Startups plan) but aitools auth not implemented. datadogApiKey currently in plain text in config.json. No centralized credential management.",
            "verified": "Session b8a9ed4e: read Auth0 plan. No aitools-auth.sh/.ps1 in scripts/.",
            "impact": "Credentials managed ad-hoc per tool. Keychain prompts block installs (incident #23).",
            "frameworks": ["Tool lifecycle"]
        }
    ],
    "assumptions": [
        {
            "id": "A1",
            "assumption": "Closing 14 incidents won't break downstream references in plans, roadmap, or other incidents.",
            "risk": "If a plan references a closed ID, the reference becomes stale.",
            "verification": "Grep repo for each incident ID before closing.",
            "frameworks": ["Incident governance"]
        },
        {
            "id": "A2",
            "assumption": "Stop hook stat crash doesn't affect other hooks on Windows.",
            "risk": "Other hooks may have the same BSD stat pattern.",
            "verification": "session-archive.sh has uname dispatch (safe). Verify tool-ops-session-audit.sh.",
            "frameworks": ["Platform engineering (proposed)"]
        },
        {
            "id": "A3",
            "assumption": "Blocking Explore agents won't break existing workflows.",
            "risk": "Some agents use Explore for legitimate read-only research.",
            "verification": "Audit recent sessions for Explore launches. Determine if general-purpose works instead.",
            "frameworks": ["Mission command (proposed)"]
        },
        {
            "id": "A4",
            "assumption": "Hooks run bash on all platforms (Claude Code design constraint).",
            "risk": "If Anthropic changes CC to run hooks in PowerShell on Windows, all hooks break.",
            "verification": "Monitor CC release notes. Current: verified CC 2.1.76.",
            "frameworks": ["Platform engineering (proposed)", "Tool operations"]
        },
        {
            "id": "A5",
            "assumption": "Datadog startup credits (up to $100K, 1 year Pro) are sufficient for our telemetry volume.",
            "risk": "If log volume exceeds credits, we need to migrate to Axiom sooner than planned.",
            "verification": "Monitor usage after log_ship is built. Axiom migration path is designed (Phase 5).",
            "frameworks": ["Tool operations"]
        },
        {
            "id": "A6",
            "assumption": "Auth0 Startups plan (100K MAU, 12 months free) will remain available and auto-downgrade to Free (25K MAU) after.",
            "risk": "Auth0 changes pricing or plan terms.",
            "verification": "Monitor Auth0 announcements. Free tier (25K MAU) is the fallback.",
            "frameworks": ["Tool lifecycle"]
        }
    ],
    "decisions": []
}

# Helper to build decisions
def d(id, decision, rationale, context, components, frameworks, artifacts, kpis, related, status="agreed"):
    return {
        "id": id,
        "decision": decision,
        "rationale": rationale,
        "context": context,
        "components": components,
        "frameworks": frameworks,
        "artifacts": artifacts,
        "kpis": kpis,
        "status": status,
        "related": related
    }

decisions = [
    # === SESSION LIFECYCLE ===
    d(1,
      "Session archive hook must auto-commit and auto-push at SessionEnd",
      "3 sessions invisible cross-machine because archive hook copies transcripts but does no git ops. 'User commits on their own schedule' creates predictable cross-machine gap.",
      "Windows session: 1/4 sessions visible. Session b8a9ed4e: confirmed 3 uncommitted on Mac. reference/user-repo.md L147.",
      ["(1) git add transcript after copy",
       "(2) git commit: 'Archive session <date>_<prefix> (<project>)'",
       "(3) git push to remote",
       "(4) If push fails (remote ahead): log_warn, don't block SessionEnd",
       "(5) If userRepoPath not configured: skip silently (existing behavior)"],
      [{"name": "Session lifecycle", "status": "proposed", "intent": {
          "purpose": "Govern end-to-end lifecycle of Claude Code session data — archiving, cross-machine sync, privacy boundaries, and relationship to artifact harvesting",
          "scope": "Session transcript archiving, dotprofile sync, naming conventions, cross-machine visibility. NOT artifact harvesting. NOT session content analysis",
          "audience": "Agents modifying session hooks, user-repo spec, or archive behavior"}}],
      [{"path": "shared/hooks/session-archive.sh", "status": "existing"},
       {"path": "reference/user-repo.md", "status": "existing"}],
      [{"name": "crossMachineVisibilityRate", "source": "session-archive hook logs", "unit": "percent", "target": ">= 99% sessions visible within 5 min of end"},
       {"name": "archivePushFailureRate", "source": "session-archive hook logs", "unit": "failures/week", "target": "< 1"}],
      [2, 10]),

    d(2,
      "Data replication between session archives and harvesting is acceptable if clearly defined",
      "User: 'im ok replicating data... some users have privacy concerns.' Archives (dotprofile) = full transcripts for user. Harvesting (project repo) = extracted artifacts for project. Privacy boundary must be documented.",
      "Session b8a9ed4e: overlap discussion between hooks.",
      ["(1) Document what lives where: transcripts in dotprofile, artifacts in project repo",
       "(2) Privacy boundary: user controls dotprofile visibility, project repo is shared",
       "(3) Naming consistency between systems (session ID prefix, date format)",
       "(4) Define opt-out: harvesting without archiving, or vice versa",
       "(5) Document in reference/user-repo.md and reference/framework-artifact-harvesting.md"],
      [{"name": "Session lifecycle", "status": "proposed"},
       {"name": "Artifact harvesting", "status": "existing"}],
      [{"path": "reference/user-repo.md", "status": "existing"},
       {"path": "reference/framework-artifact-harvesting.md", "status": "existing"}],
      [{"name": "archiveHarvestNamingConsistency", "source": "check script audit", "unit": "mismatches", "target": "0"}],
      [1, 10]),

    # === MISSION COMMAND ===
    d(3,
      "Mission command framework needed: rule, skill, reference file, channel",
      "5 delegation failures this session + AAR Decision 8 (L1187) identified delegation duty as framework-level. Scope expanded from 'delegation protocol' to full Mission Command: delegation + communication + staff functions + authority model.",
      "Planning 84280c8b: L522 framework vision, L633 naming, L1187 delegation duty. Session b8a9ed4e: 5 failures demonstrated, framework evolved through naming iterations (Agent delegation -> Delegation protocol -> Mission command). AAR Section 9 Lesson 5.",
      ["(1) Rule (.claude/rules/delegation.md): governance principle, trigger directive, harness constraints",
       "(2) Skill (.claude/skills/delegate/SKILL.md): context injection, agent type selection, identity briefing, carry-forward",
       "(3) Skill (.claude/skills/channel/SKILL.md): inter-agent messaging (SITREP/FINDING)",
       "(4) Reference (reference/framework-mission-command.md): Mission Command + FM 101-5-2 adaptation, harness constraints",
       "(5) Reference (reference/channel-schemas.json): SITREP and FINDING (SALUTE-adapted) schemas",
       "(6) Directory (.channel/): operations journal for inter-agent communication",
       "(7) Hook (shared/hooks/block-explore-agent.sh): agent type enforcement",
       "(8) Register via /frameworks skill"],
      [{"name": "Mission command", "status": "proposed", "intent": {
          "purpose": "Govern how agents plan, delegate, communicate, and coordinate during multi-agent operations. Adapted from Mission Command (Auftragstaktik) and US Army battle staff communications (FM 101-5-2), with five harness constraints: no persistence, no inherited rules, no mid-execution updates, no peer communication, post-execution verification only. Covers the full operational cycle: delegation duty, identity briefings, inter-agent communication (SITREP/FINDING), staff function identities (S1-S3), disciplined initiative authority, intelligence preparation, findings consolidation, and FRAGORD kill-and-replace",
          "scope": "Delegation protocol (8 components), inter-agent channel (.channel/, schemas, /channel skill), staff functions and identity assignment, authority model (sensors not filers, disciplined initiative), plan execution coordination (S2 at start/end, S1 at end), FRAGORD pattern, pre-draft intent approval pattern. NOT plan writing (mission analysis). NOT tool-specific operations (tool operations). NOT session archiving (session lifecycle)",
          "audience": "Every agent that delegates work or communicates findings, every plan execution, every session"}}],
      [{"path": ".claude/rules/delegation.md", "status": "proposed"},
       {"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"},
       {"path": ".claude/skills/channel/SKILL.md", "status": "proposed"},
       {"path": "reference/framework-mission-command.md", "status": "proposed"},
       {"path": "reference/channel-schemas.json", "status": "proposed"},
       {"path": ".channel/", "status": "proposed"},
       {"path": "shared/hooks/block-explore-agent.sh", "status": "proposed"}],
      [{"name": "delegationComplianceRate", "source": "channel SITREPs", "unit": "percent", "target": ">= 95% delegations include all 8 components"},
       {"name": "channelMessageCount", "source": "channel-manifest.json", "unit": "messages/plan", "target": ">= 1 SITREP per batch"},
       {"name": "findingConsolidationRate", "source": "S2 SITREP at plan end", "unit": "percent", "target": "100% findings reviewed at plan completion"}],
      [4, 5, 6, 7, 22, 23, 24, 25, 26, 27, 28]),

    d(4,
      "Delegation duty has 8 components — 7 from tool-ops execution protocol + agent type matching",
      "Planning session 84280c8b produced 7-step duty through 7 revisions. Session b8a9ed4e added 8th: agent type matching.",
      "84280c8b: L1187 duty born, L1271 identity, L1236-1242 constraints, L1260 recursive, L1268 include-the-plan. eaacf9da: executed 8 batches. AAR: harvesting/2026-03-16_aar-tool-ops-plan.md. b8a9ed4e: 5 failures, evolution report .scratch/session-952OZxWICI/delegation-evolution.md.",
      ["(1) Establish identity — who the agent is, role, how work fits larger effort",
       "(2) Include the plan — execution protocol + relevant sections (FRAGORD without OPORD is useless)",
       "(3) Include prior results — actual results, deviations, impact",
       "(4) Include what comes after — downstream dependencies",
       "(5) Inject critical rules — standing orders, scratch, error-handling, source-of-truth, governed-data",
       "(6) Note deviations — what changed from plan and why",
       "(7) Note new findings — issues surfaced during prior work",
       "(8) Match agent type — Explore for read-only, general-purpose when writing required"],
      [{"name": "Mission command", "status": "proposed"}],
      [{"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"},
       {"path": ".claude/rules/delegation.md", "status": "proposed"}],
      [{"name": "delegationComponentCoverage", "source": "delegation briefing audit", "unit": "components/8", "target": "8/8 for every delegation"},
       {"name": "agentTypeMismatchRate", "source": "block-explore-agent hook", "unit": "blocks/session", "target": "0 after framework adoption"}],
      [3, 5, 6, 7, 19]),

    d(5,
      "Block Explore agents via new PreToolUse hook with corrective injection",
      "Explore agents can't Write/Edit. Delegation duty component 5 requires scratch access. New hook per decision #20 (one hook per feature).",
      "Session b8a9ed4e: 3 Explore agents failed silently on write-to-scratch. Existing block-claude-code-guide.sh pattern (84280c8b).",
      ["(1) New hook: shared/hooks/block-explore-agent.sh",
       "(2) PreToolUse on Agent — check subagent_type in tool_input JSON",
       "(3) If Explore: exit 0 with deny + corrective message in permissionDecisionReason",
       "(4) Message: 'Explore agents cannot write to scratch. Use general-purpose. See /delegate.'",
       "(5) If not Explore: exit 0, no stdout (allow)",
       "(6) Add verification case to tool-ops.json via /tool-ops",
       "(7) Deploy to ~/.claude/hooks/ via setup-user-hooks"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Tool operations", "status": "existing"}],
      [{"path": "shared/hooks/block-explore-agent.sh", "status": "proposed"},
       {"path": "reference/tool-ops.json", "status": "existing"}],
      [{"name": "exploreDenyRate", "source": "hook logs", "unit": "blocks/session", "target": "trending to 0 as agents learn"},
       {"name": "hookLatency", "source": "hook timing", "unit": "ms", "target": "< 50ms"}],
      [4, 6, 20]),

    d(6,
      "Add Explore agent deny rule to Claude Code permissions — defense in depth",
      "Hook provides corrective injection, deny rule provides belt-and-suspenders prevention. Register in tool-ops.json via /tool-ops.",
      "Session b8a9ed4e: existing pattern from Agent(claude-code-guide). Three-layer: hook=detection, deny=prevention.",
      ["(1) Add Agent(Explore) to permissions.deny in settings.json",
       "(2) Add deny rule to tool-ops.json: id=cc-deny-explore-agent, pattern=Agent(Explore), hook=block-explore-agent.sh",
       "(3) Add to setup-user-hooks deployment",
       "(4) Add verification test case to tool-ops.json"],
      [{"name": "Tool operations", "status": "existing"},
       {"name": "Three-layer governance", "status": "existing"}],
      [{"path": "reference/tool-ops.json", "status": "existing"}],
      [{"name": "denyRuleDriftRate", "source": "tool-ops-session-audit hook", "unit": "mismatches", "target": "0"}],
      [5, 20]),

    d(7,
      "Delegation duty is recursive — any agent that delegates must follow it",
      "AAR Revision 6 (L1260): 'This applies recursively.' Protocol included in briefing so delegated agents follow it if they delegate.",
      "84280c8b: L1254-1264 agent generalized to 'delegating/delegated agent'. Evolution report Section 7. b8a9ed4e: confirmed.",
      ["(1) Any agent that delegates follows all 8 components",
       "(2) Protocol itself included in briefing for recursive application",
       "(3) Terminology: 'delegating agent' / 'delegated agent' — never 'main agent'",
       "(4) Practical depth limit: ~2-3 levels (context cost increases per level)"],
      [{"name": "Mission command", "status": "proposed"}],
      [{"path": ".claude/rules/delegation.md", "status": "proposed"}],
      [{"name": "maxDelegationDepth", "source": "channel SITREPs", "unit": "levels", "target": "<= 3"}],
      [3, 4]),

    # === PLATFORM ENGINEERING ===
    d(8,
      "Platform engineering framework: all aitools code, all languages, user-level",
      "Hooks + build-deploy run bash on ALL platforms but cross-platform rule only covers .sh/.ps1 pairs. surfacing-duty-stop.sh crashed on Windows. nobul-ops has 10 Rust platform blocks, 4 CI targets. Scope covers all languages.",
      "Windows session: stop hook crash. b8a9ed4e: cross-platform audit, nobul-ops audit (10 #[cfg] blocks). CLAUDE.md mission: 'platform-native best practices — not artificial 1:1 parity.'",
      ["(1) Absorbs .claude/rules/cross-platform.md as the rule",
       "(2) Absorbs reference/cross-platform-detail.md as detail reference",
       "(3) New reference/framework-platform-engineering.md — Rust/Go/Python/Perl patterns from nobul-ops",
       "(4) New reference/platform-compat.json — divergence registry + all-platform script registry",
       "(5) New shared/skills/platform-engineering/SKILL.md — USER-LEVEL, deployed to ~/.claude/skills/",
       "(6) Extend aitools-lib.sh: get_mtime(), get_birthtime(), epoch_to_date() wrappers",
       "(7) All-platform registry: 9 hooks, build-deploy.sh, init-logging.sh, check-lib.sh, aitools-lib.sh",
       "(8) Check script validation: registered scripts use wrappers not raw platform commands",
       "(9) Cross-compilation patterns from nobul-ops CI (4 targets)",
       "(10) Rust #[cfg], Go build tags, Python sys.platform documented with examples"],
      [{"name": "Platform engineering", "status": "proposed", "intent": {
          "purpose": "Govern platform correctness across the harness — what code runs on which platforms, how it handles platform differences, and how violations are prevented, detected, and audited. Maintain registries of all-platform scripts, known command divergences, and empirically verified install paths. Provide three-layer governance for platform concerns: prevention (rule + compat registry), detection (portability check scripts), audit (on-demand compliance review). Grounded in project mission: 'platform-native best practices — not artificial 1:1 parity'",
          "scope": "All aitools code: .sh/.ps1 pairs, all-platform bash (hooks, build-deploy), compiled language platform blocks (Rust #[cfg], Go build tags), scripting language checks (Python, Perl), CI cross-compilation, platform-native paths, package manager behaviors, and platform-specific implementation patterns in setup scripts (the HOW — not the WHAT, which is tool lifecycle), compatibility wrappers. Absorbs existing cross-platform rule and reference. NOT tool selection or install method evaluation (tool lifecycle — decides WHAT and WHICH method). NOT tool-specific operations (tool operations)",
          "audience": "Every agent writing code that runs on multiple platforms, in any project. User-level skill deployed to ~/.claude/skills/"}}],
      [{"path": ".claude/rules/cross-platform.md", "status": "existing"},
       {"path": "reference/cross-platform-detail.md", "status": "existing"},
       {"path": "scripts/aitools-lib.sh", "status": "existing"},
       {"path": "reference/framework-platform-engineering.md", "status": "proposed"},
       {"path": "reference/platform-compat.json", "status": "proposed"},
       {"path": "shared/skills/platform-engineering/SKILL.md", "status": "proposed"}],
      [{"name": "platformViolationRate", "source": "check script portability audit", "unit": "violations/release", "target": "0"},
       {"name": "allPlatformScriptCoverage", "source": "platform-compat.json registry", "unit": "percent", "target": "100% of all-platform scripts registered"},
       {"name": "wrapperAdoptionRate", "source": "grep for raw stat/date in registered scripts", "unit": "percent", "target": "100% use wrappers after migration"}],
      [9]),

    d(9,
      "Fix surfacing-duty-stop.sh: add uname dispatch for stat calls",
      "Lines 53/56 use stat -f (BSD-only). Windows Git Bash: GNU stat -f means --file-system. Crashes under set -u.",
      "Windows session: 'line 54: File: unbound variable.' b8a9ed4e: confirmed by reading source.",
      ["(1) Line 53: stat -f %m → get_mtime wrapper or inline uname dispatch",
       "(2) Line 56: stat -f %B → get_birthtime wrapper or inline uname dispatch",
       "(3) Hooks don't source aitools-lib.sh — need lightweight hook-utils.sh or inline dispatch",
       "(4) Test on both macOS and Windows Git Bash"],
      [{"name": "Platform engineering", "status": "proposed"}],
      [{"path": "shared/hooks/surfacing-duty-stop.sh", "status": "existing"}],
      [{"name": "stopHookCrashRate", "source": "hook error logs", "unit": "crashes/session", "target": "0 on all platforms"}],
      [8]),

    # === SESSION LIFECYCLE (continued) ===
    d(10,
      "Session ID and date derivation shared between hooks",
      "session-archive uses birth time, harvest uses current date. Produced mismatch: archive=2026-03-15, harvest=2026-03-16 for same session.",
      "b8a9ed4e: manifest 2026-03-16_eaacf9da vs archive 2026-03-15_eaacf9da. Session spanned midnight UTC.",
      ["(1) Session ID prefix: first 8 chars (already consistent)",
       "(2) Session date: standardize on transcript birth time (session start), not current date",
       "(3) Project name: basename of git root (already consistent)",
       "(4) Shared utility in aitools-lib.sh or dedicated hook-utils.sh",
       "(5) Update harvest-session.sh L56: replace date -u with birth-time-based date"],
      [{"name": "Session lifecycle", "status": "proposed"},
       {"name": "Artifact harvesting", "status": "existing"}],
      [{"path": "shared/hooks/session-archive.sh", "status": "existing"},
       {"path": "shared/hooks/harvest-session.sh", "status": "existing"}],
      [{"name": "dateDerivationMismatchRate", "source": "manifest vs archive audit", "unit": "mismatches/week", "target": "0"}],
      [1, 2]),

    d(11,
      "Fix harvest manifest: correct fake session ID and deduplicate",
      "Session fabricated 2Hb40B0VEu during harvest test. Real session: eaacf9da. Duplicates from re-harvesting.",
      "b8a9ed4e: traced fake ID. Manifest lines 57-78 (fake ID), lines 79-108 (duplicates).",
      ["(1) Change 2Hb40B0VEu to eaacf9da on 2 entries",
       "(2) Fix date: 2026-03-15 not 2026-03-16",
       "(3) Deduplicate lines 79-108 (re-harvested copies with generic descriptions)",
       "(4) Use /harvest skill (governed data)"],
      [{"name": "Artifact harvesting", "status": "existing"}],
      [{"path": "harvesting/harvest-manifest.json", "status": "existing"}],
      [{"name": "manifestIntegrityScore", "source": "harvest manifest audit", "unit": "issues", "target": "0 phantom IDs, 0 duplicates"}],
      [10]),

    # === INTENT DOCUMENTATION ===
    d(12,
      "Intent-writing skill must incorporate AAR patterns",
      "AAR L1122: user said skill isn't good enough, explicit instructions better. Weight by recency, multi-pass ambiguity removal, pre-write term audit.",
      "84280c8b: L1101 weight-by-recency, L1122 'my explicit instructions are better.' b8a9ed4e: 'generalize from the AAR.'",
      ["(1) Reference recent conversation history — more recent = more weight",
       "(2) Multi-pass ambiguity removal: 4 passes per AAR L1117",
       "(3) Pre-write governed term audit before writing",
       "(4) Read skill as reference but don't invoke mechanically",
       "(5) Match conciseness of existing governed JSON intents"],
      [{"name": "Intent documentation", "status": "existing"}],
      [{"path": "shared/skills/intent-writing/SKILL.md", "status": "existing"}],
      [{"name": "intentApprovalRounds", "source": "session transcript analysis", "unit": "rounds/batch", "target": "<= 1 (single-round approval)"},
       {"name": "intentCoverageRate", "source": "harness state audit", "unit": "percent", "target": ">= 90% files have intent"}],
      [13]),

    # === MISSION ANALYSIS ===
    d(13,
      "Adopt MDMP Mission Analysis as framework for pre-plan requirements enumeration",
      "Tool-ops plan: 7 rewrites because requirements surfaced during writing. AAR Lesson 1: 'Enumerate before writing.' This planning brief is the proof of concept.",
      "b8a9ed4e: user said 'this is a skill in itself.' Windows session recommended enumeration. This brief: 33 decisions, 15 facts, 6 assumptions — proof of concept.",
      ["(1) Planning brief schema: meta + facts + assumptions + decisions with KPIs",
       "(2) Decision capture during conversation — recognize resolved decision points",
       "(3) Review workflow: print human-readable, discuss, refine, re-audit",
       "(4) Plan-brief linkage: plan references its brief, executing agents read both",
       "(5) Quality checklist: 6 criteria (decision #21) applied before plan writing",
       "(6) /analyze skill: governed process for creating/maintaining briefs",
       "(7) Reference: framework-mission-analysis.md documenting MDMP adaptation"],
      [{"name": "Mission analysis", "status": "proposed", "intent": {
          "purpose": "Govern pre-plan requirements enumeration — capturing resolved decision points, facts, assumptions, and constraints before entering plan mode. Adapted from MDMP Step 2 and SRE production readiness reviews",
          "scope": "Planning brief schema, decision capture, plan-brief linkage, quality checklist. NOT plan writing. NOT plan execution. NOT delegation (mission command)",
          "audience": "Agents preparing to write a plan, users making decisions to capture before planning"}}],
      [{"path": ".claude/skills/analyze/SKILL.md", "status": "proposed"},
       {"path": "reference/framework-mission-analysis.md", "status": "proposed"}],
      [{"name": "planRewriteCount", "source": "plan revision history", "unit": "rewrites/plan", "target": "<= 2 (down from 7)"},
       {"name": "decisionQualityScore", "source": "6-criterion checklist audit", "unit": "criteria passed/6", "target": "6/6 for every decision"}],
      [12, 21]),

    d(14,
      "Scratch files must always be cleaned up — no orphaned session directories",
      "User directive. SessionEnd hook handles cleanup. SessionStart prunes >24 hours. Both must work cross-platform.",
      "b8a9ed4e: user said 'scratch files should always be cleaned up.'",
      ["(1) SessionEnd hook deletes session dir after classifying",
       "(2) SessionStart hook prunes >24h via find -mmin +1440 (POSIX, portable)",
       "(3) Edge case: crash without SessionEnd — SessionStart is safety net"],
      [{"name": "Artifact harvesting", "status": "existing"}],
      [{"path": "shared/hooks/scratch-init.sh", "status": "existing"},
       {"path": "shared/hooks/harvest-session.sh", "status": "existing"}],
      [{"name": "orphanedScratchDirs", "source": "SessionStart audit", "unit": "count", "target": "0"}],
      [1]),

    # === NAMING & GOVERNANCE ===
    d(15,
      "Framework name is 'Mission command' — encompasses delegation, communication, coordination, staff functions",
      "Evolved: Agent delegation -> Delegation protocol -> Mission command. The doctrine we're adapting IS Mission Command — covers delegation, comms, staff org, disciplined initiative.",
      "b8a9ed4e: user approved 'thats pretty damn beautiful.' Naming evolution captured across session.",
      ["(1) Add 'mission command' to governed vocabulary via /glossary",
       "(2) Update all references from prior names",
       "(3) Source: Mission Command (Auftragstaktik), FM 101-5-2/ABCS, OPORD/WARNORD/FRAGORD, S1-S3, AAR"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Governed vocabulary", "status": "existing"}],
      [{"path": "reference/glossary.json", "status": "existing"}],
      [],
      [3, 16]),

    d(16,
      "Naming conventions: frameworks 2+ word noun phrase, rules noun, skills verb, hooks descriptive",
      "Without conventions, names collide. Rules are governance only — no process, no howto. Skills and references are where actions/howtos live.",
      "b8a9ed4e: user said 'rules are just about governance' and 'i like having verbs for skills they imply action.'",
      ["(1) Document in reference/framework-governed-vocabulary.md",
       "(2) Add to .claude/rules/frameworks.md",
       "(3) Audit existing skills for verb/noun consistency",
       "(4) Add governed terms via /glossary"],
      [{"name": "Governed vocabulary", "status": "existing"}],
      [{"path": "reference/framework-governed-vocabulary.md", "status": "existing"},
       {"path": ".claude/rules/frameworks.md", "status": "existing"}],
      [{"name": "namingConventionCompliance", "source": "harness state audit", "unit": "percent", "target": "100% of new artifacts follow conventions"}],
      [15]),

    d(17,
      "New framework creation gatekept by /frameworks skill",
      "/frameworks skill provides governed process. Direct writes to framework-registry.json bypass the process.",
      "b8a9ed4e: user said 'any creation of a new framework would have to be gatekept by the framework skill.'",
      ["(1) All 4 proposed frameworks registered via /frameworks",
       "(2) Each requires: reference file exists, implementing artifacts exist, lastUpdated set"],
      [{"name": "Governed data access", "status": "existing"},
       {"name": "Framework adoption", "status": "existing"}],
      [{"path": ".claude/skills/frameworks/SKILL.md", "status": "existing"},
       {"path": "reference/framework-registry.json", "status": "existing"}],
      [{"name": "frameworkRegistrationCompliance", "source": "audit skill", "unit": "percent", "target": "100% frameworks registered via skill"}],
      [16]),

    d(18,
      "Plan subagent plan files should be archived or harvested",
      "Tool-ops plan at ~/.claude/plans/gleaming-cooking-unicorn.md — outside repo, outside dotprofile. Lost on machine change.",
      "b8a9ed4e: tracing session references for #4 revealed plan in Claude's local dir only.",
      ["(1) Option A: SessionEnd hook checks ~/.claude/plans/ and copies to .scratch/ for harvesting",
       "(2) Option B: /delegate instructs Plan subagents to write to .scratch/",
       "(3) Option C: /analyze copies to repo at plan-finalization",
       "(4) Evaluate best fit with existing patterns"],
      [{"name": "Session lifecycle", "status": "proposed"},
       {"name": "Artifact harvesting", "status": "existing"}],
      [{"path": "shared/hooks/harvest-session.sh", "status": "existing"}],
      [{"name": "planFilePreservationRate", "source": "harvest manifest audit", "unit": "percent", "target": "100% plans archived"}],
      [1, 2, 13]),

    d(19,
      "Delegation references must include session IDs for planning, execution, and subagent work",
      "Subagents start blank. Session references let executing agents trace full context.",
      "b8a9ed4e: user said 'referencing this session is important because of the limitations of our subagents: they start blank.'",
      ["(1) Planning conversation session ID",
       "(2) Plan file location",
       "(3) Executing conversation session ID",
       "(4) Subagent work products (AAR, test suites, reports)",
       "(5) Current session ID",
       "(6) /delegate template includes session references section"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Session lifecycle", "status": "proposed"}],
      [{"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"}],
      [{"name": "sessionReferenceCompleteness", "source": "delegation briefing audit", "unit": "references/delegation", "target": ">= 3 per delegation"}],
      [4, 7, 18]),

    d(20,
      "One hook per feature — new hooks for new capabilities, never conflate",
      "Single-responsibility hooks: easier to test, reason about, manage via tool-ops. One hook doing 5 things = one bug breaks 5 features.",
      "b8a9ed4e: user rejected extending block-claude-code-guide.sh — 'i dont like conflating hooks.'",
      ["(1) New capability = new hook in shared/hooks/",
       "(2) New hook = entry in tool-ops.json hooks array via /tool-ops",
       "(3) New hook = verification cases in tool-ops.json",
       "(4) Exception: extending existing only when explicitly stated",
       "(5) Document in tool-ops rule or hook-rollout rule"],
      [{"name": "Tool operations", "status": "existing"},
       {"name": "Hook rollout", "status": "existing"}],
      [{"path": ".claude/rules/tool-ops.md", "status": "existing"}],
      [{"name": "hookSingleResponsibilityScore", "source": "tool-ops.json audit", "unit": "features/hook", "target": "1"}],
      [5, 6]),

    d(21,
      "Every planning brief decision must pass 6-criterion quality checklist before plan is written",
      "Decision #4 improved from narrow/no-refs to exemplar through systematic improvement. Generalized into checklist: A(scope), B(source), C(components), D(current), E(merge), F(refs).",
      "b8a9ed4e: user asked to generalize improvement of #4. Audit: .scratch/session-952OZxWICI/decision-quality-audit.md",
      ["(1) A — Check scope: component of something larger?",
       "(2) B — Trace to source: session IDs, quotes, line numbers",
       "(3) C — Enumerate components: concrete sub-steps",
       "(4) D — Current-session discoveries: has concept grown?",
       "(5) E — Merge related: sub-components scattered?",
       "(6) F — Session references: planning, execution, work products"],
      [{"name": "Mission analysis", "status": "proposed"}],
      [{"path": ".claude/skills/analyze/SKILL.md", "status": "proposed"}],
      [{"name": "decisionQualityPassRate", "source": "checklist audit", "unit": "percent", "target": "100% pass all 6 before plan writing"}],
      [4, 13]),

    # === CHANNEL ===
    d(22,
      ".channel/ is a first-class directory for inter-agent communication, separate from .scratch/",
      "Channel messages have different lifecycle than scratch. Military ops journal is separate from working documents.",
      "b8a9ed4e: user said 'i want .channel directory... naming and pathing conventions and schemas and how this ties into harvesting.'",
      ["(1) .channel/ at repo root, gitignored",
       "(2) Session-scoped: .channel/session-XXXXXXXXXX/",
       "(3) File naming: {UTC-timestamp}_{agent-role-slugified}_{type}.json",
       "(4) channel-manifest.json per session dir — message index",
       "(5) SessionEnd hook: archive severity >= high to harvesting/, clean up rest",
       "(6) .channel/ in .gitignore",
       "(7) SessionStart hook: create session channel dir",
       "(8) Path in .channel/.current-session"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Artifact harvesting", "status": "existing"}],
      [{"path": ".channel/", "status": "proposed"}],
      [{"name": "channelOrphanRate", "source": "SessionStart audit", "unit": "orphaned dirs", "target": "0"},
       {"name": "highSeverityArchivalRate", "source": "SessionEnd hook logs", "unit": "percent", "target": "100% high+ findings archived"}],
      [23, 24, 25, 26, 14]),

    d(23,
      "/channel skill governs messaging with SITREP and FINDING (SALUTE-adapted) schemas",
      "Two message types: SITREP (status), FINDING (structured observation). FINDING severity=critical is the SPOTREP. Urgency in severity field.",
      "b8a9ed4e: adapted SITREP/SPOTREP/SALUTE from FM 101-5-2.",
      ["(1) SITREP: {type, agent, timestamp, batch, status, filesWritten, filesModified, summary}",
       "(2) FINDING (SALUTE): {type, severity, finding, location:{file,line}, agent, timestamp, context, actionTaken, recommendation}",
       "(3) /channel post --type sitrep: write SITREP",
       "(4) /channel post --type finding --severity <level>: write FINDING",
       "(5) /channel read: all messages, filterable by type/severity/agent",
       "(6) /channel status: summary counts",
       "(7) Auto-trigger: agents invoke without user prompting",
       "(8) channel-manifest.json tracks all messages per session"],
      [{"name": "Mission command", "status": "proposed"}],
      [{"path": ".claude/skills/channel/SKILL.md", "status": "proposed"},
       {"path": "reference/channel-schemas.json", "status": "proposed"},
       {"path": ".channel/session-XXX/channel-manifest.json", "status": "proposed"}],
      [{"name": "sitrepCompletionRate", "source": "channel-manifest.json", "unit": "percent", "target": "100% batches have SITREP"},
       {"name": "findingResolutionRate", "source": "S2 consolidation SITREP", "unit": "percent", "target": ">= 80% findings resolved by execution"}],
      [22, 24, 4]),

    d(24,
      "Agents are sensors not filers — findings flow channel -> S2 consolidation -> S1 incident filing",
      "Subagents filing incidents directly creates spam (batch 2 finds problem, batch 4 fixes it). S2 consolidates at plan end, delegates to S1 for filing only still-outstanding items.",
      "b8a9ed4e: user said 'the executing agent collects all incident reports and only files the one still outstanding at end of plan.' Also: 'delegate incident filing to a subagent.' Existing principle in incident-governance.md.",
      ["(1) During execution: agents post FINDINGs to .channel/. Never invoke /incident",
       "(2) Disciplined initiative: fix routine issues, report significant findings, don't make architectural decisions",
       "(3) Between batches: executing agent reads .channel/, adjusts next briefing",
       "(4) Plan completion: executing agent delegates to S2 (consolidation)",
       "(5) S2 reads all .channel/ findings, cross-references with completed batches, discards resolved",
       "(6) S2 delegates to S1 (incident filer) for each outstanding finding",
       "(7) S1 drafts incident via /incident, presents to user for approval",
       "(8) S2 posts final SITREP: 'N reviewed, M filed, K resolved'",
       "(9) Update incident-governance.md: replace 'report INCIDENT:' with 'post FINDING to /channel'"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Incident governance", "status": "existing"}],
      [{"path": ".claude/rules/incident-governance.md", "status": "existing"},
       {"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"}],
      [{"name": "falseIncidentRate", "source": "incident registry audit", "unit": "stale incidents filed during plan execution", "target": "0"},
       {"name": "consolidationCompleteness", "source": "S2 final SITREP", "unit": "percent findings reviewed", "target": "100%"}],
      [22, 23, 25, 26]),

    d(25,
      "Military staff functions (S1-S3) adapted as agent identities assigned by plan or executing agent",
      "Staff roles map to FUNCTIONS not titles. Each is an identity via delegation protocol. Plan writer assigns executing agent identity.",
      "b8a9ed4e: user asked 'how do we adapt the military identities for S3?' 84280c8b L1260: eliminated 'main agent.' AAR Rev 7: role-based identities.",
      ["(1) S3 (Operations) = executing agent / operations coordinator — assigned by plan writer",
       "(2) S2 (Intelligence) = consolidation agent — spawned at plan start (IPB) and plan end (consolidation)",
       "(3) S1 (Administration) = incident filer — delegated by S2 at plan end",
       "(4) Batch agents = role from briefing ('hook engineer for batch 7')",
       "(5) Plan writer assigns executing agent identity in preamble",
       "(6) These are functions not ranks — any agent can hold any function",
       "(7) A batch agent delegating sub-work assigns its own delegates' identities"],
      [{"name": "Mission command", "status": "proposed"}],
      [{"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"},
       {"path": "reference/framework-mission-command.md", "status": "proposed"}],
      [{"name": "identityAssignmentRate", "source": "delegation briefing audit", "unit": "percent", "target": "100% agents have identity"}],
      [3, 4, 7, 24, 26]),

    d(26,
      "S2 spawned at plan start (intelligence preparation) and plan end (findings consolidation)",
      "At start: reads brief, prior channel, known states → intelligence brief. At end: consolidates findings → delegates S1 for incident filing. S1 waits till end.",
      "b8a9ed4e: user said 'maybe the executing agent spawns an S2 subagent? the admin stuff, S1, can probably wait till the end no?'",
      ["(1) Plan start: executing agent delegates to S2 (intelligence preparation)",
       "(2) S2 start mission: read brief, prior .channel/, known states → intelligence brief",
       "(3) S2 returns brief. Executing agent absorbs it, starts batch 1",
       "(4) Between batches: executing agent reads channel itself (lightweight)",
       "(5) Plan completion: executing agent delegates to S2 again (consolidation)",
       "(6) S2 consolidation: read .channel/, cross-reference, discard resolved, prepare outstanding briefs",
       "(7) S2 delegates to S1 for each outstanding finding",
       "(8) S1 waits till end — no admin overhead during execution"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Mission analysis", "status": "proposed"}],
      [{"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"}],
      [{"name": "intelligencePrepTime", "source": "S2 SITREP at start", "unit": "seconds", "target": "< 120"},
       {"name": "consolidationCompletionRate", "source": "S2 final SITREP", "unit": "percent", "target": "100% plans have S2 consolidation"}],
      [24, 25, 4]),

    d(27,
      "FRAGORD is kill-and-replace — terminate stale delegation and reissue",
      "No mid-execution updates possible. FRAGORD = wait for/kill current agent, create new with updated briefing including original OPORD + deviations + new findings.",
      "b8a9ed4e: identified during military protocol analysis. Architectural constraint: no mid-execution communication.",
      ["(1) Executing agent monitors channel and user interrupts between delegations",
       "(2) If findings change plan: don't delegate next batch with stale orders",
       "(3) If current agent running and orders invalidated: user interrupts, new delegation created",
       "(4) New briefing: original plan + all deviations + new findings + explanation of change",
       "(5) /delegate skill: 'before each delegation, check if findings invalidate planned briefing'",
       "(6) Sequential order revision, not real-time FRAGORD"],
      [{"name": "Mission command", "status": "proposed"}],
      [{"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"}],
      [{"name": "staleOrderDelegationRate", "source": "delegation audit", "unit": "percent", "target": "0% delegations with stale orders"}],
      [4, 7, 25]),

    d(28,
      "Plans must pre-draft all intents before delegation, present consolidated for single-round approval",
      "Tool-ops batch 1: 15 min, 3+ rounds. Batch 5: 'beautiful', 42 sec. User can only approve/deny subagent tool calls — no feedback channel.",
      "eaacf9da L149: 'every file that needs an intent must have it drafted and approved before I delegate.' Report: .scratch/session-952OZxWICI/intent-approval-evolution.md",
      ["(1) Plans enumerate intent-requiring files per batch",
       "(2) Executing agent drafts all intents BEFORE delegating",
       "(3) Present as consolidated batch for single-round approval",
       "(4) Delegated agent receives verbatim approved text",
       "(5) Track approval: Approved / Pending / Draft table",
       "(6) If changes requested: revise and re-present before delegating"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Intent documentation", "status": "existing"},
       {"name": "Mission analysis", "status": "proposed"}],
      [{"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"}],
      [{"name": "intentApprovalRoundsPerBatch", "source": "session transcript", "unit": "rounds", "target": "1"},
       {"name": "intentApprovalTime", "source": "session transcript", "unit": "seconds", "target": "< 120"}],
      [4, 12, 13]),

    # === CRITICAL BLOCKING ===
    d(29,
      "Critical facts (blocksPlanning=true) must be resolved before plan writing begins",
      "Two skills broken right now. Don't start mission with broken comms. S2 intelligence prep would discover these but we already know them.",
      "b8a9ed4e: S2 investigation revealed F1 and F2. User: 'all critical items done first, block until S1/S2 give clear.'",
      ["(1) Fix F1: tool-registry SKILL.md → point to tool-registry.md (RCA Option A)",
       "(2) Fix F2: harvest SKILL.md → harvesting/harvest-manifest.json (correct directory)",
       "(3) Fix F3: frameworks.md registries table → reference skill not phantom path",
       "(4) Verify: invoke /tool-registry and /harvest after fixes",
       "(5) Only after S2 confirms all critical facts resolved: proceed to plan"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Incident governance", "status": "existing"}],
      [{"path": ".claude/skills/tool-registry/SKILL.md", "status": "existing"},
       {"path": ".claude/skills/harvest/SKILL.md", "status": "existing"},
       {"path": ".claude/rules/frameworks.md", "status": "existing"}],
      [{"name": "criticalFactResolutionTime", "source": "session timestamp", "unit": "minutes", "target": "< 30 from identification to fix"}],
      [26]),

    d(30,
      "Every plan completion includes incident registry audit by S2, delegated to S1 for cleanup",
      "Plan execution changes code, silently resolving incidents. Without post-execution audit, registry drifts. S2 does both: consolidate new + audit existing.",
      "b8a9ed4e: audit found 14 closeable incidents. User: 'probably something every plan should include.'",
      ["(1) Standard plan completion: executing agent delegates to S2",
       "(2) S2 mission expands: (a) consolidate channel findings, (b) audit existing incident registry",
       "(3) Silently resolved: S2 prepares close briefs → S1",
       "(4) Stale/duplicate: S2 prepares close briefs with rationale → S1",
       "(5) New outstanding: S2 prepares filing briefs → S1",
       "(6) S1 files new + closes resolved via /incident with user approval",
       "(7) Document in /delegate plan completion checklist",
       "(8) Document in delegation rule trigger directive"],
      [{"name": "Mission command", "status": "proposed"},
       {"name": "Incident governance", "status": "existing"}],
      [{"path": ".claude/skills/delegate/SKILL.md", "status": "proposed"},
       {"path": ".claude/rules/delegation.md", "status": "proposed"}],
      [{"name": "incidentRegistryDriftRate", "source": "S2 audit at plan end", "unit": "stale incidents found", "target": "trending to 0"},
       {"name": "registryCleanupCompletionRate", "source": "S2 final SITREP", "unit": "percent", "target": "100% plans include registry audit"}],
      [24, 25, 26]),

    # === PLATFORM ENGINEERING (updated scope) ===
    d(31,
      "Platform engineering scope: all aitools code, all languages, user-level, three-layer governance for platform correctness",
      "Project mission: 'cross-platform tool lifecycle management.' Platform engineering is core capability provided to users. Covers .sh/.ps1, Rust #[cfg], Go build tags, Python, Perl, CI, paths.",
      "b8a9ed4e: user rejected 'portable scripting' as narrow. nobul-ops audit: 10 Rust blocks, 4 CI targets. CLAUDE.md: 'platform-native best practices — not artificial 1:1 parity.'",
      ["(1) Absorbs cross-platform.md as rule",
       "(2) Absorbs cross-platform-detail.md as reference",
       "(3) New framework-platform-engineering.md with Rust/Go/Python/Perl patterns",
       "(4) New platform-compat.json — divergence + all-platform script registry",
       "(5) New shared/skills/platform-engineering/SKILL.md — USER-LEVEL",
       "(6) Wrappers in aitools-lib.sh: get_mtime(), get_birthtime(), epoch_to_date()",
       "(7) All-platform registry: 9 hooks + build-deploy + init-logging + check-lib + aitools-lib",
       "(8) Check script: validate registered scripts use wrappers",
       "(9) CI patterns from nobul-ops (4 targets, platform-aware packaging)",
       "(10) Three-layer: prevention (rule+compat), detection (check scripts), audit (skill)"],
      [{"name": "Platform engineering", "status": "proposed"}],
      [{"path": ".claude/rules/cross-platform.md", "status": "existing"},
       {"path": "reference/cross-platform-detail.md", "status": "existing"},
       {"path": "reference/framework-platform-engineering.md", "status": "proposed"},
       {"path": "reference/platform-compat.json", "status": "proposed"},
       {"path": "shared/skills/platform-engineering/SKILL.md", "status": "proposed"}],
      [{"name": "crossPlatformTestCoverage", "source": "CI build results", "unit": "platforms tested per release", "target": ">= 2 (macOS + Windows)"},
       {"name": "platformCompatRegistryCoverage", "source": "platform-compat.json", "unit": "percent known divergences documented", "target": "100%"}],
      [8, 9]),

    # === DATADOG & AUTH0 ===
    d(32,
      "KPIs ship to Datadog via log_ship — the telemetry pipeline for all framework effectiveness measurement",
      "Governance plan decision #13: 'Local SQLite + Datadog for KPIs.' Every decision in this brief has KPIs. Those KPIs need a delivery mechanism. log_ship is designed (plans/datadog-log-integration.md) but not built. Building it is a prerequisite for measuring any framework's effectiveness.",
      "b8a9ed4e: added KPIs to all decisions. plans/datadog-log-integration.md: 5 phases, log_ship conceptual code. plans/governance-and-compliance-framework.md decision #13.",
      ["(1) Build log_ship in aitools-lib.sh — POST JSON batch to Datadog HTTP Logs API at script exit",
       "(2) Build LogShip in aitools-lib.ps1 — Invoke-RestMethod equivalent",
       "(3) Build local SQLite store: ~/.aitools/telemetry/governance.db (WAL mode)",
       "(4) SessionEnd hook: ship accumulated KPIs from SQLite to Datadog",
       "(5) Channel KPIs: message counts, SITREP/FINDING ratios, consolidation completeness",
       "(6) Delegation KPIs: compliance rate, component coverage, agent type mismatches",
       "(7) Platform KPIs: violation rate, wrapper adoption, all-platform coverage",
       "(8) Opt-in: only ships if datadogApiKey configured (no-op otherwise)",
       "(9) Graceful: network failures logged locally, never abort script"],
      [{"name": "Tool operations", "status": "existing"}],
      [{"path": "scripts/aitools-lib.sh", "status": "existing"},
       {"path": "scripts/aitools-lib.ps1", "status": "existing"},
       {"path": "plans/datadog-log-integration.md", "status": "existing"}],
      [{"name": "logShipSuccessRate", "source": "log_ship function logs", "unit": "percent", "target": ">= 95%"},
       {"name": "kpiDeliveryLatency", "source": "Datadog intake timestamps", "unit": "seconds", "target": "< 30"}],
      [33]),

    d(33,
      "Auth0 manages datadogApiKey and other provider credentials — centralized credential management",
      "datadogApiKey currently in plain config.json (F15). Auth0 plan Phase 2 moves Datadog + Vercel credentials to Auth0 token management. aitools auth CLI resolves incident #23 (keychain prompts block install).",
      "b8a9ed4e: read Auth0 plan. plans/nobul-auth0-platform.md: 5 phases. datadogApiKey integration is Phase 2. Incident #23: credential storage undocumented.",
      ["(1) Phase 1 (GitHub): aitools auth login → device flow → GH_TOKEN export → no keychain",
       "(2) Phase 2 (Datadog+Vercel): Auth0 stores IdP tokens → DD_ACCESS_TOKEN, VERCEL_TOKEN exports",
       "(3) log_ship reads credential from Auth0-managed token (Phase 2) or config.json (Phase 1 fallback)",
       "(4) Token storage: ~/.aitools/auth/ with 600 permissions, NOT in dotprofile",
       "(5) Shell integration: eval $(aitools auth env) exports all provider tokens",
       "(6) Auth0 dependency: startup plan provisioned, custom domain auth.nobul.tech"],
      [{"name": "Tool lifecycle", "status": "existing"}],
      [{"path": "plans/nobul-auth0-platform.md", "status": "existing"},
       {"path": "scripts/aitools-auth.sh", "status": "proposed"},
       {"path": "scripts/aitools-auth.ps1", "status": "proposed"}],
      [{"name": "keychainPromptRate", "source": "install logs", "unit": "prompts/install", "target": "0 after Auth0 Phase 1"},
       {"name": "credentialExpiryRate", "source": "aitools auth status", "unit": "expired tokens", "target": "0 (auto-refresh)"}],
      [32]),
]

brief["decisions"] = decisions

# Write
out_path = "/Users/pepe/repos/aitools/.scratch/session-952OZxWICI/planning-brief.json"
with open(out_path, "w") as f:
    json.dump(brief, f, indent=2, ensure_ascii=False)
    f.write("\n")

print(f"Written {len(decisions)} decisions, {len(brief['facts'])} facts, {len(brief['assumptions'])} assumptions to {out_path}")
