#!/usr/bin/env bash
# build-deploy.sh — Generates self-contained deploy/ scripts from scripts/ + shared/
#
# Reads shared content files and embeds them into deploy versions of setup scripts.
# The deploy/ scripts have zero dependencies on the repo or Google Drive — they can
# be deployed to any endpoint via MDM (Jamf, Intune) or run manually.
#
# Usage: bash scripts/build-deploy.sh   (run from repo root)
#
# CROSS-PLATFORM NOTE: This script is intentionally bash-only (no .ps1 variant).
# It's a build step that produces platform-independent output (both .sh and .ps1
# deploy scripts). The result is committed to git, so both platforms get identical
# deploy/ contents. A parallel PS1 would double maintenance for no output difference.
# On Windows, aitools.ps1 invokes this via Git Bash (a prerequisite for Claude Code).
# See .claude/rules/cross-platform.md "Approved exceptions" for the exception record.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPTS_DIR="$REPO_ROOT/scripts"
DEPLOY_DIR="$REPO_ROOT/deploy"
SHARED_DIR="$REPO_ROOT/shared"

# Shared content files
CLAUDE_SHARED="$SHARED_DIR/claude-shared.md"
USER_RULES="$SHARED_DIR/cursor-rules/user-rules.md"

# Verify shared files exist
for f in "$CLAUDE_SHARED" "$USER_RULES"; do
    if [ ! -f "$f" ]; then
        echo "Error: Required shared file not found: $f" >&2
        exit 1
    fi
done

# Read shared content
CLAUDE_SHARED_CONTENT=$(cat "$CLAUDE_SHARED")
USER_RULES_CONTENT=$(cat "$USER_RULES")

# Clean and recreate deploy/
rm -rf "$DEPLOY_DIR"
mkdir -p "$DEPLOY_DIR"

GENERATED=0

# Header for generated files
HEADER_COMMENT_BASH="# Generated by scripts/build-deploy.sh — do not edit directly."
HEADER_COMMENT_PS1="# Generated by scripts/build-deploy.sh — do not edit directly."

# ============================================================
# Bash logging helpers (embedded into each bash deploy script)
# ============================================================
bash_logging_helpers() {
    local script_name="$1"
    cat <<'LOGGING_BASH'
# --- Logging ---
LOG_DIR="$HOME/Library/Logs/ai-tooling"
[ "$(uname -s)" != "Darwin" ] && LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/ai-tooling"
LOG_FILE="$LOG_DIR/deploy.log"
LOGGING_BASH
    echo "SCRIPT_NAME=\"$script_name\""
    cat <<'LOGGING_BASH'
ERRORS=0

mkdir -p "$LOG_DIR"

log()       { printf '[%s] [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$SCRIPT_NAME" "$1" | tee -a "$LOG_FILE"; }
log_ok()    { log "OK: $1"; }
log_error() { log "ERROR: $1"; ERRORS=$((ERRORS + 1)); }
log_warn()  { log "WARN: $1"; }
LOGGING_BASH
}

# PowerShell logging helpers
ps1_logging_helpers() {
    local script_name="$1"
    cat <<LOGGING_PS1
# --- Logging ---
\$logDir = Join-Path \$env:LOCALAPPDATA "ai-tooling"
\$logFile = Join-Path \$logDir "deploy.log"
\$scriptName = "$script_name"
\$errors = 0

if (-not (Test-Path \$logDir)) { New-Item -ItemType Directory -Path \$logDir -Force | Out-Null }

function Log(\$msg) {
    \$ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    \$line = "[\$ts] [\$scriptName] \$msg"
    Write-Host \$line
    Add-Content -Path \$logFile -Value \$line
}
function LogOk(\$msg)    { Log "OK: \$msg" }
function LogError(\$msg) { Log "ERROR: \$msg"; \$script:errors++ }
function LogWarn(\$msg)  { Log "WARN: \$msg" }
LOGGING_PS1
}

# Bash exit footer
bash_exit_footer() {
    cat <<'EXIT_BASH'

# --- Exit ---
if [ "$ERRORS" -gt 0 ]; then
    log "FAILED with $ERRORS error(s). See log: $LOG_FILE"
    exit 1
else
    log "COMPLETED successfully"
    exit 0
fi
EXIT_BASH
}

# PowerShell exit footer
ps1_exit_footer() {
    cat <<'EXIT_PS1'

# --- Exit ---
if ($errors -gt 0) {
    Log "FAILED with $errors error(s). See log: $logFile"
    exit 1
} else {
    Log "COMPLETED successfully"
    exit 0
}
EXIT_PS1
}

# ============================================================
# Backup helpers (embedded into deploy scripts that overwrite files)
# ============================================================
bash_backup_helper() {
    cat <<'BACKUP_BASH'

# Backup a file before overwriting. Keeps at most $max_backups copies.
backup_file() {
    local file="$1" max_backups=20
    [ -f "$file" ] || return 0
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    cp "$file" "${file}.bak.${ts}"
    # Prune oldest beyond limit
    ls -1t "${file}.bak."* 2>/dev/null | tail -n +$((max_backups + 1)) | xargs rm -f 2>/dev/null
    log "Backed up $file"
}
BACKUP_BASH
}

ps1_backup_helper() {
    cat <<'BACKUP_PS1'

# Backup a file before overwriting. Keeps at most $MaxBackups copies.
function Backup-File {
    param([string]$FilePath, [int]$MaxBackups = 20)
    if (-not (Test-Path $FilePath)) { return }
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHHmmssZ")
    $backupPath = "${FilePath}.bak.${ts}"
    Copy-Item -Path $FilePath -Destination $backupPath
    # Prune oldest beyond limit
    $backups = Get-ChildItem -Path "${FilePath}.bak.*" | Sort-Object LastWriteTime -Descending
    if ($backups.Count -gt $MaxBackups) {
        $backups | Select-Object -Skip $MaxBackups | Remove-Item -Force
    }
    Log "Backed up $FilePath"
}
BACKUP_PS1
}

# ============================================================
# OS guard helpers (embedded into template-generated deploy scripts)
# ============================================================
bash_os_guard() {
    cat <<'OS_GUARD_BASH'

# --- OS guard ---
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        log_error "This script is for macOS/Linux. On Windows, use the .ps1 version."
        exit 1 ;;
esac
OS_GUARD_BASH
}

ps1_os_guard() {
    cat <<'OS_GUARD_PS1'

# --- OS guard ---
if ($PSVersionTable.PSVersion.Major -ge 6 -and -not $IsWindows) {
    LogError "This script is for Windows. On macOS/Linux, use the .sh version."
    exit 1
}
OS_GUARD_PS1
}

# ============================================================
# 1. deploy/setup-user-claude.sh
# ============================================================
echo "Generating deploy/setup-user-claude.sh ..."

{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    cat <<'BLOCK'
# setup-user-claude.sh — Creates user-level ~/.claude/CLAUDE.md
# Self-contained: shared preferences are embedded below. No repo or Drive needed.
# Safe to re-run — replaces existing file with latest version.

set -euo pipefail

BLOCK
    bash_logging_helpers "setup-user-claude"
    bash_os_guard
    bash_backup_helper
    cat <<'BLOCK'

# --- Auto-detect machine info ---
OS_NAME=$(uname -s)
ARCH=$(uname -m)
HOSTNAME=$(hostname -s 2>/dev/null || hostname)
SHELL_NAME=$(basename "${SHELL:-/bin/bash}")

CLAUDE_DIR="$HOME/.claude"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"

mkdir -p "$CLAUDE_DIR"
log "Ensuring $CLAUDE_DIR exists"

backup_file "$CLAUDE_MD"
if [ -f "$CLAUDE_MD" ]; then
    rm "$CLAUDE_MD"
    log "Removed existing $CLAUDE_MD"
fi

# --- Embedded shared preferences (from shared/claude-shared.md) ---
BLOCK
    echo 'read -r -d "" SHARED_CONTENT <<'"'"'__EMBEDDED_CLAUDE_SHARED__'"'"' || true'
    echo "$CLAUDE_SHARED_CONTENT"
    echo '__EMBEDDED_CLAUDE_SHARED__'
    cat <<'BLOCK'

# --- Write CLAUDE.md ---
cat > "$CLAUDE_MD" << CLAUDE_EOF
${SHARED_CONTENT}

## Machine-Specific

- Machine: ${OS_NAME} ${ARCH} (${HOSTNAME})
- Shell: ${SHELL_NAME}
CLAUDE_EOF

log_ok "Wrote $CLAUDE_MD"
log "Machine: $OS_NAME $ARCH ($HOSTNAME), Shell: $SHELL_NAME"
BLOCK
    bash_exit_footer
} > "$DEPLOY_DIR/setup-user-claude.sh"

chmod +x "$DEPLOY_DIR/setup-user-claude.sh"
GENERATED=$((GENERATED + 1))

# ============================================================
# 2. deploy/setup-user-claude.ps1
# ============================================================
echo "Generating deploy/setup-user-claude.ps1 ..."

{
    echo "$HEADER_COMMENT_PS1"
    cat <<'BLOCK'
# setup-user-claude.ps1 — Creates user-level ~/.claude/CLAUDE.md on Windows
# Self-contained: shared preferences are embedded below. No repo or Drive needed.
# Safe to re-run — replaces existing file with latest version.

BLOCK
    ps1_logging_helpers "setup-user-claude"
    ps1_os_guard
    ps1_backup_helper
    cat <<'BLOCK'

# --- Auto-detect machine info ---
$osInfo = (Get-CimInstance Win32_OperatingSystem).Caption
$hostname = $env:COMPUTERNAME

$claudeDir = Join-Path $env:USERPROFILE ".claude"
$claudeMd = Join-Path $claudeDir "CLAUDE.md"

if (-not (Test-Path $claudeDir)) {
    New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null
    Log "Created $claudeDir"
}

Backup-File -FilePath $claudeMd
if (Test-Path $claudeMd) {
    Remove-Item $claudeMd
    Log "Removed existing $claudeMd"
}

# --- Embedded shared preferences (from shared/claude-shared.md) ---
$sharedContent = @'
BLOCK
    echo "$CLAUDE_SHARED_CONTENT"
    cat <<'BLOCK'
'@

# --- Write CLAUDE.md ---
$content = @"
$sharedContent

## Machine-Specific

- Machine: $osInfo ($hostname)
- Shell: bash (Claude Code requires Git Bash on Windows)
"@

[System.IO.File]::WriteAllText($claudeMd, $content, [System.Text.UTF8Encoding]::new($false))
LogOk "Wrote $claudeMd"
Log "Machine: $osInfo ($hostname)"
BLOCK
    ps1_exit_footer
} > "$DEPLOY_DIR/setup-user-claude.ps1"

GENERATED=$((GENERATED + 1))

# ============================================================
# 3. deploy/setup-user-cursor.sh
# ============================================================
echo "Generating deploy/setup-user-cursor.sh ..."

{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    cat <<'BLOCK'
# setup-user-cursor.sh — Sets up Cursor CLI + dependencies on macOS/Linux
# Self-contained: User Rules content is embedded below. No repo or Drive needed.
# Safe to re-run — checks each step and skips what's already done.
#
# Does four things:
#   1. Installs ripgrep (rg) if not already present (required by Cursor CLI)
#   2. Installs Cursor CLI (agent command) if not already present
#   3. Writes ~/.cursor/cli-config.json (skips if already up to date)
#   4. Copies embedded User Rules to clipboard for pasting into Cursor Settings > Rules

set -euo pipefail

BLOCK
    bash_logging_helpers "setup-user-cursor"
    bash_os_guard
    cat <<'BLOCK'

CURSOR_DIR="$HOME/.cursor"
CLI_CONFIG="$CURSOR_DIR/cli-config.json"

# --- 1. ripgrep (rg) ---
log "Step 1: ripgrep (rg)"

if command -v rg &>/dev/null; then
    RG_VERSION=$(rg --version | head -1)
    log_ok "Already installed: $RG_VERSION"
else
    if command -v brew &>/dev/null; then
        log "Installing ripgrep via brew..."
        brew install ripgrep
        if command -v rg &>/dev/null; then
            log_ok "Installed: $(rg --version | head -1)"
        else
            log_error "brew install completed but 'rg' not found in PATH"
        fi
    else
        log_error "Homebrew not found. Install ripgrep manually: brew install ripgrep"
    fi
fi

# --- 2. Cursor CLI (agent) ---
log "Step 2: Cursor CLI (agent)"

if command -v agent &>/dev/null; then
    AGENT_VERSION=$(agent --version)
    log_ok "Already installed: $AGENT_VERSION"
else
    log "Installing Cursor CLI..."
    curl https://cursor.com/install -fsS | bash
    if command -v agent &>/dev/null; then
        log_ok "Installed: $(agent --version)"
    else
        log_error "Cursor CLI install completed but 'agent' not found in PATH (restart terminal)"
    fi
fi

# --- 3. cli-config.json ---
log "Step 3: cli-config.json"

EXPECTED_CONFIG='{
  "version": 1,
  "editor": {
    "vimMode": false
  },
  "permissions": {
    "allow": [],
    "deny": []
  }
}'

mkdir -p "$CURSOR_DIR"

if [ -f "$CLI_CONFIG" ]; then
    EXISTING_CONFIG=$(cat "$CLI_CONFIG")
    if [ "$EXISTING_CONFIG" = "$EXPECTED_CONFIG" ]; then
        log_ok "Already up to date: $CLI_CONFIG"
    else
        printf '%s' "$EXPECTED_CONFIG" > "$CLI_CONFIG"
        log_ok "Updated: $CLI_CONFIG"
    fi
else
    printf '%s' "$EXPECTED_CONFIG" > "$CLI_CONFIG"
    log_ok "Created: $CLI_CONFIG"
fi

# --- 4. User Rules ---
log "Step 4: User Rules (embedded)"

# --- Embedded User Rules (from shared/cursor-rules/user-rules.md) ---
BLOCK
    echo 'read -r -d "" USER_RULES_CONTENT <<'"'"'__EMBEDDED_USER_RULES__'"'"' || true'
    echo "$USER_RULES_CONTENT"
    echo '__EMBEDDED_USER_RULES__'
    cat <<'BLOCK'

if [ -t 1 ]; then
    # Interactive: copy to clipboard
    if command -v pbcopy &>/dev/null; then
        printf '%s' "$USER_RULES_CONTENT" | pbcopy
        log_ok "Copied User Rules to clipboard"
    elif command -v xclip &>/dev/null; then
        printf '%s' "$USER_RULES_CONTENT" | xclip -selection clipboard
        log_ok "Copied User Rules to clipboard (xclip)"
    else
        log_warn "No clipboard command found (pbcopy/xclip). Copy manually from log."
    fi
    log "Paste User Rules into: Cursor Settings > Rules"
else
    # Non-interactive: skip clipboard
    log_ok "User Rules embedded and ready"
fi
BLOCK
    bash_exit_footer
} > "$DEPLOY_DIR/setup-user-cursor.sh"

chmod +x "$DEPLOY_DIR/setup-user-cursor.sh"
GENERATED=$((GENERATED + 1))

# ============================================================
# 4. deploy/setup-user-cursor.ps1
# ============================================================
echo "Generating deploy/setup-user-cursor.ps1 ..."

{
    echo "$HEADER_COMMENT_PS1"
    cat <<'BLOCK'
# setup-user-cursor.ps1 — Sets up Cursor CLI + dependencies on Windows
# Self-contained: User Rules content is embedded below. No repo or Drive needed.
# Safe to re-run — checks each step and skips what's already done.
#
# Does four things:
#   1. Installs ripgrep (rg) if not already present (required by Cursor CLI)
#   2. Installs Cursor CLI (agent command) if not already present
#   3. Writes ~/.cursor/cli-config.json (skips if already up to date)
#   4. Copies embedded User Rules to clipboard for pasting into Cursor Settings > Rules

BLOCK
    ps1_logging_helpers "setup-user-cursor"
    ps1_os_guard
    cat <<'BLOCK'

# Helper: refresh PATH from registry (picks up winget installs in same session)
function Refresh-Path {
    $machinePath = [Environment]::GetEnvironmentVariable("Path", "Machine")
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    $env:Path = "$machinePath;$userPath"
}

$cursorDir = Join-Path $env:USERPROFILE ".cursor"
$cliConfig = Join-Path $cursorDir "cli-config.json"

# --- 1. ripgrep (rg) ---
Log "Step 1: ripgrep (rg)"

$rgCmd = Get-Command rg -ErrorAction SilentlyContinue
if ($rgCmd) {
    $rgVersion = (rg --version | Select-Object -First 1)
    LogOk "Already installed: $rgVersion"
} else {
    Log "Installing ripgrep via winget..."
    winget install BurntSushi.ripgrep.MSVC --accept-package-agreements --accept-source-agreements
    Refresh-Path
    $rgCmd = Get-Command rg -ErrorAction SilentlyContinue
    if ($rgCmd) {
        LogOk "Installed: $(rg --version | Select-Object -First 1)"
    } else {
        LogError "winget install completed but 'rg' not found in PATH (restart terminal)"
    }
}

# --- 2. Cursor CLI (agent) ---
Log "Step 2: Cursor CLI (agent)"

$agentCmd = Get-Command agent -ErrorAction SilentlyContinue
if ($agentCmd) {
    $agentVersion = agent --version
    LogOk "Already installed: $agentVersion"
} else {
    Log "Installing Cursor CLI..."
    Invoke-Expression (Invoke-RestMethod 'https://cursor.com/install?win32=true')
    $agentCmd = Get-Command agent -ErrorAction SilentlyContinue
    if ($agentCmd) {
        LogOk "Installed: $(agent --version)"
    } else {
        LogError "Cursor CLI install completed but 'agent' not found in PATH (restart terminal)"
    }
}

# --- 3. cli-config.json ---
Log "Step 3: cli-config.json"

$expectedConfig = @'
{
  "version": 1,
  "editor": {
    "vimMode": false
  },
  "permissions": {
    "allow": [],
    "deny": []
  }
}
'@

if (-not (Test-Path $cursorDir)) {
    New-Item -ItemType Directory -Path $cursorDir -Force | Out-Null
    Log "Created $cursorDir"
}

if (Test-Path $cliConfig) {
    $existingConfig = (Get-Content -Path $cliConfig -Raw).TrimEnd()
    if ($existingConfig -eq $expectedConfig) {
        LogOk "Already up to date: $cliConfig"
    } else {
        [System.IO.File]::WriteAllText($cliConfig, $expectedConfig, [System.Text.UTF8Encoding]::new($false))
        LogOk "Updated: $cliConfig"
    }
} else {
    [System.IO.File]::WriteAllText($cliConfig, $expectedConfig, [System.Text.UTF8Encoding]::new($false))
    LogOk "Created: $cliConfig"
}

# --- 4. User Rules ---
Log "Step 4: User Rules (embedded)"

# --- Embedded User Rules (from shared/cursor-rules/user-rules.md) ---
$userRulesContent = @'
BLOCK
    echo "$USER_RULES_CONTENT"
    cat <<'BLOCK'
'@

if (-not $env:AITOOLS_DEPLOY) {
    Set-Clipboard -Value $userRulesContent
    LogOk "Copied User Rules to clipboard"
    Log "Paste into: Cursor Settings > Rules"
} else {
    LogOk "User Rules embedded and ready"
}
BLOCK
    ps1_exit_footer
} > "$DEPLOY_DIR/setup-user-cursor.ps1"

GENERATED=$((GENERATED + 1))

# ============================================================
# 5-6. deploy/setup-cursor-mcp.sh and .ps1 (copy as-is)
# ============================================================
echo "Copying deploy/setup-cursor-mcp.sh ..."
{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    # Strip the shebang from source and append the rest
    tail -n +2 "$SCRIPTS_DIR/setup-cursor-mcp.sh"
} > "$DEPLOY_DIR/setup-cursor-mcp.sh"
chmod +x "$DEPLOY_DIR/setup-cursor-mcp.sh"
GENERATED=$((GENERATED + 1))

echo "Copying deploy/setup-cursor-mcp.ps1 ..."
{
    echo "$HEADER_COMMENT_PS1"
    cat "$SCRIPTS_DIR/setup-cursor-mcp.ps1"
} > "$DEPLOY_DIR/setup-cursor-mcp.ps1"
GENERATED=$((GENERATED + 1))

# ============================================================
# 7-8. deploy/setup-vercelcli.sh and .ps1 (copy as-is)
# ============================================================
echo "Copying deploy/setup-vercelcli.sh ..."
{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    # Strip the shebang from source and append the rest
    tail -n +2 "$SCRIPTS_DIR/setup-vercelcli.sh"
} > "$DEPLOY_DIR/setup-vercelcli.sh"
chmod +x "$DEPLOY_DIR/setup-vercelcli.sh"
GENERATED=$((GENERATED + 1))

echo "Copying deploy/setup-vercelcli.ps1 ..."
{
    echo "$HEADER_COMMENT_PS1"
    cat "$SCRIPTS_DIR/setup-vercelcli.ps1"
} > "$DEPLOY_DIR/setup-vercelcli.ps1"
GENERATED=$((GENERATED + 1))

# ============================================================
# 9-10. deploy/setup-pandoc.sh and .ps1 (copy as-is)
# ============================================================
echo "Copying deploy/setup-pandoc.sh ..."
{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    # Strip the shebang from source and append the rest
    tail -n +2 "$SCRIPTS_DIR/setup-pandoc.sh"
} > "$DEPLOY_DIR/setup-pandoc.sh"
chmod +x "$DEPLOY_DIR/setup-pandoc.sh"
GENERATED=$((GENERATED + 1))

echo "Copying deploy/setup-pandoc.ps1 ..."
{
    echo "$HEADER_COMMENT_PS1"
    cat "$SCRIPTS_DIR/setup-pandoc.ps1"
} > "$DEPLOY_DIR/setup-pandoc.ps1"
GENERATED=$((GENERATED + 1))

# ============================================================
# 11-12. deploy/setup-user-mcp.sh and .ps1 (copy as-is)
# ============================================================
echo "Copying deploy/setup-user-mcp.sh ..."
{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    # Strip the shebang from source and append the rest
    tail -n +2 "$SCRIPTS_DIR/setup-user-mcp.sh"
} > "$DEPLOY_DIR/setup-user-mcp.sh"
chmod +x "$DEPLOY_DIR/setup-user-mcp.sh"
GENERATED=$((GENERATED + 1))

echo "Copying deploy/setup-user-mcp.ps1 ..."
{
    echo "$HEADER_COMMENT_PS1"
    cat "$SCRIPTS_DIR/setup-user-mcp.ps1"
} > "$DEPLOY_DIR/setup-user-mcp.ps1"
GENERATED=$((GENERATED + 1))

# ============================================================
# Summary
# ============================================================
echo ""
echo "========================================"
echo "Build complete: $GENERATED scripts generated in deploy/"
echo "========================================"
echo ""
ls -la "$DEPLOY_DIR/"
echo ""
echo "These scripts are self-contained and ready for MDM deployment."
echo "No dependencies on this repo, Google Drive, or gh CLI."
