#!/usr/bin/env bash
# build-deploy.sh — Generates self-contained deploy/ scripts from scripts/ + shared/
#
# Reads shared content files and embeds them into deploy versions of setup scripts.
# The deploy/ scripts have zero dependencies on the repo or Google Drive — they can
# be deployed to any endpoint via MDM (Jamf, Intune) or run manually.
#
# Usage: bash scripts/build-deploy.sh   (run from repo root)
#
# CROSS-PLATFORM NOTE: This script is intentionally bash-only (no .ps1 variant).
# It's a build step that produces platform-independent output (both .sh and .ps1
# deploy scripts). The result is committed to git, so both platforms get identical
# deploy/ contents. A parallel PS1 would double maintenance for no output difference.
# On Windows, aitools.ps1 invokes this via Git Bash (a prerequisite for Claude Code).
# See .claude/rules/cross-platform.md "Approved exceptions" for the exception record.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPTS_DIR="$REPO_ROOT/scripts"
DEPLOY_DIR="$REPO_ROOT/deploy"
SHARED_DIR="$REPO_ROOT/shared"

# --- Build logging (timestamped) ---
SCRIPT_NAME="build-deploy"
blog() { printf '[%s] [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$SCRIPT_NAME" "$1"; }
blog_ok() { blog "OK: $1"; }
blog_error() { blog "ERROR: $1" >&2; }

# Shared content files
CLAUDE_SHARED="$SHARED_DIR/claude-shared.md"

# Verify shared files exist
if [ ! -f "$CLAUDE_SHARED" ]; then
    blog_error "Required shared file not found: $CLAUDE_SHARED"
    exit 1
fi
for skill_file in "$SHARED_DIR/skills/chrome-devtools/SKILL.md" "$SHARED_DIR/skills/a11y-debugging/SKILL.md"; do
    if [ ! -f "$skill_file" ]; then
        blog_error "Required skill file not found: $skill_file"
        exit 1
    fi
done

# Read shared content
CLAUDE_SHARED_CONTENT=$(cat "$CLAUDE_SHARED")

# --- Profile interpolation ---
# Read profile from user repo, interpolate identity placeholders.
# Fallback: use defaults if profile not found (build never fails).
PROFILE_NAME="Jose"
PROFILE_COMPANY="Nobul"
IDENTITY_GIT_NAME="Jose"
IDENTITY_GIT_EMAIL="jose@nobul.tech"

CONFIG="$HOME/.config/ai-tooling/config.json"
if [ -f "$CONFIG" ] && command -v node &>/dev/null; then
    PROFILE_VALS=$(node -e "
const fs = require('fs'), path = require('path'), os = require('os');
try {
    const cfg = JSON.parse(fs.readFileSync(process.argv[1], 'utf8'));
    const repo = cfg.userRepoPath;
    const alias = cfg.machineAlias || '';
    if (!repo) throw new Error('no userRepoPath');
    const pf = path.join(repo, 'profile.json');
    const p = JSON.parse(fs.readFileSync(pf, 'utf8'));
    let prof, ident;
    if (p.version === 2) {
        prof = p.profiles[alias]
            || Object.values(p.profiles).find(pr => pr.machine && pr.machine.hostname === os.hostname())
            || Object.values(p.profiles)[0];
        ident = p.identity;
    } else {
        prof = { name: p.name, company: p.company || '' };
        ident = { git: { name: (p.git && p.git.name) || p.name, email: (p.git && p.git.email) || p.email } };
    }
    // Output as KEY=VALUE lines for bash eval
    console.log('PROFILE_NAME=' + JSON.stringify(prof.name));
    console.log('PROFILE_COMPANY=' + JSON.stringify(prof.company));
    console.log('IDENTITY_GIT_NAME=' + JSON.stringify(ident.git.name));
    console.log('IDENTITY_GIT_EMAIL=' + JSON.stringify(ident.git.email));
} catch(e) { process.exit(1); }
" "$CONFIG" 2>/dev/null) && eval "$PROFILE_VALS"
fi

# Interpolate placeholders
CLAUDE_SHARED_CONTENT="${CLAUDE_SHARED_CONTENT//\{\{PROFILE_NAME\}\}/$PROFILE_NAME}"
CLAUDE_SHARED_CONTENT="${CLAUDE_SHARED_CONTENT//\{\{PROFILE_COMPANY\}\}/$PROFILE_COMPANY}"
CLAUDE_SHARED_CONTENT="${CLAUDE_SHARED_CONTENT//\{\{IDENTITY_GIT_NAME\}\}/$IDENTITY_GIT_NAME}"
CLAUDE_SHARED_CONTENT="${CLAUDE_SHARED_CONTENT//\{\{IDENTITY_GIT_EMAIL\}\}/$IDENTITY_GIT_EMAIL}"

blog "Profile interpolation: name=$PROFILE_NAME company=$PROFILE_COMPANY"

# Clean and recreate deploy/
rm -rf "$DEPLOY_DIR"
mkdir -p "$DEPLOY_DIR"

GENERATED=0

# Header for generated files
HEADER_COMMENT_BASH="# Generated by scripts/build-deploy.sh — do not edit directly."
HEADER_COMMENT_PS1="# Generated by scripts/build-deploy.sh — do not edit directly."

# ============================================================
# Bash logging helpers (embedded into each bash deploy script)
# ============================================================
bash_logging_helpers() {
    local script_name="$1"
    cat <<'LOGGING_BASH'
# --- Logging ---
LOG_DIR="$HOME/Library/Logs/ai-tooling"
[ "$(uname -s)" != "Darwin" ] && LOG_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/ai-tooling"
LOG_FILE="$LOG_DIR/deploy.log"
LOGGING_BASH
    echo "SCRIPT_NAME=\"$script_name\""
    cat <<'LOGGING_BASH'
ERRORS=0

mkdir -p "$LOG_DIR"

log()       { printf '[%s] [%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$SCRIPT_NAME" "$1" | tee -a "$LOG_FILE"; }
log_ok()    { log "OK: $1"; }
log_error() { log "ERROR: $1"; ERRORS=$((ERRORS + 1)); }
log_warn()  { log "WARN: $1"; }
LOGGING_BASH
}

# PowerShell logging helpers
ps1_logging_helpers() {
    local script_name="$1"
    cat <<LOGGING_PS1
# --- Logging ---
\$logDir = Join-Path \$env:LOCALAPPDATA "ai-tooling"
\$logFile = Join-Path \$logDir "deploy.log"
\$scriptName = "$script_name"
\$errors = 0

if (-not (Test-Path \$logDir)) { New-Item -ItemType Directory -Path \$logDir -Force | Out-Null }

function Log(\$msg) {
    \$ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    \$line = "[\$ts] [\$scriptName] \$msg"
    Write-Host \$line
    Add-Content -Path \$logFile -Value \$line
}
function LogOk(\$msg)    { Log "OK: \$msg" }
function LogError(\$msg) { Log "ERROR: \$msg"; \$script:errors++ }
function LogWarn(\$msg)  { Log "WARN: \$msg" }
LOGGING_PS1
}

# Bash exit footer
bash_exit_footer() {
    cat <<'EXIT_BASH'

# --- Exit ---
if [ "$ERRORS" -gt 0 ]; then
    log "FAILED with $ERRORS error(s). See log: $LOG_FILE"
    exit 1
else
    log "COMPLETED successfully"
    exit 0
fi
EXIT_BASH
}

# PowerShell exit footer
ps1_exit_footer() {
    cat <<'EXIT_PS1'

# --- Exit ---
if ($errors -gt 0) {
    Log "FAILED with $errors error(s). See log: $logFile"
    exit 1
} else {
    Log "COMPLETED successfully"
    exit 0
}
EXIT_PS1
}

# ============================================================
# Backup helpers (embedded into deploy scripts that overwrite files)
# ============================================================
bash_backup_helper() {
    cat <<'BACKUP_BASH'

# Backup a file before overwriting. Keeps at most $max_backups copies.
backup_file() {
    local file="$1" max_backups=20
    [ -f "$file" ] || return 0
    local ts
    ts=$(date -u +%Y-%m-%dT%H%M%SZ)
    cp "$file" "${file}.bak.${ts}"
    # Prune oldest beyond limit
    ls -1t "${file}.bak."* 2>/dev/null | tail -n +$((max_backups + 1)) | xargs rm -f 2>/dev/null
    log "Backed up $file"
}
BACKUP_BASH
}

ps1_backup_helper() {
    cat <<'BACKUP_PS1'

# Backup a file before overwriting. Keeps at most $MaxBackups copies.
function Backup-File {
    param([string]$FilePath, [int]$MaxBackups = 20)
    if (-not (Test-Path $FilePath)) { return }
    $ts = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHHmmssZ")
    $backupPath = "${FilePath}.bak.${ts}"
    Copy-Item -Path $FilePath -Destination $backupPath
    # Prune oldest beyond limit
    $backups = Get-ChildItem -Path "${FilePath}.bak.*" | Sort-Object LastWriteTime -Descending
    if ($backups.Count -gt $MaxBackups) {
        $backups | Select-Object -Skip $MaxBackups | Remove-Item -Force
    }
    Log "Backed up $FilePath"
}
BACKUP_PS1
}

# ============================================================
# OS guard helpers (embedded into template-generated deploy scripts)
# ============================================================
bash_os_guard() {
    cat <<'OS_GUARD_BASH'

# --- OS guard ---
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        log_error "This script is for macOS/Linux. On Windows, use the .ps1 version."
        exit 1 ;;
esac
OS_GUARD_BASH
}

ps1_os_guard() {
    cat <<'OS_GUARD_PS1'

# --- OS guard ---
if ($PSVersionTable.PSVersion.Major -ge 6 -and -not $IsWindows) {
    LogError "This script is for Windows. On macOS/Linux, use the .sh version."
    exit 1
}
OS_GUARD_PS1
}

# ============================================================
# 1. deploy/setup-user-claude.sh
# ============================================================
blog "Generating deploy/setup-user-claude.sh"

{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    cat <<'BLOCK'
# setup-user-claude.sh — Creates user-level ~/.claude/CLAUDE.md
# Self-contained: shared preferences are embedded below. No repo or Drive needed.
# Safe to re-run — replaces existing file with latest version.

set -euo pipefail

BLOCK
    bash_logging_helpers "setup-user-claude"
    bash_os_guard
    bash_backup_helper
    cat <<'BLOCK'

# --- Auto-detect machine info ---
OS_NAME=$(uname -s)
ARCH=$(uname -m)
HOSTNAME=$(hostname -s 2>/dev/null || hostname)
SHELL_NAME=$(basename "${SHELL:-/bin/bash}")

CLAUDE_DIR="$HOME/.claude"
CLAUDE_MD="$CLAUDE_DIR/CLAUDE.md"

mkdir -p "$CLAUDE_DIR"
log "Ensuring $CLAUDE_DIR exists"

backup_file "$CLAUDE_MD"
if [ -f "$CLAUDE_MD" ]; then
    rm "$CLAUDE_MD"
    log "Removed existing $CLAUDE_MD"
fi

# --- Embedded shared preferences (from shared/claude-shared.md) ---
BLOCK
    echo 'read -r -d "" SHARED_CONTENT <<'"'"'__EMBEDDED_CLAUDE_SHARED__'"'"' || true'
    echo "$CLAUDE_SHARED_CONTENT"
    echo '__EMBEDDED_CLAUDE_SHARED__'
    cat <<'BLOCK'

# --- Write CLAUDE.md ---
cat > "$CLAUDE_MD" << CLAUDE_EOF
${SHARED_CONTENT}

## Machine-Specific

- Machine: ${OS_NAME} ${ARCH} (${HOSTNAME})
- Shell: ${SHELL_NAME}
CLAUDE_EOF

log_ok "Wrote $CLAUDE_MD"
log "Machine: $OS_NAME $ARCH ($HOSTNAME), Shell: $SHELL_NAME"
BLOCK
    bash_exit_footer
} > "$DEPLOY_DIR/setup-user-claude.sh"

chmod +x "$DEPLOY_DIR/setup-user-claude.sh"
GENERATED=$((GENERATED + 1))

# ============================================================
# 2. deploy/setup-user-claude.ps1
# ============================================================
blog "Generating deploy/setup-user-claude.ps1"

{
    echo "$HEADER_COMMENT_PS1"
    cat <<'BLOCK'
# setup-user-claude.ps1 — Creates user-level ~/.claude/CLAUDE.md on Windows
# Self-contained: shared preferences are embedded below. No repo or Drive needed.
# Safe to re-run — replaces existing file with latest version.

BLOCK
    ps1_logging_helpers "setup-user-claude"
    ps1_os_guard
    ps1_backup_helper
    cat <<'BLOCK'

# --- Auto-detect machine info ---
$osInfo = (Get-CimInstance Win32_OperatingSystem).Caption
$hostname = $env:COMPUTERNAME

$claudeDir = Join-Path $env:USERPROFILE ".claude"
$claudeMd = Join-Path $claudeDir "CLAUDE.md"

if (-not (Test-Path $claudeDir)) {
    New-Item -ItemType Directory -Path $claudeDir -Force | Out-Null
    Log "Created $claudeDir"
}

Backup-File -FilePath $claudeMd
if (Test-Path $claudeMd) {
    Remove-Item $claudeMd
    Log "Removed existing $claudeMd"
}

# --- Embedded shared preferences (from shared/claude-shared.md) ---
$sharedContent = @'
BLOCK
    echo "$CLAUDE_SHARED_CONTENT"
    cat <<'BLOCK'
'@

# --- Write CLAUDE.md ---
$content = @"
$sharedContent

## Machine-Specific

- Machine: $osInfo ($hostname)
- Shell: bash (Claude Code requires Git Bash on Windows)
"@

[System.IO.File]::WriteAllText($claudeMd, $content, [System.Text.UTF8Encoding]::new($false))
LogOk "Wrote $claudeMd"
Log "Machine: $osInfo ($hostname)"
BLOCK
    ps1_exit_footer
} > "$DEPLOY_DIR/setup-user-claude.ps1"

GENERATED=$((GENERATED + 1))

# ============================================================
# 3. deploy/setup-user-cursor.sh
# ============================================================
blog "Generating deploy/setup-user-cursor.sh"

{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    cat <<'BLOCK'
# setup-user-cursor.sh — Sets up Cursor CLI + dependencies on macOS/Linux
# Self-contained. No repo or Drive needed.
# Safe to re-run — checks each step and skips what's already done.
#
# Does three things:
#   1. Installs ripgrep (rg) if not already present (required by Cursor CLI)
#   2. Installs Cursor CLI (agent command) if not already present
#   3. Writes ~/.cursor/cli-config.json (skips if already up to date)

set -euo pipefail

BLOCK
    bash_logging_helpers "setup-user-cursor"
    bash_os_guard
    cat <<'BLOCK'

CURSOR_DIR="$HOME/.cursor"
CLI_CONFIG="$CURSOR_DIR/cli-config.json"

# --- 1. ripgrep (rg) ---
log "Step 1: ripgrep (rg)"

if command -v rg &>/dev/null; then
    RG_VERSION=$(rg --version | head -1)
    log_ok "Already installed: $RG_VERSION"
else
    if command -v brew &>/dev/null; then
        log "Installing ripgrep via brew..."
        brew install ripgrep
        if command -v rg &>/dev/null; then
            log_ok "Installed: $(rg --version | head -1)"
        else
            log_error "brew install completed but 'rg' not found in PATH"
        fi
    else
        log_error "Homebrew not found. Install ripgrep manually: brew install ripgrep"
    fi
fi

# --- 2. Cursor CLI (agent) ---
log "Step 2: Cursor CLI (agent)"

if command -v agent &>/dev/null; then
    AGENT_VERSION=$(agent --version)
    log_ok "Already installed: $AGENT_VERSION"
else
    log "Installing Cursor CLI..."
    curl https://cursor.com/install -fsS | bash
    if command -v agent &>/dev/null; then
        log_ok "Installed: $(agent --version)"
    else
        log_error "Cursor CLI install completed but 'agent' not found in PATH (restart terminal)"
    fi
fi

# --- 3. cli-config.json ---
log "Step 3: cli-config.json"

EXPECTED_CONFIG='{
  "version": 1,
  "editor": {
    "vimMode": false
  },
  "permissions": {
    "allow": [],
    "deny": []
  }
}'

mkdir -p "$CURSOR_DIR"

if [ -f "$CLI_CONFIG" ]; then
    EXISTING_CONFIG=$(cat "$CLI_CONFIG")
    if [ "$EXISTING_CONFIG" = "$EXPECTED_CONFIG" ]; then
        log_ok "Already up to date: $CLI_CONFIG"
    else
        printf '%s' "$EXPECTED_CONFIG" > "$CLI_CONFIG"
        log_ok "Updated: $CLI_CONFIG"
    fi
else
    printf '%s' "$EXPECTED_CONFIG" > "$CLI_CONFIG"
    log_ok "Created: $CLI_CONFIG"
fi
BLOCK
    bash_exit_footer
} > "$DEPLOY_DIR/setup-user-cursor.sh"

chmod +x "$DEPLOY_DIR/setup-user-cursor.sh"
GENERATED=$((GENERATED + 1))

# ============================================================
# 4. deploy/setup-user-cursor.ps1
# ============================================================
blog "Generating deploy/setup-user-cursor.ps1"

{
    echo "$HEADER_COMMENT_PS1"
    cat <<'BLOCK'
# setup-user-cursor.ps1 — Sets up Cursor CLI + dependencies on Windows
# Self-contained. No repo or Drive needed.
# Safe to re-run — checks each step and skips what's already done.
#
# Does three things:
#   1. Installs ripgrep (rg) if not already present (required by Cursor CLI)
#   2. Installs Cursor CLI (agent command) if not already present
#   3. Writes ~/.cursor/cli-config.json (skips if already up to date)

BLOCK
    ps1_logging_helpers "setup-user-cursor"
    ps1_os_guard
    cat <<'BLOCK'

# Helper: refresh PATH from registry (picks up winget installs in same session)
function Refresh-Path {
    $machinePath = [Environment]::GetEnvironmentVariable("Path", "Machine")
    $userPath = [Environment]::GetEnvironmentVariable("Path", "User")
    $env:Path = "$machinePath;$userPath"
}

$cursorDir = Join-Path $env:USERPROFILE ".cursor"
$cliConfig = Join-Path $cursorDir "cli-config.json"

# --- 1. ripgrep (rg) ---
Log "Step 1: ripgrep (rg)"

$rgCmd = Get-Command rg -ErrorAction SilentlyContinue
if ($rgCmd) {
    $rgVersion = (rg --version | Select-Object -First 1)
    LogOk "Already installed: $rgVersion"
} else {
    Log "Installing ripgrep via winget..."
    winget install BurntSushi.ripgrep.MSVC --accept-package-agreements --accept-source-agreements
    Refresh-Path
    $rgCmd = Get-Command rg -ErrorAction SilentlyContinue
    if ($rgCmd) {
        LogOk "Installed: $(rg --version | Select-Object -First 1)"
    } else {
        LogError "winget install completed but 'rg' not found in PATH (restart terminal)"
    }
}

# --- 2. Cursor CLI (agent) ---
Log "Step 2: Cursor CLI (agent)"

$agentCmd = Get-Command agent -ErrorAction SilentlyContinue
if ($agentCmd) {
    $agentVersion = agent --version
    LogOk "Already installed: $agentVersion"
} else {
    Log "Installing Cursor CLI..."
    Invoke-Expression (Invoke-RestMethod 'https://cursor.com/install?win32=true')
    $agentCmd = Get-Command agent -ErrorAction SilentlyContinue
    if ($agentCmd) {
        LogOk "Installed: $(agent --version)"
    } else {
        LogError "Cursor CLI install completed but 'agent' not found in PATH (restart terminal)"
    }
}

# --- 3. cli-config.json ---
Log "Step 3: cli-config.json"

$expectedConfig = @'
{
  "version": 1,
  "editor": {
    "vimMode": false
  },
  "permissions": {
    "allow": [],
    "deny": []
  }
}
'@

if (-not (Test-Path $cursorDir)) {
    New-Item -ItemType Directory -Path $cursorDir -Force | Out-Null
    Log "Created $cursorDir"
}

if (Test-Path $cliConfig) {
    $existingConfig = (Get-Content -Path $cliConfig -Raw).TrimEnd()
    if ($existingConfig -eq $expectedConfig) {
        LogOk "Already up to date: $cliConfig"
    } else {
        [System.IO.File]::WriteAllText($cliConfig, $expectedConfig, [System.Text.UTF8Encoding]::new($false))
        LogOk "Updated: $cliConfig"
    }
} else {
    [System.IO.File]::WriteAllText($cliConfig, $expectedConfig, [System.Text.UTF8Encoding]::new($false))
    LogOk "Created: $cliConfig"
}
BLOCK
    ps1_exit_footer
} > "$DEPLOY_DIR/setup-user-cursor.ps1"

GENERATED=$((GENERATED + 1))

# ============================================================
# 5-6. deploy/setup-cursor-mcp.sh and .ps1 (copy as-is)
# ============================================================
blog "Copying deploy/setup-cursor-mcp.sh"
{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    # Strip the shebang from source and append the rest
    tail -n +2 "$SCRIPTS_DIR/setup-cursor-mcp.sh"
} > "$DEPLOY_DIR/setup-cursor-mcp.sh"
chmod +x "$DEPLOY_DIR/setup-cursor-mcp.sh"
GENERATED=$((GENERATED + 1))

blog "Copying deploy/setup-cursor-mcp.ps1"
{
    echo "$HEADER_COMMENT_PS1"
    cat "$SCRIPTS_DIR/setup-cursor-mcp.ps1"
} > "$DEPLOY_DIR/setup-cursor-mcp.ps1"
GENERATED=$((GENERATED + 1))

# ============================================================
# 7-8. deploy/setup-vercelcli.sh and .ps1 (copy as-is)
# ============================================================
blog "Copying deploy/setup-vercelcli.sh"
{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    # Strip the shebang from source and append the rest
    tail -n +2 "$SCRIPTS_DIR/setup-vercelcli.sh"
} > "$DEPLOY_DIR/setup-vercelcli.sh"
chmod +x "$DEPLOY_DIR/setup-vercelcli.sh"
GENERATED=$((GENERATED + 1))

blog "Copying deploy/setup-vercelcli.ps1"
{
    echo "$HEADER_COMMENT_PS1"
    cat "$SCRIPTS_DIR/setup-vercelcli.ps1"
} > "$DEPLOY_DIR/setup-vercelcli.ps1"
GENERATED=$((GENERATED + 1))

# ============================================================
# 9-10. deploy/setup-pandoc.sh and .ps1 (copy as-is)
# ============================================================
blog "Copying deploy/setup-pandoc.sh"
{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    # Strip the shebang from source and append the rest
    tail -n +2 "$SCRIPTS_DIR/setup-pandoc.sh"
} > "$DEPLOY_DIR/setup-pandoc.sh"
chmod +x "$DEPLOY_DIR/setup-pandoc.sh"
GENERATED=$((GENERATED + 1))

blog "Copying deploy/setup-pandoc.ps1"
{
    echo "$HEADER_COMMENT_PS1"
    cat "$SCRIPTS_DIR/setup-pandoc.ps1"
} > "$DEPLOY_DIR/setup-pandoc.ps1"
GENERATED=$((GENERATED + 1))

# ============================================================
# 11-12. deploy/setup-user-mcp.sh and .ps1 (template with embedded skills)
# ============================================================
# The scripts/ versions read skills from shared/skills/ (repo-relative).
# The deploy/ versions must be self-contained, so we embed SKILL.md content
# inline using heredocs, replacing the file-copy deploy_skill() function.

# Read skill content
SKILL_CHROME_DEVTOOLS=$(cat "$SHARED_DIR/skills/chrome-devtools/SKILL.md")
SKILL_A11Y_DEBUGGING=$(cat "$SHARED_DIR/skills/a11y-debugging/SKILL.md")

blog "Generating deploy/setup-user-mcp.sh (with embedded skills)"
{
    echo '#!/usr/bin/env bash'
    echo "$HEADER_COMMENT_BASH"
    # Take everything from source up to (but not including) the skills section
    sed -n '2,/^# --- Deploy Chrome DevTools skills ---$/{ /^# --- Deploy Chrome DevTools skills ---$/!p; }' \
        "$SCRIPTS_DIR/setup-user-mcp.sh"
    # Emit self-contained skills deployment using heredocs
    cat <<'SKILLS_HEADER'

# --- Deploy Chrome DevTools skills (embedded) ---
# Vendored from https://github.com/ChromeDevTools/chrome-devtools-mcp/tree/main/skills
# Content embedded at build time by build-deploy.sh for self-contained deployment.

SKILLS_DEST="$HOME/.claude/skills"
SKILLS_DEST_CURSOR="$HOME/.cursor/skills"

SKILLS_HEADER
    # Deploy to ~/.claude/skills/ (Claude Code)
    echo 'log "Deploying skills to $SKILLS_DEST..."'
    echo 'mkdir -p "$SKILLS_DEST/chrome-devtools"'
    echo 'cat > "$SKILLS_DEST/chrome-devtools/SKILL.md" <<'"'"'__SKILL_CHROME_DEVTOOLS__'"'"
    echo "$SKILL_CHROME_DEVTOOLS"
    echo '__SKILL_CHROME_DEVTOOLS__'
    echo 'log_ok "Deployed skill: chrome-devtools -> $SKILLS_DEST/chrome-devtools"'
    echo ''
    echo 'mkdir -p "$SKILLS_DEST/a11y-debugging"'
    echo 'cat > "$SKILLS_DEST/a11y-debugging/SKILL.md" <<'"'"'__SKILL_A11Y_DEBUGGING__'"'"
    echo "$SKILL_A11Y_DEBUGGING"
    echo '__SKILL_A11Y_DEBUGGING__'
    echo 'log_ok "Deployed skill: a11y-debugging -> $SKILLS_DEST/a11y-debugging"'
    echo ''
    # Deploy to ~/.cursor/skills/ (Cursor Agent CLI)
    echo 'log "Deploying skills to $SKILLS_DEST_CURSOR..."'
    echo 'mkdir -p "$SKILLS_DEST_CURSOR/chrome-devtools"'
    echo 'cat > "$SKILLS_DEST_CURSOR/chrome-devtools/SKILL.md" <<'"'"'__SKILL_CHROME_DEVTOOLS_CURSOR__'"'"
    echo "$SKILL_CHROME_DEVTOOLS"
    echo '__SKILL_CHROME_DEVTOOLS_CURSOR__'
    echo 'log_ok "Deployed skill: chrome-devtools -> $SKILLS_DEST_CURSOR/chrome-devtools"'
    echo ''
    echo 'mkdir -p "$SKILLS_DEST_CURSOR/a11y-debugging"'
    echo 'cat > "$SKILLS_DEST_CURSOR/a11y-debugging/SKILL.md" <<'"'"'__SKILL_A11Y_DEBUGGING_CURSOR__'"'"
    echo "$SKILL_A11Y_DEBUGGING"
    echo '__SKILL_A11Y_DEBUGGING_CURSOR__'
    echo 'log_ok "Deployed skill: a11y-debugging -> $SKILLS_DEST_CURSOR/a11y-debugging"'
    echo ''
    # Emit exit footer from source
    sed -n '/^# --- Exit ---$/,$ p' "$SCRIPTS_DIR/setup-user-mcp.sh"
} > "$DEPLOY_DIR/setup-user-mcp.sh"
chmod +x "$DEPLOY_DIR/setup-user-mcp.sh"
GENERATED=$((GENERATED + 1))

blog "Generating deploy/setup-user-mcp.ps1 (with embedded skills)"
{
    echo "$HEADER_COMMENT_PS1"
    # Take everything from source up to (but not including) the skills section
    # PS1 files have CRLF -- strip \r for sed matching, then re-add for PS1 output
    tr -d '\r' < "$SCRIPTS_DIR/setup-user-mcp.ps1" | \
        sed -n '1,/^# --- Deploy Chrome DevTools skills ---$/{ /^# --- Deploy Chrome DevTools skills ---$/!p; }' | \
        sed 's/$/'$'\r''/'
    # Emit self-contained skills deployment using PS1 here-strings
    cat <<'SKILLS_PS1_HEADER'

# --- Deploy Chrome DevTools skills (embedded) ---
# Vendored from https://github.com/ChromeDevTools/chrome-devtools-mcp/tree/main/skills
# Content embedded at build time by build-deploy.sh for self-contained deployment.

$skillsDest = Join-Path $env:USERPROFILE ".claude" "skills"
$skillsDestCursor = Join-Path $env:USERPROFILE ".cursor" "skills"

SKILLS_PS1_HEADER
    # Deploy to ~/.claude/skills/ (Claude Code)
    echo 'Log "Deploying skills to $skillsDest..."'
    echo '$chromeDevtoolsDir = Join-Path $skillsDest "chrome-devtools"'
    echo 'if (-not (Test-Path $chromeDevtoolsDir)) { New-Item -ItemType Directory -Path $chromeDevtoolsDir -Force | Out-Null }'
    echo '$chromeDevtoolsSkill = @'"'"
    echo "$SKILL_CHROME_DEVTOOLS"
    echo "'"'@'
    echo '$chromeDevtoolsDest = Join-Path $chromeDevtoolsDir "SKILL.md"'
    echo '[System.IO.File]::WriteAllText($chromeDevtoolsDest, $chromeDevtoolsSkill, [System.Text.UTF8Encoding]::new($false))'
    echo 'LogOk "Deployed skill: chrome-devtools -> $chromeDevtoolsDest"'
    echo ''
    echo '$a11yDir = Join-Path $skillsDest "a11y-debugging"'
    echo 'if (-not (Test-Path $a11yDir)) { New-Item -ItemType Directory -Path $a11yDir -Force | Out-Null }'
    echo '$a11ySkill = @'"'"
    echo "$SKILL_A11Y_DEBUGGING"
    echo "'"'@'
    echo '$a11yDest = Join-Path $a11yDir "SKILL.md"'
    echo '[System.IO.File]::WriteAllText($a11yDest, $a11ySkill, [System.Text.UTF8Encoding]::new($false))'
    echo 'LogOk "Deployed skill: a11y-debugging -> $a11yDest"'
    echo ''
    # Deploy to ~/.cursor/skills/ (Cursor Agent CLI)
    echo 'Log "Deploying skills to $skillsDestCursor..."'
    echo '$chromeDevtoolsDirCursor = Join-Path $skillsDestCursor "chrome-devtools"'
    echo 'if (-not (Test-Path $chromeDevtoolsDirCursor)) { New-Item -ItemType Directory -Path $chromeDevtoolsDirCursor -Force | Out-Null }'
    echo '$chromeDevtoolsDestCursor = Join-Path $chromeDevtoolsDirCursor "SKILL.md"'
    echo '[System.IO.File]::WriteAllText($chromeDevtoolsDestCursor, $chromeDevtoolsSkill, [System.Text.UTF8Encoding]::new($false))'
    echo 'LogOk "Deployed skill: chrome-devtools -> $chromeDevtoolsDestCursor"'
    echo ''
    echo '$a11yDirCursor = Join-Path $skillsDestCursor "a11y-debugging"'
    echo 'if (-not (Test-Path $a11yDirCursor)) { New-Item -ItemType Directory -Path $a11yDirCursor -Force | Out-Null }'
    echo '$a11yDestCursor = Join-Path $a11yDirCursor "SKILL.md"'
    echo '[System.IO.File]::WriteAllText($a11yDestCursor, $a11ySkill, [System.Text.UTF8Encoding]::new($false))'
    echo 'LogOk "Deployed skill: a11y-debugging -> $a11yDestCursor"'
    echo ''
    # Emit exit footer from source (strip \r for matching, re-add for PS1)
    tr -d '\r' < "$SCRIPTS_DIR/setup-user-mcp.ps1" | \
        sed -n '/^# --- Exit ---$/,$ p' | \
        sed 's/$/'$'\r''/'
} > "$DEPLOY_DIR/setup-user-mcp.ps1"
GENERATED=$((GENERATED + 1))

# ============================================================
# Summary
# ============================================================
# ============================================================
# Post-build: Validate PS1 syntax (Windows only)
# ============================================================
# On Windows (Git Bash), validate all generated .ps1 files with ParseFile.
# Catches encoding issues (em-dash, smart quotes) and PS 5.1 syntax errors
# at build time rather than install time.
# On macOS, skip -- pwsh may not be installed.
case "$(uname -s)" in
    MINGW*|MSYS*|CYGWIN*)
        blog "Validating generated PS1 scripts..."
        PS1_ERRORS=0
        for ps1_file in "$DEPLOY_DIR"/*.ps1; do
            [ -f "$ps1_file" ] || continue
            ps1_name=$(basename "$ps1_file")
            if ! powershell.exe -NoProfile -Command "
                \$e = \$null
                \$null = [System.Management.Automation.Language.Parser]::ParseFile('$(cygpath -w "$ps1_file")', [ref]\$null, [ref]\$e)
                if (\$e.Count -gt 0) {
                    foreach (\$err in \$e) { Write-Host \"  line \$(\$err.Extent.StartLineNumber): \$(\$err.Message)\" }
                    exit 1
                }
            " 2>/dev/null; then
                blog_error "$ps1_name has parse errors on this PowerShell version"
                PS1_ERRORS=$((PS1_ERRORS + 1))
            fi
        done
        if [ "$PS1_ERRORS" -gt 0 ]; then
            blog_error "$PS1_ERRORS PS1 file(s) failed validation"
            exit 1
        else
            blog_ok "All PS1 files passed validation"
        fi
        ;;
    *)
        # macOS/Linux: PS1 validation skipped (pwsh may not be installed)
        ;;
esac

blog_ok "Build complete: $GENERATED scripts generated in deploy/"
ls -la "$DEPLOY_DIR/"
blog "Scripts are self-contained and ready for MDM deployment"
